/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package waleta_system.Maintenance.view.jadwal;

import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.TimeZone;
import javax.swing.border.TitledBorder;
import waleta_system.Maintenance.view.MainFrame_Maintenance;

/**
 *
 * @author User
 */
public class DaftarJadwalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DaftarAlatJPanel
     *
     * @param mainJFrame
     * @param idJadwal
     */
    public DaftarJadwalJPanel(MainFrame_Maintenance mainJFrame, int idJadwal, boolean isHariIni) {
        initComponents();

        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("EEEEE, dd MMMM yyyy", new Locale("in", "ID"));
        simpleDateFormat.setTimeZone(TimeZone.getTimeZone("Asia/Jakarta"));

        if (isHariIni) {
            if (mainJFrame.jadwalHariInis.get(idJadwal).getIdAlat() != null && mainJFrame.jadwalHariInis.get(idJadwal).getNamaAlat() != null) {
                String idAlat;
                if (mainJFrame.jadwalHariInis.get(idJadwal).getIdAlat().equals("")) {
                    idAlat = "-";
                } else {
                    idAlat = mainJFrame.jadwalHariInis.get(idJadwal).getIdAlat();

                    if (!mainJFrame.jadwalHariInis.get(idJadwal).getNamaAlat().equals("")) {
                        idAlat += " - " + mainJFrame.jadwalHariInis.get(idJadwal).getNamaAlat();
                    }
                }
                jLabeltIdAlat.setText(idAlat);
            } else {
                jLabeltIdAlat.setText("-");
            }
            if (mainJFrame.jadwalHariInis.get(idJadwal).getTglKegiatan().equals("")) {
                jLabelTglKegiatan.setText("-");
            } else {
                jLabelTglKegiatan.setText(simpleDateFormat.format(mainJFrame.jadwalHariInis.get(idJadwal).getTglKegiatan()));
            }
            jLabelPetugas.setVisible(false);
            if (mainJFrame.jadwalHariInis.get(idJadwal).getNamaKegiatan().equals("")) {
                jLabelKegiatan.setText("-");
            } else {
                jLabelKegiatan.setText(mainJFrame.jadwalHariInis.get(idJadwal).getNamaKegiatan());
            }
        } else {
            if (mainJFrame.jadwalTerlambats.get(idJadwal).getIdAlat() != null && mainJFrame.jadwalTerlambats.get(idJadwal).getNamaAlat() != null) {
                String idAlat;
                if (mainJFrame.jadwalTerlambats.get(idJadwal).getIdAlat().equals("")) {
                    idAlat = "-";
                } else {
                    idAlat = mainJFrame.jadwalTerlambats.get(idJadwal).getIdAlat();

                    if (!mainJFrame.jadwalTerlambats.get(idJadwal).getNamaAlat().equals("")) {
                        idAlat += " - " + mainJFrame.jadwalTerlambats.get(idJadwal).getNamaAlat();
                    }
                }
                jLabeltIdAlat.setText(idAlat);
            } else {
                jLabeltIdAlat.setText("-");
            }
            if (mainJFrame.jadwalTerlambats.get(idJadwal).getTglKegiatan().equals("")) {
                jLabelTglKegiatan.setText("-");
            } else {
                jLabelTglKegiatan.setText(simpleDateFormat.format(mainJFrame.jadwalTerlambats.get(idJadwal).getTglKegiatan()));
            }
            if (mainJFrame.jadwalTerlambats.get(idJadwal).getNamaPegawai().equals("")) {
                jLabelPetugas.setText("-");
            } else {
                jLabelPetugas.setText(mainJFrame.jadwalTerlambats.get(idJadwal).getNamaPegawai());
            }
            if (mainJFrame.jadwalTerlambats.get(idJadwal).getNamaKegiatan().equals("")) {
                jLabelKegiatan.setText("-");
            } else {
                jLabelKegiatan.setText(mainJFrame.jadwalTerlambats.get(idJadwal).getNamaKegiatan());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPetugas = new javax.swing.JLabel();
        jLabelKegiatan = new javax.swing.JLabel();
        jLabeltIdAlat = new javax.swing.JLabel();
        jLabelTglKegiatan = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(325, 32767));
        setMinimumSize(new java.awt.Dimension(325, 0));

        jLabelPetugas.setText("-");

        jLabelKegiatan.setText("-");

        jLabeltIdAlat.setText("-");

        jLabelTglKegiatan.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabeltIdAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTglKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelKegiatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeltIdAlat)
                    .addComponent(jLabelTglKegiatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPetugas)
                    .addComponent(jLabelKegiatan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelKegiatan;
    private javax.swing.JLabel jLabelPetugas;
    private javax.swing.JLabel jLabelTglKegiatan;
    private javax.swing.JLabel jLabeltIdAlat;
    // End of variables declaration//GEN-END:variables
}
