package waleta_system.HRD;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import waleta_system.Class.Utility;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class JDialog_Show_KK extends javax.swing.JDialog {

    String sql = null;
    ResultSet rs;
    PreparedStatement pst;
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date today = new Date();
    String id;

    public JDialog_Show_KK(java.awt.Frame parent, boolean modal, String nik, String nama) {
        super(parent, modal);
        initComponents();
        button_rotate_left.setIcon(Utility.ResizeImageIcon(new ImageIcon(getClass().getResource("/waleta_system/Images/rotate_page_counterclockwise_50px.png")), button_rotate_left.getWidth(), button_rotate_left.getHeight()));
        button_rotate_right.setIcon(Utility.ResizeImageIcon(new ImageIcon(getClass().getResource("/waleta_system/Images/rotate_page_clockwise_50px.png")), button_rotate_right.getWidth(), button_rotate_right.getHeight()));
        label_nik.setText(nik);
        label_nama.setText(nama);
    }

    public void show_data_local(String id) {
        try {
            button_rotate_left.setEnabled(true);
            button_rotate_right.setEnabled(true);
            this.id = id;
            lbl_Image.setIcon(Utility.ResizeImage("\\\\192.168.10.2\\Shared Folder\\DOKUMEN SISTEM\\FC_KK\\" + id + ".jpg", null, lbl_Image.getWidth(), lbl_Image.getHeight()));
//            String query = "SELECT `ktp_image` FROM `tb_karyawan` WHERE `id_pegawai`='" + id + "'";
//            rs = Utility.db.getStatement().executeQuery(query);
//            if (rs.next()) {
//                lbl_Image.setIcon(Utility.ResizeImage(null, rs.getBytes("ktp_image"), lbl_Image.getWidth(), lbl_Image.getHeight()));
//            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(JDialog_Show_KK.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void show_data_online(String id) {
        try {
            button_rotate_left.setEnabled(false);
            button_rotate_right.setEnabled(false);
            this.id = id;
            Utility.db_sub.connect();
            String query = "SELECT `foto_ktp` FROM `tb_karyawan` WHERE `id_pegawai`='" + id + "'";
            ResultSet result = Utility.db_sub.getStatement().executeQuery(query);
            if (result.next()) {
                String path = result.getString("foto_ktp").replace("194.163.41.103", "waleta019.com");
                URL url = new URL(path);
                HttpURLConnection conn = (HttpURLConnection) url.openConnection();
                conn.connect();
//                System.out.println("code:" + conn.getResponseCode());
                InputStream is = conn.getInputStream();
                ByteArrayOutputStream os = new ByteArrayOutputStream();
                byte[] buf = new byte[4096];
                int n;
                while ((n = is.read(buf)) >= 0) {
                    os.write(buf, 0, n);
                }
                os.close();
                is.close();
                conn.disconnect();
                byte[] data = os.toByteArray();

                lbl_Image.setIcon(Utility.ResizeImage(null, data, lbl_Image.getWidth(), lbl_Image.getHeight()));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(JDialog_Show_KK.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Image = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_nama = new javax.swing.JLabel();
        label_nik = new javax.swing.JLabel();
        button_rotate_left = new javax.swing.JButton();
        button_rotate_right = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Image.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Image.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lbl_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("NIK :");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Nama :");

        label_nama.setBackground(new java.awt.Color(255, 255, 255));
        label_nama.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        label_nama.setText("Nama :");

        label_nik.setBackground(new java.awt.Color(255, 255, 255));
        label_nik.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        label_nik.setText("NIK :");

        button_rotate_left.setBackground(new java.awt.Color(255, 255, 255));
        button_rotate_left.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_rotate_left.setToolTipText("Rotate Left");
        button_rotate_left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_rotate_leftActionPerformed(evt);
            }
        });

        button_rotate_right.setBackground(new java.awt.Color(255, 255, 255));
        button_rotate_right.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_rotate_right.setToolTipText("Rotate Right");
        button_rotate_right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_rotate_rightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nik)
                            .addComponent(label_nama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 718, Short.MAX_VALUE)
                        .addComponent(button_rotate_left, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_rotate_right, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_nik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_nama))
                    .addComponent(button_rotate_right, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_rotate_left, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Image, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_rotate_leftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_rotate_leftActionPerformed
        // TODO add your handling code here:
        File input = new File("\\\\192.168.10.2\\Shared Folder\\DOKUMEN SISTEM\\FC_KK\\" + id + ".JPG");
            File output = new File("\\\\192.168.10.2\\Shared Folder\\DOKUMEN SISTEM\\FC_KK\\" + id + ".JPG");
                Utility.rotate90(input, output, Utility.ROTATE_LEFT);
                lbl_Image.setIcon(Utility.ResizeImage("\\\\192.168.10.2\\Shared Folder\\DOKUMEN SISTEM\\FC_KK\\" + id + ".JPG", null, lbl_Image.getWidth(), lbl_Image.getHeight()));
    }//GEN-LAST:event_button_rotate_leftActionPerformed

    private void button_rotate_rightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_rotate_rightActionPerformed
        // TODO add your handling code here:
        File input = new File("\\\\192.168.10.2\\Shared Folder\\DOKUMEN SISTEM\\FC_KK\\" + id + ".JPG");
            File output = new File("\\\\192.168.10.2\\Shared Folder\\DOKUMEN SISTEM\\FC_KK\\" + id + ".JPG");
                Utility.rotate90(input, output, Utility.ROTATE_RIGHT);
                lbl_Image.setIcon(Utility.ResizeImage("\\\\192.168.10.2\\Shared Folder\\DOKUMEN SISTEM\\FC_KK\\" + id + ".JPG", null, lbl_Image.getWidth(), lbl_Image.getHeight()));
    }//GEN-LAST:event_button_rotate_rightActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JDialog_Show_KK(null, true, "test", "test").setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_rotate_left;
    private javax.swing.JButton button_rotate_right;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_nik;
    private javax.swing.JLabel lbl_Image;
    // End of variables declaration//GEN-END:variables
}
