package waleta_system.HRD;

import waleta_system.Class.Utility;
import java.awt.HeadlessException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import waleta_system.MainForm;

public class JDialog_Edit_Ijin_Keluar extends javax.swing.JDialog {

     
    String sql = null;
    ResultSet rs;
    PreparedStatement pst;
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date today = new Date();

    public JDialog_Edit_Ijin_Keluar(java.awt.Frame parent, boolean modal, String kode) {
        super(parent, modal);
        initComponents();
        try {
            
            sql = "SELECT `kode_keluar`, `tb_ijin_keluar`.`id_pegawai`, `tb_karyawan`.`nama_pegawai`, `tb_ijin_keluar`.`tanggal_keluar`, `jam_keluar`, `jam_kembali`, `tb_ijin_keluar`.`keterangan` "
                    + "FROM `tb_ijin_keluar` LEFT JOIN `tb_karyawan` ON `tb_ijin_keluar`.`id_pegawai` = `tb_karyawan`.`id_pegawai`"
                    + "WHERE `kode_keluar` = '" + kode + "'";
            rs = Utility.db.getStatement().executeQuery(sql);
            while (rs.next()) {
                label_kode.setText(rs.getString("kode_keluar"));
                label_id_pegawai.setText(rs.getString("id_pegawai"));
                label_nama_pegawai.setText(rs.getString("nama_pegawai"));
                
//                Date hh1 = new Date(rs.getTimestamp("jam_keluar").getTime());
//                Date mm1 = new Date(rs.getTimestamp("jam_keluar").getTime());
//                int hour1 = Integer.valueOf(new SimpleDateFormat("hh").format(hh1));
//                int minutes1 = Integer.valueOf(new SimpleDateFormat("mm").format(mm1));
//                Spinner_jam_keluar.setValue(hour1);
//                Spinner_menit_keluar.setValue(minutes1);
                
                if (rs.getTimestamp("jam_kembali") != null) {
                    Date hh2 = new Date(rs.getTimestamp("jam_kembali").getTime());
                    Date mm2 = new Date(rs.getTimestamp("jam_kembali").getTime());
                    int hour2 = Integer.valueOf(new SimpleDateFormat("hh").format(hh2));
                    int minutes2 = Integer.valueOf(new SimpleDateFormat("mm").format(mm2));
                    Spinner_jam_kembali.setValue(hour2);
                    Spinner_menit_kembali.setValue(minutes2);
                } else {
                    CheckBox_pulang.setSelected(true);
                    Spinner_jam_kembali.setEnabled(false);
                    Spinner_menit_kembali.setEnabled(false);
                }
                Date_Ijin.setDate(rs.getDate("tanggal_keluar"));
                txt_keterangan.setText(rs.getString("keterangan"));
            }
        } catch (Exception ex) {
            Logger.getLogger(JDialog_Edit_Ijin_Keluar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_kode = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Date_Ijin = new com.toedter.calendar.JDateChooser();
        txt_keterangan = new javax.swing.JTextField();
        Spinner_jam_kembali = new javax.swing.JSpinner();
        Spinner_menit_kembali = new javax.swing.JSpinner();
        button_save = new javax.swing.JButton();
        label_title = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CheckBox_pulang = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        label_nama_pegawai = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        label_id_pegawai = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Spinner_menit_keluar = new javax.swing.JSpinner();
        Spinner_jam_keluar = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ijin Karyawan Keluar");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Kode :");

        label_kode.setBackground(new java.awt.Color(255, 255, 255));
        label_kode.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label_kode.setText("0");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("Tanggal Ijin :");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("Jam Kembali :");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setText("Keterangan:");

        Date_Ijin.setBackground(new java.awt.Color(255, 255, 255));
        Date_Ijin.setDate(new Date());
        Date_Ijin.setDateFormatString("dd MMMM yyyy");

        txt_keterangan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        Spinner_jam_kembali.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Spinner_jam_kembali.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        Spinner_jam_kembali.setEditor(new javax.swing.JSpinner.NumberEditor(Spinner_jam_kembali, ""));

        Spinner_menit_kembali.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Spinner_menit_kembali.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        Spinner_menit_kembali.setEditor(new javax.swing.JSpinner.NumberEditor(Spinner_menit_kembali, ""));

        button_save.setBackground(new java.awt.Color(255, 255, 255));
        button_save.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_save.setText("OK");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        label_title.setBackground(new java.awt.Color(255, 255, 255));
        label_title.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_title.setForeground(new java.awt.Color(0, 0, 255));
        label_title.setText("Edit Ijin Keluar Karyawan");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setText("Jam");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel9.setText("Menit");

        CheckBox_pulang.setBackground(new java.awt.Color(255, 255, 255));
        CheckBox_pulang.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        CheckBox_pulang.setText("Tidak Kembali / Pulang");
        CheckBox_pulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_pulangActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Nama Pegawai :");

        label_nama_pegawai.setBackground(new java.awt.Color(255, 255, 255));
        label_nama_pegawai.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label_nama_pegawai.setText("-");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("ID Pegawai :");

        label_id_pegawai.setBackground(new java.awt.Color(255, 255, 255));
        label_id_pegawai.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label_id_pegawai.setText("-");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setText("Jam Keluar :");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel12.setText("Menit");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel13.setText("Jam");

        Spinner_menit_keluar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Spinner_menit_keluar.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        Spinner_menit_keluar.setEditor(new javax.swing.JSpinner.NumberEditor(Spinner_menit_keluar, ""));

        Spinner_jam_keluar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Spinner_jam_keluar.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        Spinner_jam_keluar.setEditor(new javax.swing.JSpinner.NumberEditor(Spinner_jam_keluar, ""));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nama_pegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_id_pegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date_Ijin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(label_kode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckBox_pulang)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Spinner_jam_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Spinner_menit_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Spinner_jam_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Spinner_menit_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_keterangan)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_save)
                .addGap(10, 10, 10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(label_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_id_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_Ijin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner_jam_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner_menit_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner_jam_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner_menit_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckBox_pulang, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_save, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        // TODO add your handling code here:
        try {
            boolean check = true;
            String Query = null;
            String komputer = "";
            try {
                komputer = InetAddress.getLocalHost().getHostName();
            } catch (UnknownHostException e) {
            }
            String edited = " Edited " + new SimpleDateFormat("dd-MMM-yyyy hh:mm").format(today) + " by : " + MainForm.Login_NamaPegawai + "-" + komputer;
            String jam_keluar = "'" + Spinner_jam_keluar.getValue() + ":" + Spinner_menit_keluar.getValue() + ":00'";
            String jam_kembali = "'" + Spinner_jam_kembali.getValue() + ":" + Spinner_menit_kembali.getValue() + ":00'";
            if (CheckBox_pulang.isSelected()) {
                jam_kembali = "NULL";
            }

            if ((Integer.parseInt(Spinner_jam_kembali.getValue().toString()) < Integer.parseInt(Spinner_jam_keluar.getValue().toString())) && !"NULL".equals(jam_kembali)) {
                check = false;
                JOptionPane.showMessageDialog(this, "Jam kembali tidak bisa lebih awal dari jam keluar !");
            }
            
            if (check) {
                Query = "UPDATE `tb_ijin_keluar` SET "
                        + "`tanggal_keluar`='" + dateFormat.format(Date_Ijin.getDate()) + "',"
                        + "`jam_keluar`=" + jam_keluar + ","
                        + "`jam_kembali`=" + jam_kembali + ","
                        + "`keterangan`='" + txt_keterangan.getText() + edited + "'"
                        + "WHERE `kode_keluar`='" + label_kode.getText() + "'";
                Utility.db.getConnection().createStatement();
                if ((Utility.db.getStatement().executeUpdate(Query)) == 1) {
                    JOptionPane.showMessageDialog(this, "Data Edited!");
                    this.dispose();
                }
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_saveActionPerformed

    private void CheckBox_pulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_pulangActionPerformed
        // TODO add your handling code here:
        if (CheckBox_pulang.isSelected()) {
            Spinner_jam_kembali.setEnabled(false);
            Spinner_menit_kembali.setEnabled(false);
        } else {
            Spinner_jam_kembali.setEnabled(true);
            Spinner_menit_kembali.setEnabled(true);
        }
    }//GEN-LAST:event_CheckBox_pulangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox_pulang;
    private com.toedter.calendar.JDateChooser Date_Ijin;
    private javax.swing.JSpinner Spinner_jam_keluar;
    private javax.swing.JSpinner Spinner_jam_kembali;
    private javax.swing.JSpinner Spinner_menit_keluar;
    private javax.swing.JSpinner Spinner_menit_kembali;
    private javax.swing.JButton button_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_id_pegawai;
    private javax.swing.JLabel label_kode;
    private javax.swing.JLabel label_nama_pegawai;
    public static javax.swing.JLabel label_title;
    private javax.swing.JTextField txt_keterangan;
    // End of variables declaration//GEN-END:variables
}
