package waleta_system.HRD;

import waleta_system.Class.Utility;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import waleta_system.Browse_Karyawan;
import waleta_system.Class.Utility;

public class JDialog_Add_GrupCabut extends javax.swing.JDialog {

    String sql = null;
    ResultSet rs;

    public JDialog_Add_GrupCabut(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    public void init() {
        //give icon for button
        button_tambah.setIcon(Utility.ResizeImageIcon(new javax.swing.ImageIcon(getClass().getResource("/waleta_system/Images/add_green.png")), button_tambah.getWidth(), button_tambah.getHeight()));
        button_kurang.setIcon(Utility.ResizeImageIcon(new javax.swing.ImageIcon(getClass().getResource("/waleta_system/Images/delete-icon.png")), button_kurang.getWidth(), button_kurang.getHeight()));
    }

    public String findGrup(String id) {
        String kode_grup = null;
        try {
            sql = "SELECT `kode_grup` FROM `tb_grup_cabut` WHERE `id_pegawai` = '" + id + "'";
            rs = Utility.db.getStatement().executeQuery(sql);
            if (rs.next()) {
                kode_grup = rs.getString("kode_grup");
            }
        } catch (SQLException ex) {
            Logger.getLogger(JDialog_Add_GrupCabut.class.getName()).log(Level.SEVERE, null, ex);
        }
        return kode_grup;
    }

    public boolean isGroupDuplicate(String kode_grup) {
        boolean result = false;
        try {
            sql = "SELECT * FROM `tb_grup_cabut` WHERE `kode_grup` = '" + kode_grup + "'";
            rs = Utility.db.getStatement().executeQuery(sql);
            result = rs.next();
        } catch (SQLException ex) {
            Logger.getLogger(JDialog_Add_GrupCabut.class.getName()).log(Level.SEVERE, null, ex);
        }
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nama_grup = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ComboBox_ruang = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pegawai_grup = new javax.swing.JTable();
        button_kurang = new javax.swing.JButton();
        button_tambah = new javax.swing.JButton();
        button_add = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        label_warning = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah Grup");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel1.setText("Tambah Grup Cabut & Cetak");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Nama Grup :");

        txt_nama_grup.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_nama_grup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nama_grupFocusLost(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("Ruang :");

        ComboBox_ruang.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        ComboBox_ruang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "-" }));

        table_pegawai_grup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pegawai", "Nama Pegawai", "Bagian", "Desa", "Nomor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_pegawai_grup.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_pegawai_grup);

        button_kurang.setBackground(new java.awt.Color(255, 255, 255));
        button_kurang.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_kurangActionPerformed(evt);
            }
        });

        button_tambah.setBackground(new java.awt.Color(255, 255, 255));
        button_tambah.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tambahActionPerformed(evt);
            }
        });

        button_add.setBackground(new java.awt.Color(255, 255, 255));
        button_add.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_add.setText("Add");
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        button_cancel.setBackground(new java.awt.Color(255, 255, 255));
        button_cancel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_cancel.setText("Cancel");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        label_warning.setBackground(new java.awt.Color(255, 255, 255));
        label_warning.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        label_warning.setForeground(new java.awt.Color(255, 0, 0));
        label_warning.setText("*Harus Diisi");
        label_warning.setVisible(false);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("Total :");

        label_total.setBackground(new java.awt.Color(255, 255, 255));
        label_total.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_total.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBox_ruang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nama_grup, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_warning))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_add)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nama_grup, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_warning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_ruang, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(button_add)
                                .addComponent(button_cancel))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(label_total))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_button_cancelActionPerformed

    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        try {
            Utility.db.getConnection().setAutoCommit(false);
            String id, nama_grup, ruangan, kode_urut;
            nama_grup = txt_nama_grup.getText();
            ruangan = ComboBox_ruang.getSelectedItem().toString();
            int x = table_pegawai_grup.getRowCount();

            boolean check = true;
            for (int i = 0; i < x; i++) {
                if (table_pegawai_grup.getValueAt(i, 4) == null) {
                    check = false;
                    break;
                }
            }

            if (isGroupDuplicate(nama_grup)) {
                JOptionPane.showMessageDialog(this, "Nama Grup " + nama_grup + " sudah ada !");
            } else if (check) {
                sql = "INSERT INTO `tb_grup`(`kode_grup`, `ruangan`, `status`) VALUES ('" + nama_grup + "','" + ruangan + "','PROSES')";
                if ((Utility.db.getStatement().executeUpdate(sql)) < 1) {
                    throw new Exception("Error");
                }
                for (int i = 0; i < x; i++) {
                    id = table_pegawai_grup.getValueAt(i, 0).toString();
                    kode_urut = table_pegawai_grup.getValueAt(i, 4).toString();
                    sql = "INSERT INTO `tb_grup_cabut`(`id_pegawai`, `kode_grup`, `kode_urut`) VALUES ('" + id + "','" + nama_grup + "','" + kode_urut + "')";
                    if ((Utility.db.getStatement().executeUpdate(sql)) < 1) {
                        throw new Exception("Error");
                    }
                }
                JOptionPane.showMessageDialog(this, "Grup Baru berhasil dibuat");
                this.dispose();
                Utility.db.getConnection().commit();
            } else {
                JOptionPane.showMessageDialog(this, "Silahkan lengkapi kode urut setiap karyawan !");
            }
        } catch (Exception ex) {
            try {
                Utility.db.getConnection().rollback();
            } catch (SQLException e) {
                Logger.getLogger(JDialog_Add_GrupCabut.class.getName()).log(Level.SEVERE, null, e);
            }
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(JDialog_Add_GrupCabut.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                Utility.db.getConnection().setAutoCommit(true);
            } catch (SQLException ex) {
                Logger.getLogger(JDialog_Add_SuratPerintahLembur.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_button_addActionPerformed

    private void button_kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_kurangActionPerformed
        // TODO add your handling code here:
        int i = table_pegawai_grup.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) table_pegawai_grup.getModel();
        if (i != -1) {
            model.removeRow(i);
        }

        label_total.setText(Integer.toString(table_pegawai_grup.getRowCount()));
    }//GEN-LAST:event_button_kurangActionPerformed

    private void button_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tambahActionPerformed
        // TODO add your handling code here:
        boolean add = true;
        String id = null, nama = null, bagian = null, desa = null;
        String filter = " AND `tb_grup_cabut`.`id_pegawai` IS NULL ";
//        String filter = "AND DATE(`att_log`.`scan_date`) = CURRENT_DATE()";
        Browse_Karyawan dialog = new Browse_Karyawan(new javax.swing.JFrame(), true, filter);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);

        int x = Browse_Karyawan.table_list_karyawan.getSelectedRow();
        if (x != -1) {
            id = Browse_Karyawan.table_list_karyawan.getValueAt(x, 0).toString();
            nama = Browse_Karyawan.table_list_karyawan.getValueAt(x, 1).toString();
            bagian = Browse_Karyawan.table_list_karyawan.getValueAt(x, 2).toString();

            for (int i = 0; i < table_pegawai_grup.getRowCount(); i++) {
                if (table_pegawai_grup.getValueAt(i, 0).toString().equals(id)) {
                    JOptionPane.showMessageDialog(this, nama + " sudah tergabung dalam grup ini!!");
                    add = false;
                }
            }
            if (findGrup(id) != null) {
                JOptionPane.showMessageDialog(this, nama + " sudah tergabung dalam grup " + findGrup(id));
                add = false;
            }

            if (add) {
                DefaultTableModel model = (DefaultTableModel) table_pegawai_grup.getModel();
                model.addRow(new Object[]{id, nama, bagian, desa});
                label_total.setText(Integer.toString(table_pegawai_grup.getRowCount()));
            }
        }
    }//GEN-LAST:event_button_tambahActionPerformed

    private void txt_nama_grupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nama_grupFocusLost
        // TODO add your handling code here:
        String nama_grup = txt_nama_grup.getText();
        if (txt_nama_grup.getText() == null || "".equals(txt_nama_grup.getText())) {
            label_warning.setText("Nama Grup Harus diisi !!");
            label_warning.setVisible(true);
            button_add.setEnabled(false);
        } else if (isGroupDuplicate(nama_grup)) {
            label_warning.setText("Maaf Nama grup sudah ada !!");
            label_warning.setVisible(true);
        } else {
            label_warning.setVisible(false);
            button_add.setEnabled(true);
        }
    }//GEN-LAST:event_txt_nama_grupFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialog_Add_GrupCabut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialog_Add_GrupCabut dialog = new JDialog_Add_GrupCabut(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_ruang;
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_kurang;
    private javax.swing.JButton button_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_total;
    private javax.swing.JLabel label_warning;
    private javax.swing.JTable table_pegawai_grup;
    private javax.swing.JTextField txt_nama_grup;
    // End of variables declaration//GEN-END:variables
}
