package waleta_system.Cabuto;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import waleta_system.Class.ColumnsAutoSizer;
import waleta_system.Class.ExportToExcel;
import waleta_system.Class.Utility;

public class JPanel_Laporan_Produksi_Cabuto extends javax.swing.JPanel {

    String sql = null;
    String sql2 = null;
    ResultSet rs;
    Date date = new Date();
    DecimalFormat decimalFormat = new DecimalFormat();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    DefaultTableCellRenderer TableAlignment = new DefaultTableCellRenderer();
    float kadar_air_bahan_baku = 0;

    public JPanel_Laporan_Produksi_Cabuto() {
        initComponents();
    }

    public void init() {
        refresh_tabel_cabuto_online();
    }

    public void refresh_tabel_cabuto_online() {
        try {
            Utility.db_cabuto.connect();
            int total_keping = 0, total_gram = 0;
            DefaultTableModel model = (DefaultTableModel) Table_laporan_produksi_cabuto.getModel();
            model.setRowCount(0);
            String filter_tanggal_lp = "";
            if (Date_Search_LP_1.getDate() != null && Date_Search_LP_2.getDate() != null) {
                filter_tanggal_lp = "AND `tanggal_lp` BETWEEN '" + dateFormat.format(Date_Search_LP_1.getDate()) + "' AND '" + dateFormat.format(Date_Search_LP_2.getDate()) + "' ";
            }
            String status = "";
            if (ComboBox_status.getSelectedIndex() == 1) {//Stok
                status = " AND `id_order` IS NULL \n";
            } else if (ComboBox_status.getSelectedIndex() == 2) {//Sudah diproses
                status = " AND `id_order` IS NOT NULL \n";
            }
            String query = "SELECT `id_order`, `no_laporan_produksi`, `no_kartu_waleta`, `tanggal_lp`, `ruangan`, `kode_grade`, `jenis_bulu_lp`, `memo_lp`, `berat_basah`, `berat_kering`, `jumlah_keping`, `keping_upah`, "
                    + "`harga_baku` "
                    + "FROM `tb_lp` "
                    + "WHERE "
                    + "`no_laporan_produksi` LIKE '%" + txt_search_lp.getText() + "%' \n"
                    + "AND `kode_grade` LIKE '%" + txt_search_grade.getText() + "%' \n"
                    + filter_tanggal_lp
                    + status
                    + "ORDER BY `no_laporan_produksi` DESC";
            ResultSet result = Utility.db_cabuto.getStatement().executeQuery(query);
            Object[] row = new Object[15];
            while (result.next()) {
                row[0] = result.getString("no_laporan_produksi");
                row[1] = result.getDate("tanggal_lp");
                row[2] = result.getString("kode_grade");
                row[3] = result.getString("jenis_bulu_lp");
                row[4] = result.getString("memo_lp");
                row[5] = result.getInt("jumlah_keping");
                row[6] = result.getInt("keping_upah");
                row[7] = result.getInt("berat_basah");
                row[8] = result.getInt("berat_kering");
                row[9] = result.getInt("harga_baku");
                row[10] = result.getString("id_order");
                model.addRow(row);
                total_keping = total_keping + result.getInt("jumlah_keping");
                total_gram = total_gram + result.getInt("berat_basah");
            }
            ColumnsAutoSizer.sizeColumnsToFit(Table_laporan_produksi_cabuto);
            label_total_data_laporan_produksi.setText(Integer.toString(Table_laporan_produksi_cabuto.getRowCount()));
            label_total_keping_LP.setText(decimalFormat.format(total_keping));
            label_total_gram_LP.setText(decimalFormat.format(total_gram));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            Logger.getLogger(JPanel_Laporan_Produksi_Cabuto.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_laporan_produksi = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        label_total_data_laporan_produksi = new javax.swing.JLabel();
        label_total_gram_LP = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        label_total_keping_LP = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        button_export = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        Table_laporan_produksi_cabuto = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_search_grade = new javax.swing.JTextField();
        txt_search_lp = new javax.swing.JTextField();
        Date_Search_LP_1 = new com.toedter.calendar.JDateChooser();
        Date_Search_LP_2 = new com.toedter.calendar.JDateChooser();
        jLabel35 = new javax.swing.JLabel();
        button_cari = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        ComboBox_status = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();

        jPanel_laporan_produksi.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_laporan_produksi.setPreferredSize(new java.awt.Dimension(1366, 700));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Total Data :");

        label_total_data_laporan_produksi.setBackground(new java.awt.Color(255, 255, 255));
        label_total_data_laporan_produksi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label_total_data_laporan_produksi.setText("TOTAL");

        label_total_gram_LP.setBackground(new java.awt.Color(255, 255, 255));
        label_total_gram_LP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label_total_gram_LP.setText("TOTAL");

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("Total Berat :");

        label_total_keping_LP.setBackground(new java.awt.Color(255, 255, 255));
        label_total_keping_LP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label_total_keping_LP.setText("TOTAL");

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Total Keping :");

        button_export.setBackground(new java.awt.Color(255, 255, 255));
        button_export.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        button_export.setText("Export Excel");
        button_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exportActionPerformed(evt);
            }
        });

        Table_laporan_produksi_cabuto.setAutoCreateRowSorter(true);
        Table_laporan_produksi_cabuto.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Table_laporan_produksi_cabuto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No LP", "Tanggal LP", "Kode Grade", "Bulu Upah", "Memo", "Keping", "Kpg Upah", "Berat Angin2", "Berat Kering", "Harga Baku", "ID Order"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_laporan_produksi_cabuto.getTableHeader().setReorderingAllowed(false);
        jScrollPane9.setViewportView(Table_laporan_produksi_cabuto);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("No LP :");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Grade :");

        txt_search_grade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_search_grade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_search_gradeKeyPressed(evt);
            }
        });

        txt_search_lp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_search_lp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_search_lpKeyPressed(evt);
            }
        });

        Date_Search_LP_1.setBackground(new java.awt.Color(255, 255, 255));
        Date_Search_LP_1.setToolTipText("");
        Date_Search_LP_1.setDate(new Date(new Date().getTime()-(7 * 24 * 60 * 60 * 1000)));
        Date_Search_LP_1.setDateFormatString("dd MMM yyyy");
        Date_Search_LP_1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Date_Search_LP_1.setMinSelectableDate(new java.util.Date(1420048915000L));

        Date_Search_LP_2.setBackground(new java.awt.Color(255, 255, 255));
        Date_Search_LP_2.setDate(new Date());
        Date_Search_LP_2.setDateFormatString("dd MMM yyyy");
        Date_Search_LP_2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel35.setText("Tgl LP :");

        button_cari.setBackground(new java.awt.Color(255, 255, 255));
        button_cari.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        button_cari.setText("Cari");
        button_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cariActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("LAPORAN PRODUKSI CABUTO");

        ComboBox_status.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ComboBox_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Stok", "Sudah Diproses" }));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel36.setText("Status :");

        javax.swing.GroupLayout jPanel_laporan_produksiLayout = new javax.swing.GroupLayout(jPanel_laporan_produksi);
        jPanel_laporan_produksi.setLayout(jPanel_laporan_produksiLayout);
        jPanel_laporan_produksiLayout.setHorizontalGroup(
            jPanel_laporan_produksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_laporan_produksiLayout.createSequentialGroup()
                .addGroup(jPanel_laporan_produksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_laporan_produksiLayout.createSequentialGroup()
                        .addGroup(jPanel_laporan_produksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_laporan_produksiLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_total_data_laporan_produksi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_total_keping_LP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_total_gram_LP))
                            .addGroup(jPanel_laporan_produksiLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel18)))
                        .addGap(0, 998, Short.MAX_VALUE))
                    .addGroup(jPanel_laporan_produksiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane9)))
                .addContainerGap())
            .addGroup(jPanel_laporan_produksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_search_lp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_search_grade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Date_Search_LP_1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Date_Search_LP_2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBox_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_cari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_export)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_laporan_produksiLayout.setVerticalGroup(
            jPanel_laporan_produksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_laporan_produksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_laporan_produksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_status, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_export, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_Search_LP_2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_Search_LP_1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search_lp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search_grade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_laporan_produksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel26)
                    .addComponent(label_total_keping_LP)
                    .addComponent(jLabel27)
                    .addComponent(jLabel15)
                    .addComponent(label_total_data_laporan_produksi)
                    .addComponent(label_total_gram_LP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel_laporan_produksi, javax.swing.GroupLayout.DEFAULT_SIZE, 1364, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_laporan_produksi, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cariActionPerformed
        // TODO add your handling code here:
        refresh_tabel_cabuto_online();
    }//GEN-LAST:event_button_cariActionPerformed

    private void txt_search_lpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_lpKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            refresh_tabel_cabuto_online();
        }
    }//GEN-LAST:event_txt_search_lpKeyPressed

    private void button_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exportActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Table_laporan_produksi_cabuto.getModel();
        ExportToExcel.writeToExcel(model, this);
    }//GEN-LAST:event_button_exportActionPerformed

    private void txt_search_gradeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_gradeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            refresh_tabel_cabuto_online();
        }
    }//GEN-LAST:event_txt_search_gradeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_status;
    private com.toedter.calendar.JDateChooser Date_Search_LP_1;
    private com.toedter.calendar.JDateChooser Date_Search_LP_2;
    public static javax.swing.JTable Table_laporan_produksi_cabuto;
    private javax.swing.JButton button_cari;
    private javax.swing.JButton button_export;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel_laporan_produksi;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel label_total_data_laporan_produksi;
    private javax.swing.JLabel label_total_gram_LP;
    private javax.swing.JLabel label_total_keping_LP;
    private javax.swing.JTextField txt_search_grade;
    private javax.swing.JTextField txt_search_lp;
    // End of variables declaration//GEN-END:variables
}
