package waleta_system.Cabuto;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import waleta_system.Class.ColumnsAutoSizer;
import waleta_system.Class.ExportToExcel;
import waleta_system.Class.Utility;

public class JPanel_GradeBarangJadi_Cabuto extends javax.swing.JPanel {

    String sql = null;
    String sql2 = null;
    ResultSet rs;
    Date date = new Date();
    DecimalFormat decimalFormat = new DecimalFormat();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    DefaultTableCellRenderer TableAlignment = new DefaultTableCellRenderer();
    float kadar_air_bahan_baku = 0;

    public JPanel_GradeBarangJadi_Cabuto() {
        initComponents();
        Table_grade_barang_jadi_cabuto.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting() && Table_grade_barang_jadi_cabuto.getSelectedRow() != -1) {
                    int i = Table_grade_barang_jadi_cabuto.getSelectedRow();
                    Utility.db_cabuto.connect();
                    txt_grade_barang_jadi.setText(Table_grade_barang_jadi_cabuto.getValueAt(i, 0).toString());
                    txt_harga_evaluasi.setText(Table_grade_barang_jadi_cabuto.getValueAt(i, 1).toString());
                    txt_harga_jual.setText(Table_grade_barang_jadi_cabuto.getValueAt(i, 2).toString());
                }
            }
        });
    }

    public void init() {
        refresh_tabel_grade_bj_cabuto();
    }

    private void refresh_tabel_grade_bj_cabuto() {
        try {
            Utility.db_cabuto.connect();
            DefaultTableModel model = (DefaultTableModel) Table_grade_barang_jadi_cabuto.getModel();
            model.setRowCount(0);
            String query = "SELECT `grade`, `harga`, `harga_jual` "
                    + "FROM `tb_pricelist` "
                    + "WHERE `grade` LIKE '%" + txt_search_grade.getText() + "%' \n";
            ResultSet result = Utility.db_cabuto.getStatement().executeQuery(query);
            Object[] row = new Object[15];
            while (result.next()) {
                row[0] = result.getString("grade");
                row[1] = result.getInt("harga");
                row[2] = result.getInt("harga_jual");
                model.addRow(row);
            }
            ColumnsAutoSizer.sizeColumnsToFit(Table_grade_barang_jadi_cabuto);
            label_total_data.setText(Integer.toString(Table_grade_barang_jadi_cabuto.getRowCount()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            Logger.getLogger(JPanel_GradeBarangJadi_Cabuto.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_laporan_produksi = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        label_total_data = new javax.swing.JLabel();
        button_export = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        Table_grade_barang_jadi_cabuto = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txt_search_grade = new javax.swing.JTextField();
        button_cari = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label_nama_customer_baku1 = new javax.swing.JLabel();
        label_alamat_customer_baku = new javax.swing.JLabel();
        label_nama_customer_baku = new javax.swing.JLabel();
        txt_harga_jual = new javax.swing.JTextField();
        button_delete_customer_baku = new javax.swing.JButton();
        button_update_customer_baku = new javax.swing.JButton();
        button_insert_customer_baku = new javax.swing.JButton();
        txt_harga_evaluasi = new javax.swing.JTextField();
        txt_grade_barang_jadi = new javax.swing.JTextField();

        jPanel_laporan_produksi.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_laporan_produksi.setPreferredSize(new java.awt.Dimension(1366, 700));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Total Data :");

        label_total_data.setBackground(new java.awt.Color(255, 255, 255));
        label_total_data.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label_total_data.setText("TOTAL");

        button_export.setBackground(new java.awt.Color(255, 255, 255));
        button_export.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        button_export.setText("Export Excel");
        button_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exportActionPerformed(evt);
            }
        });

        Table_grade_barang_jadi_cabuto.setAutoCreateRowSorter(true);
        Table_grade_barang_jadi_cabuto.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Table_grade_barang_jadi_cabuto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grade", "Harga Evaluasi / Gram (Rp)", "Harga Jual Ekspor / Kg (CNY)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_grade_barang_jadi_cabuto.getTableHeader().setReorderingAllowed(false);
        jScrollPane9.setViewportView(Table_grade_barang_jadi_cabuto);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Grade :");

        txt_search_grade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_search_grade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_search_gradeKeyPressed(evt);
            }
        });

        button_cari.setBackground(new java.awt.Color(255, 255, 255));
        button_cari.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        button_cari.setText("Cari");
        button_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cariActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("GRADE BARANG JADI CABUTO");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        label_nama_customer_baku1.setBackground(new java.awt.Color(255, 255, 255));
        label_nama_customer_baku1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_nama_customer_baku1.setText("Harga Evaluasi / Gram (Rp.) :");

        label_alamat_customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        label_alamat_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_alamat_customer_baku.setText("Harga Jual / Kg (CNY) :");

        label_nama_customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        label_nama_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_nama_customer_baku.setText("Grade :");

        txt_harga_jual.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_harga_jual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_harga_jualKeyTyped(evt);
            }
        });

        button_delete_customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        button_delete_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_delete_customer_baku.setText("Hapus");
        button_delete_customer_baku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_delete_customer_bakuActionPerformed(evt);
            }
        });

        button_update_customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        button_update_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_update_customer_baku.setText("Edit");
        button_update_customer_baku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_update_customer_bakuActionPerformed(evt);
            }
        });

        button_insert_customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        button_insert_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_insert_customer_baku.setText("Baru");
        button_insert_customer_baku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_insert_customer_bakuActionPerformed(evt);
            }
        });

        txt_harga_evaluasi.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_harga_evaluasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_harga_evaluasiKeyTyped(evt);
            }
        });

        txt_grade_barang_jadi.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_alamat_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_nama_customer_baku1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_nama_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_harga_jual)
                            .addComponent(txt_harga_evaluasi)
                            .addComponent(txt_grade_barang_jadi)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(button_insert_customer_baku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_update_customer_baku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_delete_customer_baku)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_grade_barang_jadi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama_customer_baku1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_harga_evaluasi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_alamat_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_harga_jual, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_update_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_insert_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_delete_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_laporan_produksiLayout = new javax.swing.GroupLayout(jPanel_laporan_produksi);
        jPanel_laporan_produksi.setLayout(jPanel_laporan_produksiLayout);
        jPanel_laporan_produksiLayout.setHorizontalGroup(
            jPanel_laporan_produksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_laporan_produksiLayout.createSequentialGroup()
                .addGroup(jPanel_laporan_produksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_laporan_produksiLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_total_data))
                    .addGroup(jPanel_laporan_produksiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18))
                    .addGroup(jPanel_laporan_produksiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_laporan_produksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_laporan_produksiLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_search_grade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_cari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_export))
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)))
                    .addGroup(jPanel_laporan_produksiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(854, Short.MAX_VALUE))
        );
        jPanel_laporan_produksiLayout.setVerticalGroup(
            jPanel_laporan_produksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_laporan_produksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_laporan_produksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(button_export, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search_grade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_laporan_produksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel15)
                    .addComponent(label_total_data))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel_laporan_produksi, javax.swing.GroupLayout.DEFAULT_SIZE, 1364, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_laporan_produksi, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cariActionPerformed
        // TODO add your handling code here:
        refresh_tabel_grade_bj_cabuto();
    }//GEN-LAST:event_button_cariActionPerformed

    private void button_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exportActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Table_grade_barang_jadi_cabuto.getModel();
        ExportToExcel.writeToExcel(model, this);
    }//GEN-LAST:event_button_exportActionPerformed

    private void txt_search_gradeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_gradeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            refresh_tabel_grade_bj_cabuto();
        }
    }//GEN-LAST:event_txt_search_gradeKeyPressed

    private void button_delete_customer_bakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_delete_customer_bakuActionPerformed
        // TODO add your handling code here:
        try {
            int j = Table_grade_barang_jadi_cabuto.getSelectedRow();
            if (j == -1) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data yang ingin di hapus !");
            } else {
                int dialogResult = JOptionPane.showConfirmDialog(this, "Yakin hapus data ini?", "Warning", 0);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    // delete code here
                    String Query = "DELETE FROM `tb_pricelist` WHERE `grade` = '" + Table_grade_barang_jadi_cabuto.getValueAt(j, 0).toString() + "'";
                    Utility.db_cabuto.getConnection().createStatement();
                    if ((Utility.db_cabuto.getStatement().executeUpdate(Query)) == 1) {
                        JOptionPane.showMessageDialog(this, "Hapus data berhasil!");
                        refresh_tabel_grade_bj_cabuto();
                        txt_grade_barang_jadi.setText(null);
                        txt_harga_evaluasi.setText(null);
                        txt_harga_jual.setText(null);
                    } else {
                        JOptionPane.showMessageDialog(this, "Hapus data gagal!");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            Logger.getLogger(JPanel_GradeBarangJadi_Cabuto.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_delete_customer_bakuActionPerformed

    private void button_update_customer_bakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_update_customer_bakuActionPerformed
        // TODO add your handling code here:
        int j = Table_grade_barang_jadi_cabuto.getSelectedRow();
        try {
            if (j == -1) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih salah satu data pada tabel !");
            } else {
                String Query = "UPDATE `tb_pricelist` SET "
                        + "`grade` = '" + txt_grade_barang_jadi.getText() + "', "
                        + "`harga` = '" + txt_harga_evaluasi.getText() + "', "
                        + "`harga_jual` = '" + txt_harga_jual.getText() + "' "
                        + "WHERE `grade` = '" + Table_grade_barang_jadi_cabuto.getValueAt(j, 0).toString() + "'";
                Utility.db_cabuto.getStatement().executeUpdate(Query);
                JOptionPane.showMessageDialog(this, "Data Saved!!");
                refresh_tabel_grade_bj_cabuto();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            Logger.getLogger(JPanel_GradeBarangJadi_Cabuto.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_update_customer_bakuActionPerformed

    private void button_insert_customer_bakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_insert_customer_bakuActionPerformed
        // TODO add your handling code here:
        try {
            String Query = "INSERT INTO `tb_pricelist`(`grade`, `harga`, `harga_jual`) "
                    + "VALUES ('" + txt_grade_barang_jadi.getText() + "', '" + txt_harga_evaluasi.getText() + "', '" + txt_harga_jual.getText() + "')";
            if ((Utility.db_cabuto.getStatement().executeUpdate(Query)) == 1) {
                JOptionPane.showMessageDialog(this, "Data Saved!!");
                refresh_tabel_grade_bj_cabuto();
                txt_grade_barang_jadi.setText(null);
                txt_harga_evaluasi.setText(null);
                txt_harga_jual.setText(null);
            } else {
                JOptionPane.showMessageDialog(this, "Input gagal!!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            Logger.getLogger(JPanel_GradeBarangJadi_Cabuto.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_insert_customer_bakuActionPerformed

    private void txt_harga_evaluasiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_harga_evaluasiKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())
                && evt.getKeyCode() != KeyEvent.VK_ENTER
                && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE
                && evt.getKeyCode() != KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_harga_evaluasiKeyTyped

    private void txt_harga_jualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_harga_jualKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())
                && evt.getKeyCode() != KeyEvent.VK_ENTER
                && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE
                && evt.getKeyCode() != KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_harga_jualKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Table_grade_barang_jadi_cabuto;
    private javax.swing.JButton button_cari;
    public javax.swing.JButton button_delete_customer_baku;
    private javax.swing.JButton button_export;
    public javax.swing.JButton button_insert_customer_baku;
    public javax.swing.JButton button_update_customer_baku;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_laporan_produksi;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel label_alamat_customer_baku;
    private javax.swing.JLabel label_nama_customer_baku;
    private javax.swing.JLabel label_nama_customer_baku1;
    private javax.swing.JLabel label_total_data;
    private javax.swing.JTextField txt_grade_barang_jadi;
    private javax.swing.JTextField txt_harga_evaluasi;
    private javax.swing.JTextField txt_harga_jual;
    private javax.swing.JTextField txt_search_grade;
    // End of variables declaration//GEN-END:variables
}
