package waleta_system.QC;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import waleta_system.Class.ColumnsAutoSizer;
import waleta_system.Class.Utility;
import waleta_system.Class.ExportToExcel;
import waleta_system.MainForm;

public class JPanel_Lab_BahanBaku extends javax.swing.JPanel {

    Date date = new Date();
    DecimalFormat decimalFormat = new DecimalFormat();
    String sql = null;
    ResultSet rs;
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    DefaultTableCellRenderer TableAlignment = new DefaultTableCellRenderer();

    public JPanel_Lab_BahanBaku() {
        initComponents();
    }

    public void init() {
        refreshTable();
        Table_Data_Lab_BahanBaku.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting() && Table_Data_Lab_BahanBaku.getSelectedRow() != -1) {
                    try {
                        int i = Table_Data_Lab_BahanBaku.getSelectedRow();
                        txt_no_kartu_waleta.setText(Table_Data_Lab_BahanBaku.getValueAt(i, 0).toString());

                        String date_kh = Table_Data_Lab_BahanBaku.getValueAt(i, 1).toString();
                        Date_uji_bahanBaku.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(date_kh));

                        txt_nitrit_w1.setText(Table_Data_Lab_BahanBaku.getValueAt(i, 2).toString());
                        txt_nitrit_w2.setText(Table_Data_Lab_BahanBaku.getValueAt(i, 3).toString());
                        txt_nitrit_w3.setText(Table_Data_Lab_BahanBaku.getValueAt(i, 4).toString());
                        txt_kadar_air.setText(Table_Data_Lab_BahanBaku.getValueAt(i, 5).toString());
                        txt_kadar_aluminium.setText(Table_Data_Lab_BahanBaku.getValueAt(i, 6).toString());
                        txt_kadar_PH.setText(Table_Data_Lab_BahanBaku.getValueAt(i, 7).toString());
                    } catch (ParseException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
    }

    public void refreshTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) Table_Data_Lab_BahanBaku.getModel();
            model.setRowCount(0);
            String filter_tanggal = "";
            if (Date_1.getDate() != null && Date_2.getDate() != null) {
                filter_tanggal = "AND `tgl_uji_lab_bahan` BETWEEN '" + dateFormat.format(Date_1.getDate()) + "' AND '" + dateFormat.format(Date_2.getDate()) + "'";
            }
            sql = "SELECT `no_kartu_waleta`, `tgl_uji_lab_bahan`, `nitrit_bm`, `nitrit_bm_w2`, `nitrit_bm_w3`, `kadar_air_bm`, `kadar_aluminium_baku`, `kadar_ph_baku` "
                    + "FROM `tb_lab_bahan_baku` "
                    + "WHERE "
                    + "`no_kartu_waleta` LIKE '%" + txt_search_Lab_BahanBaku.getText() + "%' "
                    + filter_tanggal;
            rs = Utility.db.getStatement().executeQuery(sql);
            Object[] row = new Object[8];
            while (rs.next()) {
                row[0] = rs.getString("no_kartu_waleta");
                row[1] = rs.getDate("tgl_uji_lab_bahan");
                row[2] = rs.getFloat("nitrit_bm");
                row[3] = rs.getFloat("nitrit_bm_w2");
                row[4] = rs.getFloat("nitrit_bm_w3");
                row[5] = rs.getFloat("kadar_air_bm");
                row[6] = rs.getFloat("kadar_aluminium_baku");
                row[7] = rs.getFloat("kadar_ph_baku");
                model.addRow(row);
            }
            ColumnsAutoSizer.sizeColumnsToFit(Table_Data_Lab_BahanBaku);
            int rowData = Table_Data_Lab_BahanBaku.getRowCount();
            label_total_data_lab_bahan_baku.setText(Integer.toString(rowData));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(JPanel_Lab_BahanBaku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Table_Data_Lab_BahanBaku = new javax.swing.JTable();
        jPanel_operation_lab_bahanBaku = new javax.swing.JPanel();
        label_no_kartu_pengirim = new javax.swing.JLabel();
        label_tgl_kh = new javax.swing.JLabel();
        button_insert_lab_bm = new javax.swing.JButton();
        button_update_lab_bm = new javax.swing.JButton();
        button_clear_lab_bm = new javax.swing.JButton();
        button_delete_lab_bm = new javax.swing.JButton();
        txt_no_kartu_waleta = new javax.swing.JTextField();
        Date_uji_bahanBaku = new com.toedter.calendar.JDateChooser();
        label_jumlah_koli5 = new javax.swing.JLabel();
        txt_nitrit_w1 = new javax.swing.JTextField();
        label_jumlah_koli6 = new javax.swing.JLabel();
        txt_kadar_air = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        label_jumlah_koli7 = new javax.swing.JLabel();
        txt_nitrit_w2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_nitrit_w3 = new javax.swing.JTextField();
        label_jumlah_koli8 = new javax.swing.JLabel();
        label_jumlah_koli9 = new javax.swing.JLabel();
        txt_kadar_aluminium = new javax.swing.JTextField();
        label_jumlah_koli10 = new javax.swing.JLabel();
        txt_kadar_PH = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label_total_data_lab_bahan_baku = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_search_Lab_BahanBaku = new javax.swing.JTextField();
        button_search_lab_bahanBaku = new javax.swing.JButton();
        Date_1 = new com.toedter.calendar.JDateChooser();
        Date_2 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        button_export = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Pemeriksaan Lab Bahan Baku", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 700));

        Table_Data_Lab_BahanBaku.setAutoCreateRowSorter(true);
        Table_Data_Lab_BahanBaku.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        Table_Data_Lab_BahanBaku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Kartu Waleta", "Tanggal Uji", "Nitrit W1", "Nitrit W2", "Nitrit W3", "Kadar Air (%)", "Aluminium", "PH"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Data_Lab_BahanBaku.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(Table_Data_Lab_BahanBaku);

        jPanel_operation_lab_bahanBaku.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_operation_lab_bahanBaku.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Main Operation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Yu Gothic", 0, 12))); // NOI18N
        jPanel_operation_lab_bahanBaku.setName("aah"); // NOI18N

        label_no_kartu_pengirim.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_no_kartu_pengirim.setText("No. Kartu Waleta :");

        label_tgl_kh.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_tgl_kh.setText("Tanggal Uji Bahan Baku :");

        button_insert_lab_bm.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_insert_lab_bm.setText("insert");
        button_insert_lab_bm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_insert_lab_bmActionPerformed(evt);
            }
        });

        button_update_lab_bm.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_update_lab_bm.setText("Update");
        button_update_lab_bm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_update_lab_bmActionPerformed(evt);
            }
        });

        button_clear_lab_bm.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_clear_lab_bm.setText("Clear Text");
        button_clear_lab_bm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clear_lab_bmActionPerformed(evt);
            }
        });

        button_delete_lab_bm.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_delete_lab_bm.setText("Delete");
        button_delete_lab_bm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_delete_lab_bmActionPerformed(evt);
            }
        });

        txt_no_kartu_waleta.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        Date_uji_bahanBaku.setDateFormatString("dd MMMM yyyy");
        Date_uji_bahanBaku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Date_uji_bahanBaku.setMaxSelectableDate(new Date());

        label_jumlah_koli5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_jumlah_koli5.setText("Nitrit Bahan Baku w1 :");

        txt_nitrit_w1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txt_nitrit_w1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nitrit_w1KeyTyped(evt);
            }
        });

        label_jumlah_koli6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_jumlah_koli6.setText("Kadar Air Bahan Baku :");

        txt_kadar_air.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txt_kadar_air.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_kadar_airKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel12.setText("%");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel13.setText("mg/Kg");

        label_jumlah_koli7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_jumlah_koli7.setText("Nitrit Bahan Baku w2 :");

        txt_nitrit_w2.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txt_nitrit_w2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nitrit_w2KeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel15.setText("mg/Kg");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel16.setText("mg/Kg");

        txt_nitrit_w3.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txt_nitrit_w3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nitrit_w3KeyTyped(evt);
            }
        });

        label_jumlah_koli8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_jumlah_koli8.setText("Nitrit Bahan Baku w3 :");

        label_jumlah_koli9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_jumlah_koli9.setText("Kadar Aluminium :");

        txt_kadar_aluminium.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txt_kadar_aluminium.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_kadar_aluminiumKeyTyped(evt);
            }
        });

        label_jumlah_koli10.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_jumlah_koli10.setText("Kadar PH :");

        txt_kadar_PH.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txt_kadar_PH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_kadar_PHKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel17.setText("mg/Kg");

        javax.swing.GroupLayout jPanel_operation_lab_bahanBakuLayout = new javax.swing.GroupLayout(jPanel_operation_lab_bahanBaku);
        jPanel_operation_lab_bahanBaku.setLayout(jPanel_operation_lab_bahanBakuLayout);
        jPanel_operation_lab_bahanBakuLayout.setHorizontalGroup(
            jPanel_operation_lab_bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_operation_lab_bahanBakuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_operation_lab_bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_no_kartu_pengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_tgl_kh, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_jumlah_koli5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_jumlah_koli7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_jumlah_koli8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_jumlah_koli6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_jumlah_koli9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_jumlah_koli10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lab_bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_operation_lab_bahanBakuLayout.createSequentialGroup()
                        .addGroup(jPanel_operation_lab_bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_kadar_air, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nitrit_w3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nitrit_w2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nitrit_w1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kadar_aluminium, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kadar_PH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_operation_lab_bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12)
                            .addComponent(jLabel17))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Date_uji_bahanBaku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_no_kartu_waleta))
                .addContainerGap())
            .addGroup(jPanel_operation_lab_bahanBakuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(button_update_lab_bm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_insert_lab_bm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_delete_lab_bm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_clear_lab_bm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_operation_lab_bahanBakuLayout.setVerticalGroup(
            jPanel_operation_lab_bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_operation_lab_bahanBakuLayout.createSequentialGroup()
                .addGroup(jPanel_operation_lab_bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_no_kartu_waleta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_no_kartu_pengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lab_bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Date_uji_bahanBaku, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_tgl_kh, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lab_bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_jumlah_koli5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nitrit_w1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lab_bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_jumlah_koli7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nitrit_w2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lab_bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_jumlah_koli8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nitrit_w3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lab_bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_jumlah_koli6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kadar_air, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lab_bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_jumlah_koli9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kadar_aluminium, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lab_bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_jumlah_koli10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kadar_PH, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lab_bahanBakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_update_lab_bm, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_insert_lab_bm, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_delete_lab_bm, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_clear_lab_bm, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setText("Total Data :");

        label_total_data_lab_bahan_baku.setBackground(new java.awt.Color(255, 255, 255));
        label_total_data_lab_bahan_baku.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        label_total_data_lab_bahan_baku.setText("TOTAL");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel11.setText("By No Kartu Waleta :");

        txt_search_Lab_BahanBaku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_search_Lab_BahanBaku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_search_Lab_BahanBakuKeyPressed(evt);
            }
        });

        button_search_lab_bahanBaku.setBackground(new java.awt.Color(255, 255, 255));
        button_search_lab_bahanBaku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_search_lab_bahanBaku.setText("Search");
        button_search_lab_bahanBaku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_search_lab_bahanBakuActionPerformed(evt);
            }
        });

        Date_1.setBackground(new java.awt.Color(255, 255, 255));
        Date_1.setDateFormatString("dd MMMM yyyy");
        Date_1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        Date_2.setBackground(new java.awt.Color(255, 255, 255));
        Date_2.setDateFormatString("dd MMMM yyyy");
        Date_2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel14.setText("Tanggal Uji :");

        button_export.setBackground(new java.awt.Color(255, 255, 255));
        button_export.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_export.setText("Export to Excel");
        button_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_search_Lab_BahanBaku, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date_1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date_2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_search_lab_bahanBaku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_export))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_total_data_lab_bahan_baku)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_operation_lab_bahanBaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_search_Lab_BahanBaku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(Date_1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Date_2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_search_lab_bahanBaku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_export, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel_operation_lab_bahanBaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_total_data_lab_bahan_baku)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_insert_lab_bmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_insert_lab_bmActionPerformed
        // TODO add your handling code here:
        try {
            Date tgl_masuk_baku = null;
            sql = "SELECT `tgl_masuk` FROM `tb_bahan_baku_masuk` WHERE `no_kartu_waleta` = '" + txt_no_kartu_waleta.getText() + "'";
            rs = Utility.db.getStatement().executeQuery(sql);
            if (rs.next()) {
                tgl_masuk_baku = rs.getDate("tgl_masuk");
            }

            if (tgl_masuk_baku.after(Date_uji_bahanBaku.getDate())) {
                JOptionPane.showMessageDialog(this, "Maaf tanggal Uji harus setelah tanggal masuk Kartu Bahan Baku");
            } else {
                String kadar_AL = txt_kadar_aluminium.getText();
                if (txt_kadar_aluminium.getText() == null || txt_kadar_aluminium.getText().equals("")) {
                    kadar_AL = "0";
                }
                String kadar_PH = txt_kadar_PH.getText();
                if (txt_kadar_PH.getText() == null || txt_kadar_PH.getText().equals("")) {
                    kadar_PH = "0";
                }
                sql = "INSERT INTO `tb_lab_bahan_baku`(`no_kartu_waleta`, `tgl_uji_lab_bahan`, `nitrit_bm`, `nitrit_bm_w2`, `nitrit_bm_w3`, `kadar_air_bm`, `kadar_aluminium_baku`, `kadar_ph_baku`) "
                        + "VALUES ("
                        + "'" + txt_no_kartu_waleta.getText() + "',"
                        + "'" + dateFormat.format(Date_uji_bahanBaku.getDate()) + "',"
                        + "'" + txt_nitrit_w1.getText() + "',"
                        + "'" + txt_nitrit_w2.getText() + "',"
                        + "'" + txt_nitrit_w3.getText() + "',"
                        + "'" + txt_kadar_air.getText() + "',"
                        + "'" + kadar_AL + "',"
                        + "'" + kadar_PH + "'"
                        + ")";
                Utility.db.getConnection().createStatement();
                if ((Utility.db.getStatement().executeUpdate(sql)) == 1) {
                    refreshTable();
                    JOptionPane.showMessageDialog(this, "data Saved !");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed !");
                }
                button_clear_lab_bm.doClick();
            }
        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_insert_lab_bmActionPerformed

    private void button_update_lab_bmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_update_lab_bmActionPerformed
        // TODO add your handling code here:
        decimalFormat.setMaximumFractionDigits(2);
        int j = Table_Data_Lab_BahanBaku.getSelectedRow();
        try {
            if (j == -1) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih salah satu data pada tabel !");
            } else {
                sql = "UPDATE `tb_lab_bahan_baku` SET "
                        + "`tgl_uji_lab_bahan`='" + dateFormat.format(Date_uji_bahanBaku.getDate()) + "',"
                        + "`nitrit_bm`='" + txt_nitrit_w1.getText() + "',"
                        + "`nitrit_bm_w2`='" + txt_nitrit_w2.getText() + "',"
                        + "`nitrit_bm_w3`='" + txt_nitrit_w3.getText() + "',"
                        + "`kadar_air_bm`='" + txt_kadar_air.getText() + "',"
                        + "`kadar_aluminium_baku`='" + txt_kadar_aluminium.getText() + "',"
                        + "`kadar_ph_baku`='" + txt_kadar_PH.getText() + "'"
                        + "WHERE `no_kartu_waleta`='" + txt_no_kartu_waleta.getText() + "'";
                Utility.db.getConnection().createStatement();
                if ((Utility.db.getStatement().executeUpdate(sql)) == 1) {
                    refreshTable();
                    JOptionPane.showMessageDialog(this, "data Saved !");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed !");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_update_lab_bmActionPerformed

    private void button_clear_lab_bmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clear_lab_bmActionPerformed
        // TODO add your handling code here:
        txt_no_kartu_waleta.setText(null);
        Date_uji_bahanBaku.setDate(null);
        txt_nitrit_w1.setText(null);
        txt_nitrit_w2.setText(null);
        txt_nitrit_w3.setText(null);
        txt_kadar_air.setText(null);
    }//GEN-LAST:event_button_clear_lab_bmActionPerformed

    private void button_delete_lab_bmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_delete_lab_bmActionPerformed
        // TODO add your handling code here:
        try {
            int j = Table_Data_Lab_BahanBaku.getSelectedRow();
            if (j == -1) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data yang ingin di hapus !");
            } else {
                int dialogResult = JOptionPane.showConfirmDialog(this, "Yakin hapus data ini?", "Warning", 0);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    // delete code here
                    sql = "DELETE FROM `tb_lab_bahan_baku` WHERE `no_kartu_waleta` = '" + Table_Data_Lab_BahanBaku.getValueAt(j, 0) + "'";
                    Utility.db.getConnection().createStatement();
                    if ((Utility.db.getStatement().executeUpdate(sql)) == 1) {
                        refreshTable();
                        JOptionPane.showMessageDialog(this, "data Deleted !");
                    } else {
                        JOptionPane.showMessageDialog(this, "Failed !");
                    }
                }
                button_clear_lab_bm.doClick();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_delete_lab_bmActionPerformed

    private void txt_search_Lab_BahanBakuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_Lab_BahanBakuKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            refreshTable();
        }
    }//GEN-LAST:event_txt_search_Lab_BahanBakuKeyPressed

    private void button_search_lab_bahanBakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_search_lab_bahanBakuActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_button_search_lab_bahanBakuActionPerformed

    private void button_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exportActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Table_Data_Lab_BahanBaku.getModel();
        ExportToExcel.writeToExcel(model, this);
    }//GEN-LAST:event_button_exportActionPerformed

    private void txt_nitrit_w1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nitrit_w1KeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())
                && evt.getKeyChar() != '.'
                && evt.getKeyCode() != KeyEvent.VK_ENTER
                && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE
                && evt.getKeyCode() != KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nitrit_w1KeyTyped

    private void txt_nitrit_w2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nitrit_w2KeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())
                && evt.getKeyChar() != '.'
                && evt.getKeyCode() != KeyEvent.VK_ENTER
                && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE
                && evt.getKeyCode() != KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nitrit_w2KeyTyped

    private void txt_nitrit_w3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nitrit_w3KeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())
                && evt.getKeyChar() != '.'
                && evt.getKeyCode() != KeyEvent.VK_ENTER
                && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE
                && evt.getKeyCode() != KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nitrit_w3KeyTyped

    private void txt_kadar_airKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kadar_airKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())
                && evt.getKeyChar() != '.'
                && evt.getKeyCode() != KeyEvent.VK_ENTER
                && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE
                && evt.getKeyCode() != KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_kadar_airKeyTyped

    private void txt_kadar_aluminiumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kadar_aluminiumKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())
                && evt.getKeyChar() != '.'
                && evt.getKeyCode() != KeyEvent.VK_ENTER
                && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE
                && evt.getKeyCode() != KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_kadar_aluminiumKeyTyped

    private void txt_kadar_PHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kadar_PHKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())
                && evt.getKeyChar() != '.'
                && evt.getKeyCode() != KeyEvent.VK_ENTER
                && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE
                && evt.getKeyCode() != KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_kadar_PHKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_1;
    private com.toedter.calendar.JDateChooser Date_2;
    private com.toedter.calendar.JDateChooser Date_uji_bahanBaku;
    public static javax.swing.JTable Table_Data_Lab_BahanBaku;
    private javax.swing.JButton button_clear_lab_bm;
    public static javax.swing.JButton button_delete_lab_bm;
    private javax.swing.JButton button_export;
    public static javax.swing.JButton button_insert_lab_bm;
    public static javax.swing.JButton button_search_lab_bahanBaku;
    public static javax.swing.JButton button_update_lab_bm;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_operation_lab_bahanBaku;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel label_jumlah_koli10;
    private javax.swing.JLabel label_jumlah_koli5;
    private javax.swing.JLabel label_jumlah_koli6;
    private javax.swing.JLabel label_jumlah_koli7;
    private javax.swing.JLabel label_jumlah_koli8;
    private javax.swing.JLabel label_jumlah_koli9;
    private javax.swing.JLabel label_no_kartu_pengirim;
    private javax.swing.JLabel label_tgl_kh;
    private javax.swing.JLabel label_total_data_lab_bahan_baku;
    private javax.swing.JTextField txt_kadar_PH;
    private javax.swing.JTextField txt_kadar_air;
    private javax.swing.JTextField txt_kadar_aluminium;
    private javax.swing.JTextField txt_nitrit_w1;
    private javax.swing.JTextField txt_nitrit_w2;
    private javax.swing.JTextField txt_nitrit_w3;
    private javax.swing.JTextField txt_no_kartu_waleta;
    private javax.swing.JTextField txt_search_Lab_BahanBaku;
    // End of variables declaration//GEN-END:variables
}
