package waleta_system.BahanBaku;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import waleta_system.Class.ColumnsAutoSizer;
import waleta_system.Class.Utility;
import waleta_system.Class.ExportToExcel;
import waleta_system.MainForm;

public class JPanel_Supplier extends javax.swing.JPanel {

    String sql = null;
    ResultSet rs;
    Date date = new Date();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    DefaultTableCellRenderer TableAlignment = new DefaultTableCellRenderer();

    public JPanel_Supplier() {
        initComponents();
    }

    public void init() {
        refreshTable();
        Table_Supplier.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting() && Table_Supplier.getSelectedRow() != -1) {
                    int i = Table_Supplier.getSelectedRow();
                    txt_kode_supplier.setText(Table_Supplier.getValueAt(i, 0).toString());
                    txt_nama_supplier.setText(Table_Supplier.getValueAt(i, 1).toString());
                    txt_alamat_supplier.setText(Table_Supplier.getValueAt(i, 2).toString());
                    txt_no_telp_supplier.setText(Table_Supplier.getValueAt(i, 3).toString());
                    if (Table_Supplier.getValueAt(i, 4).toString().equals("Aktif")) {
                        button_aktifkan.setEnabled(false);
                        button_non_aktifkan.setEnabled(true);
                    } else {
                        button_aktifkan.setEnabled(true);
                        button_non_aktifkan.setEnabled(false);
                    }
                }
            }
        });
    }

    public void refreshTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) Table_Supplier.getModel();
            model.setRowCount(0);
            sql = "SELECT `kode_supplier`, `nama_supplier`, `alamat_supplier`, `no_telp_supplier`, `status_aktif` "
                    + "FROM `waleta_database`.`tb_supplier` "
                    + "WHERE `nama_supplier` LIKE '%" + txt_search_supplier.getText() + "%'";
            rs = Utility.db.getStatement().executeQuery(sql);
            Object[] row = new Object[10];
            while (rs.next()) {
                row[0] = rs.getString("kode_supplier");
                row[1] = rs.getString("nama_supplier");
                row[2] = rs.getString("alamat_supplier");
                row[3] = rs.getString("no_telp_supplier");
                if (rs.getBoolean("status_aktif")) {
                    row[4] = "Aktif";
                } else {
                    row[4] = "Non-Aktif";
                }
                model.addRow(row);
            }
            ColumnsAutoSizer.sizeColumnsToFit(Table_Supplier);
            int rowData = Table_Supplier.getRowCount();
            label_total_data_supplier.setText(Integer.toString(rowData));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(JPanel_Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void executeSQLQuery(String query, String message) {
        Utility.db.getConnection();
        try {
            Utility.db.getConnection().createStatement();
            if ((Utility.db.getStatement().executeUpdate(query)) == 1) {
                JOptionPane.showMessageDialog(this, "data " + message + " Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "data not " + message);
            }
            refreshTable();
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Supplier = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Table_Supplier = new javax.swing.JTable();
        jPanel_operation_supplier = new javax.swing.JPanel();
        button_insert_supplier = new javax.swing.JButton();
        button_update_supplier = new javax.swing.JButton();
        button_clear_supplier = new javax.swing.JButton();
        button_delete_supplier = new javax.swing.JButton();
        txt_no_telp_supplier = new javax.swing.JTextField();
        txt_kode_supplier = new javax.swing.JTextField();
        txt_nama_supplier = new javax.swing.JTextField();
        txt_alamat_supplier = new javax.swing.JTextField();
        label_supplier_1 = new javax.swing.JLabel();
        label_supplier_2 = new javax.swing.JLabel();
        label_supplier_3 = new javax.swing.JLabel();
        label_supplier_4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label_total_data_supplier = new javax.swing.JLabel();
        txt_search_supplier = new javax.swing.JTextField();
        button_search_supplier = new javax.swing.JButton();
        button_export_supplier = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        button_aktifkan = new javax.swing.JButton();
        button_non_aktifkan = new javax.swing.JButton();

        jPanel_Supplier.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Supplier.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Supplier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel_Supplier.setPreferredSize(new java.awt.Dimension(1366, 700));

        Table_Supplier.setAutoCreateRowSorter(true);
        Table_Supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Supplier", "Nama Supplier", "Alamat Supplier", "No Telp Supplier", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Supplier.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(Table_Supplier);

        jPanel_operation_supplier.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_operation_supplier.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Operation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Yu Gothic", 0, 12))); // NOI18N
        jPanel_operation_supplier.setName("aah"); // NOI18N

        button_insert_supplier.setBackground(new java.awt.Color(255, 255, 255));
        button_insert_supplier.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_insert_supplier.setText("insert");
        button_insert_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_insert_supplierActionPerformed(evt);
            }
        });

        button_update_supplier.setBackground(new java.awt.Color(255, 255, 255));
        button_update_supplier.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_update_supplier.setText("Update");
        button_update_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_update_supplierActionPerformed(evt);
            }
        });

        button_clear_supplier.setBackground(new java.awt.Color(255, 255, 255));
        button_clear_supplier.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_clear_supplier.setText("Clear Text");
        button_clear_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clear_supplierActionPerformed(evt);
            }
        });

        button_delete_supplier.setBackground(new java.awt.Color(255, 255, 255));
        button_delete_supplier.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_delete_supplier.setText("Delete");
        button_delete_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_delete_supplierActionPerformed(evt);
            }
        });

        txt_no_telp_supplier.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_kode_supplier.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_nama_supplier.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_alamat_supplier.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        label_supplier_1.setBackground(new java.awt.Color(255, 255, 255));
        label_supplier_1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_supplier_1.setText("Kode Supplier :");

        label_supplier_2.setBackground(new java.awt.Color(255, 255, 255));
        label_supplier_2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_supplier_2.setText("Nama Supplier :");

        label_supplier_3.setBackground(new java.awt.Color(255, 255, 255));
        label_supplier_3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_supplier_3.setText("Alamat Supplier :");

        label_supplier_4.setBackground(new java.awt.Color(255, 255, 255));
        label_supplier_4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_supplier_4.setText("No Telp Supplier :");

        javax.swing.GroupLayout jPanel_operation_supplierLayout = new javax.swing.GroupLayout(jPanel_operation_supplier);
        jPanel_operation_supplier.setLayout(jPanel_operation_supplierLayout);
        jPanel_operation_supplierLayout.setHorizontalGroup(
            jPanel_operation_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_operation_supplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_operation_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_operation_supplierLayout.createSequentialGroup()
                        .addGroup(jPanel_operation_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_supplier_2)
                            .addComponent(label_supplier_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_supplier_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel_operation_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_alamat_supplier)
                            .addComponent(txt_nama_supplier)
                            .addComponent(txt_no_telp_supplier)))
                    .addGroup(jPanel_operation_supplierLayout.createSequentialGroup()
                        .addComponent(label_supplier_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(txt_kode_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_operation_supplierLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_update_supplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_insert_supplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_delete_supplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_clear_supplier)))
                .addContainerGap())
        );
        jPanel_operation_supplierLayout.setVerticalGroup(
            jPanel_operation_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_operation_supplierLayout.createSequentialGroup()
                .addGroup(jPanel_operation_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kode_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_supplier_1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel_operation_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_supplier_2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nama_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel_operation_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_supplier_3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_alamat_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_operation_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_no_telp_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_supplier_4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_update_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_insert_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_delete_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_clear_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Total Data :");

        label_total_data_supplier.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        label_total_data_supplier.setText("TOTAL");

        txt_search_supplier.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_search_supplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_search_supplierKeyPressed(evt);
            }
        });

        button_search_supplier.setBackground(new java.awt.Color(255, 255, 255));
        button_search_supplier.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_search_supplier.setText("Search");
        button_search_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_search_supplierActionPerformed(evt);
            }
        });

        button_export_supplier.setBackground(new java.awt.Color(255, 255, 255));
        button_export_supplier.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_export_supplier.setText("Export To Excel");
        button_export_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_export_supplierActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Search By Nama Supplier :");

        button_aktifkan.setBackground(new java.awt.Color(255, 255, 255));
        button_aktifkan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_aktifkan.setText("Aktifkan");
        button_aktifkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_aktifkanActionPerformed(evt);
            }
        });

        button_non_aktifkan.setBackground(new java.awt.Color(255, 255, 255));
        button_non_aktifkan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_non_aktifkan.setText("Non-Aktifkan");
        button_non_aktifkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_non_aktifkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_SupplierLayout = new javax.swing.GroupLayout(jPanel_Supplier);
        jPanel_Supplier.setLayout(jPanel_SupplierLayout);
        jPanel_SupplierLayout.setHorizontalGroup(
            jPanel_SupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1334, Short.MAX_VALUE)
                    .addGroup(jPanel_SupplierLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_search_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_search_supplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_non_aktifkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_aktifkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_export_supplier))
                    .addGroup(jPanel_SupplierLayout.createSequentialGroup()
                        .addComponent(jPanel_operation_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(65, 65, 65)
                        .addComponent(label_total_data_supplier)))
                .addContainerGap())
        );
        jPanel_SupplierLayout.setVerticalGroup(
            jPanel_SupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SupplierLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel_SupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_SupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_aktifkan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_non_aktifkan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_SupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_search_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_search_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_export_supplier)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_SupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_operation_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_SupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_total_data_supplier)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel_Supplier, javax.swing.GroupLayout.DEFAULT_SIZE, 1364, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_insert_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_insert_supplierActionPerformed
        // TODO add your handling code here:
        Boolean Check = true;
        try {
            if ("".equals(txt_kode_supplier.getText())) {
                JOptionPane.showMessageDialog(this, "Maaf kode Suplier harus diisi !");
                Check = false;
                txt_kode_supplier.requestFocus();
            }
            if (Check) {
                String Query = "INSERT INTO `tb_supplier` (`kode_supplier`, `nama_supplier`, `alamat_supplier`, `no_telp_supplier`) VALUES ('" + txt_kode_supplier.getText() + "', '" + txt_nama_supplier.getText() + "', '" + txt_alamat_supplier.getText() + "', '" + txt_no_telp_supplier.getText() + "')";
                if ((Utility.db.getStatement().executeUpdate(Query)) == 1) {
                    JOptionPane.showMessageDialog(this, "Data Saved !");
                } else {
                    JOptionPane.showMessageDialog(this, "Save Failed!");
                }
                refreshTable();
                button_clear_supplier.doClick();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            Logger.getLogger(JPanel_Supplier.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_insert_supplierActionPerformed

    private void button_update_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_update_supplierActionPerformed
        // TODO add your handling code here:
        int j = Table_Supplier.getSelectedRow();
        Boolean Check = true;
        TableModel model = Table_Supplier.getModel();
        try {
            if (j == -1) {
                JOptionPane.showMessageDialog(this, "Please Select Row Data that you want to Update !");
            } else {
                if ("".equals(txt_kode_supplier.getText())) {
                    JOptionPane.showMessageDialog(this, "Maaf kode Suplier harus diisi !");
                    Check = false;
                    txt_kode_supplier.requestFocus();
                }
                if (Check) {
                    String Query = "UPDATE `tb_supplier` SET `kode_supplier` = '" + txt_kode_supplier.getText() + "', `nama_supplier` = '" + txt_nama_supplier.getText() + "', `alamat_supplier` = '" + txt_alamat_supplier.getText() + "', `no_telp_supplier` = '" + txt_no_telp_supplier.getText() + "' WHERE `tb_supplier`.`kode_supplier` = '" + model.getValueAt(j, 0).toString() + "'";
                    if ((Utility.db.getStatement().executeUpdate(Query)) == 1) {
                        JOptionPane.showMessageDialog(this, "Data Saved !");
                    } else {
                        JOptionPane.showMessageDialog(this, "Save Failed!");
                    }
                    refreshTable();
                    button_clear_supplier.doClick();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            Logger.getLogger(JPanel_Supplier.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_update_supplierActionPerformed

    private void button_clear_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clear_supplierActionPerformed
        // TODO add your handling code here:
        txt_kode_supplier.setText(null);
        txt_nama_supplier.setText(null);
        txt_alamat_supplier.setText(null);
        txt_no_telp_supplier.setText(null);
    }//GEN-LAST:event_button_clear_supplierActionPerformed

    private void button_delete_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_delete_supplierActionPerformed
        // TODO add your handling code here:
        try {
            int j = Table_Supplier.getSelectedRow();
            if (j == -1) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data yang ingin di hapus !");
            } else {
                int dialogResult = JOptionPane.showConfirmDialog(this, "Yakin hapus data ini?", "Warning", 0);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    // delete code here
                    String Query = "DELETE FROM `tb_supplier` WHERE `tb_supplier`.`kode_supplier` = '" + txt_kode_supplier.getText() + "'";
                    if ((Utility.db.getStatement().executeUpdate(Query)) == 1) {
                        JOptionPane.showMessageDialog(this, "Data Saved !");
                    } else {
                        JOptionPane.showMessageDialog(this, "Save Failed!");
                    }
                    refreshTable();
                    button_clear_supplier.doClick();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            Logger.getLogger(JPanel_Supplier.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_delete_supplierActionPerformed

    private void txt_search_supplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_supplierKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            refreshTable();
        }
    }//GEN-LAST:event_txt_search_supplierKeyPressed

    private void button_search_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_search_supplierActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_button_search_supplierActionPerformed

    private void button_export_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_export_supplierActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Table_Supplier.getModel();
        ExportToExcel.writeToExcel(model, jPanel_Supplier);
    }//GEN-LAST:event_button_export_supplierActionPerformed

    private void button_aktifkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_aktifkanActionPerformed
        // TODO add your handling code here:
        try {
            int j = Table_Supplier.getSelectedRow();
            if (j == -1) {
                JOptionPane.showMessageDialog(this, "Pilih data yang akan di edit !");
            } else {
                sql = "UPDATE `tb_supplier` SET "
                        + "`status_aktif`=1 "
                        + "WHERE `kode_supplier`='" + Table_Supplier.getValueAt(j, 0).toString() + "'";
                if ((Utility.db.getStatement().executeUpdate(sql)) == 1) {
                    JOptionPane.showMessageDialog(this, "Set Aktif Berhasil !");
                    refreshTable();
                } else {
                    JOptionPane.showMessageDialog(this, "update failed !");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
            Logger.getLogger(JPanel_Supplier.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_aktifkanActionPerformed

    private void button_non_aktifkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_non_aktifkanActionPerformed
        // TODO add your handling code here:
        try {
            int j = Table_Supplier.getSelectedRow();
            if (j == -1) {
                JOptionPane.showMessageDialog(this, "Pilih data yang akan di edit !");
            } else {
                sql = "UPDATE `tb_supplier` SET "
                        + "`status_aktif`=0 "
                        + "WHERE `kode_supplier`='" + Table_Supplier.getValueAt(j, 0).toString() + "'";
                if ((Utility.db.getStatement().executeUpdate(sql)) == 1) {
                    JOptionPane.showMessageDialog(this, "Set Non-Aktif Berhasil !");
                    refreshTable();
                } else {
                    JOptionPane.showMessageDialog(this, "update failed !");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
            Logger.getLogger(JPanel_Supplier.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_non_aktifkanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Supplier;
    private javax.swing.JButton button_aktifkan;
    private javax.swing.JButton button_clear_supplier;
    public javax.swing.JButton button_delete_supplier;
    private javax.swing.JButton button_export_supplier;
    public javax.swing.JButton button_insert_supplier;
    private javax.swing.JButton button_non_aktifkan;
    private javax.swing.JButton button_search_supplier;
    public javax.swing.JButton button_update_supplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel_Supplier;
    private javax.swing.JPanel jPanel_operation_supplier;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_supplier_1;
    private javax.swing.JLabel label_supplier_2;
    private javax.swing.JLabel label_supplier_3;
    private javax.swing.JLabel label_supplier_4;
    private javax.swing.JLabel label_total_data_supplier;
    private javax.swing.JTextField txt_alamat_supplier;
    private javax.swing.JTextField txt_kode_supplier;
    private javax.swing.JTextField txt_nama_supplier;
    private javax.swing.JTextField txt_no_telp_supplier;
    private javax.swing.JTextField txt_search_supplier;
    // End of variables declaration//GEN-END:variables
}
