package waleta_system.BahanBaku;

import waleta_system.Class.Utility;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import waleta_system.Class.ColumnsAutoSizer;
import waleta_system.Class.ExportToExcel;
import waleta_system.MainForm;

public class JPanel_Customer extends javax.swing.JPanel {

    String sql = null;
    ResultSet rs;
    Date date = new Date();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    DefaultTableCellRenderer TableAlignment = new DefaultTableCellRenderer();

    public JPanel_Customer() {
        initComponents();
    }

    public void init() {
        refreshTable();
        Table_customer_baku.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting() && Table_customer_baku.getSelectedRow() != -1) {
                    int i = Table_customer_baku.getSelectedRow();
                    txt_kode.setText(Table_customer_baku.getValueAt(i, 0).toString());
                    txt_nama_customer_baku.setText(Table_customer_baku.getValueAt(i, 1).toString());
                    txt_alamat_customer_baku.setText(Table_customer_baku.getValueAt(i, 2).toString());
                    txt_no_telp_customer_baku.setText(Table_customer_baku.getValueAt(i, 3).toString());
                }
            }
        });
    }

    public void refreshTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) Table_customer_baku.getModel();
            model.setRowCount(0);
            sql = "SELECT * FROM `waleta_database`.`tb_customer_baku` WHERE `nama_customer` LIKE \"%" + txt_search_customer.getText() + "%\"";
            rs = Utility.db.getStatement().executeQuery(sql);
            Object[] row = new Object[4];
            while (rs.next()) {
                row[0] = rs.getString("kode_cust");
                row[1] = rs.getString("nama_customer");
                row[2] = rs.getString("alamat_customer");
                row[3] = rs.getString("no_telp_customer");
                model.addRow(row);
            }
            ColumnsAutoSizer.sizeColumnsToFit(Table_customer_baku);
            int rowData = Table_customer_baku.getRowCount();
            label_total_data_customer_baku.setText(Integer.toString(rowData));

            TableAlignment.setHorizontalAlignment(JLabel.CENTER);
            for (int i = 0; i < Table_customer_baku.getColumnCount(); i++) {
                Table_customer_baku.getColumnModel().getColumn(i).setCellRenderer(TableAlignment);
            }
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void executeSQLQuery(String query, String message) {
        Utility.db.getConnection();
        try {
            Utility.db.getConnection().createStatement();
            if ((Utility.db.getStatement().executeUpdate(query)) == 1) {
                JOptionPane.showMessageDialog(this, "data " + message + " Successfully");
                refreshTable();
            } else {
                JOptionPane.showMessageDialog(this, "data not " + message);
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Customer_baku = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Table_customer_baku = new javax.swing.JTable();
        jPanel_operation_customer = new javax.swing.JPanel();
        button_insert_customer_baku = new javax.swing.JButton();
        button_update_customer_baku = new javax.swing.JButton();
        button_clear_customer_baku = new javax.swing.JButton();
        button_delete_customer_baku = new javax.swing.JButton();
        txt_no_telp_customer_baku = new javax.swing.JTextField();
        txt_alamat_customer_baku = new javax.swing.JTextField();
        label_nama_customer_baku = new javax.swing.JLabel();
        label_alamat_customer_baku = new javax.swing.JLabel();
        label_noTelp_customer_baku = new javax.swing.JLabel();
        label_nama_customer_baku1 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        txt_nama_customer_baku = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        label_total_data_customer_baku = new javax.swing.JLabel();
        txt_search_customer = new javax.swing.JTextField();
        button_search_customer = new javax.swing.JButton();
        button_export_customer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel_Customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Customer_baku.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Customer Bahan Baku", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel_Customer_baku.setPreferredSize(new java.awt.Dimension(1366, 701));

        Table_customer_baku.setAutoCreateRowSorter(true);
        Table_customer_baku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama Customer", "Alamat Customer", "No Telp Customer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_customer_baku.getTableHeader().setReorderingAllowed(false);
        jScrollPane8.setViewportView(Table_customer_baku);

        jPanel_operation_customer.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_operation_customer.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Operation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Yu Gothic", 0, 12))); // NOI18N
        jPanel_operation_customer.setName("aah"); // NOI18N

        button_insert_customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        button_insert_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_insert_customer_baku.setText("insert");
        button_insert_customer_baku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_insert_customer_bakuActionPerformed(evt);
            }
        });

        button_update_customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        button_update_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_update_customer_baku.setText("Update");
        button_update_customer_baku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_update_customer_bakuActionPerformed(evt);
            }
        });

        button_clear_customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        button_clear_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_clear_customer_baku.setText("Clear Text");
        button_clear_customer_baku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clear_customer_bakuActionPerformed(evt);
            }
        });

        button_delete_customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        button_delete_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_delete_customer_baku.setText("Delete");
        button_delete_customer_baku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_delete_customer_bakuActionPerformed(evt);
            }
        });

        txt_no_telp_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_alamat_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        label_nama_customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        label_nama_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_nama_customer_baku.setText("Kode :");

        label_alamat_customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        label_alamat_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_alamat_customer_baku.setText("Alamat Customer :");

        label_noTelp_customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        label_noTelp_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_noTelp_customer_baku.setText("No Telp Customer :");

        label_nama_customer_baku1.setBackground(new java.awt.Color(255, 255, 255));
        label_nama_customer_baku1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_nama_customer_baku1.setText("Nama Customer :");

        txt_kode.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_nama_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel_operation_customerLayout = new javax.swing.GroupLayout(jPanel_operation_customer);
        jPanel_operation_customer.setLayout(jPanel_operation_customerLayout);
        jPanel_operation_customerLayout.setHorizontalGroup(
            jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_operation_customerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_operation_customerLayout.createSequentialGroup()
                        .addComponent(label_nama_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_operation_customerLayout.createSequentialGroup()
                        .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nama_customer_baku1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_alamat_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_alamat_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nama_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_operation_customerLayout.createSequentialGroup()
                        .addComponent(label_noTelp_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_no_telp_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_operation_customerLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(button_update_customer_baku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_insert_customer_baku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_delete_customer_baku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_clear_customer_baku)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_operation_customerLayout.setVerticalGroup(
            jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_operation_customerLayout.createSequentialGroup()
                .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama_customer_baku1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nama_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_alamat_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_alamat_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_no_telp_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_noTelp_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_update_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_insert_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_delete_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_clear_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel12.setText("Total Data :");

        label_total_data_customer_baku.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        label_total_data_customer_baku.setText("TOTAL");

        txt_search_customer.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_search_customer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_search_customerKeyPressed(evt);
            }
        });

        button_search_customer.setBackground(new java.awt.Color(255, 255, 255));
        button_search_customer.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_search_customer.setText("Search");
        button_search_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_search_customerActionPerformed(evt);
            }
        });

        button_export_customer.setBackground(new java.awt.Color(255, 255, 255));
        button_export_customer.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_export_customer.setText("Export To Excel");
        button_export_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_export_customerActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Nama Customer :");

        javax.swing.GroupLayout jPanel_Customer_bakuLayout = new javax.swing.GroupLayout(jPanel_Customer_baku);
        jPanel_Customer_baku.setLayout(jPanel_Customer_bakuLayout);
        jPanel_Customer_bakuLayout.setHorizontalGroup(
            jPanel_Customer_bakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Customer_bakuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Customer_bakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 1336, Short.MAX_VALUE)
                    .addGroup(jPanel_Customer_bakuLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_search_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_search_customer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_export_customer))
                    .addGroup(jPanel_Customer_bakuLayout.createSequentialGroup()
                        .addComponent(jPanel_operation_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 701, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_total_data_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_Customer_bakuLayout.setVerticalGroup(
            jPanel_Customer_bakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Customer_bakuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Customer_bakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_search_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_export_customer)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Customer_bakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Customer_bakuLayout.createSequentialGroup()
                        .addGroup(jPanel_Customer_bakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_total_data_customer_baku)
                            .addComponent(jLabel12))
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Customer_bakuLayout.createSequentialGroup()
                        .addComponent(jPanel_operation_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel_Customer_baku, javax.swing.GroupLayout.DEFAULT_SIZE, 1364, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel_Customer_baku, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_insert_customer_bakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_insert_customer_bakuActionPerformed
        // TODO add your handling code here:
        Boolean Check = true;
        try {
            String Query = "INSERT INTO `tb_customer_baku` (`kode_cust`, `nama_customer`, `alamat_customer`, `no_telp_customer`) "
                    + "VALUES ('" + txt_kode.getText() + "', '" + txt_nama_customer_baku.getText() + "', '" + txt_alamat_customer_baku.getText() + "', '" + txt_no_telp_customer_baku.getText() + "')";
            executeSQLQuery(Query, "inserted !");
            button_clear_customer_baku.doClick();
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_button_insert_customer_bakuActionPerformed

    private void button_update_customer_bakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_update_customer_bakuActionPerformed
        // TODO add your handling code here:
        //        DefaultTableModel Table = (DefaultTableModel)Table_customer_baku.getModel();
        int total_baris = Table_customer_baku.getRowCount();
        int j = Table_customer_baku.getSelectedRow();
        Boolean Check = true;
        try {
            if (j == -1) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih salah satu data pada tabel !");
            } else {
                if (!txt_nama_customer_baku.getText().equals(Table_customer_baku.getValueAt(j, 1))) {
                    for (int i = 0; i < total_baris; i++) {
                        if (txt_nama_customer_baku.getText().equals(Table_customer_baku.getValueAt(i, 0))) {
                            JOptionPane.showMessageDialog(this, "Nama Customer (" + txt_nama_customer_baku.getText() + ") sudah ada, untuk membedakan, tolong masukkan nama yang berbeda");
                            Check = false;
                        }
                    }
                }
                if (Check) {
                    String Query = "UPDATE `tb_customer_baku` SET "
                            + "`kode_cust` = '" + txt_kode.getText() + "', "
                            + "`nama_customer` = '" + txt_nama_customer_baku.getText() + "', "
                            + "`alamat_customer` = '" + txt_alamat_customer_baku.getText() + "', "
                            + "`no_telp_customer` = '" + txt_no_telp_customer_baku.getText() + "' "
                            + "WHERE `tb_customer_baku`.`kode_cust` = '" + Table_customer_baku.getValueAt(j, 0).toString() + "'";
                    executeSQLQuery(Query, "updated !");
                    button_clear_customer_baku.doClick();
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_button_update_customer_bakuActionPerformed

    private void button_clear_customer_bakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clear_customer_bakuActionPerformed
        // TODO add your handling code here:
        txt_kode.setText(null);
        txt_nama_customer_baku.setText(null);
        txt_alamat_customer_baku.setText(null);
        txt_no_telp_customer_baku.setText(null);
    }//GEN-LAST:event_button_clear_customer_bakuActionPerformed

    private void button_delete_customer_bakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_delete_customer_bakuActionPerformed
        // TODO add your handling code here:
        try {
            int j = Table_customer_baku.getSelectedRow();
            if (j == -1) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data yang ingin di hapus !");
            } else {
                int dialogResult = JOptionPane.showConfirmDialog(this, "Yakin hapus data ini?", "Warning", 0);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    // delete code here
                    String Query = "DELETE FROM `tb_customer_baku` WHERE `tb_customer_baku`.`kode_cust` = '" + txt_kode.getText() + "'";
                    executeSQLQuery(Query, "deleted !");
                    button_clear_customer_baku.doClick();
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_button_delete_customer_bakuActionPerformed

    private void txt_search_customerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_customerKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            refreshTable();
        }
    }//GEN-LAST:event_txt_search_customerKeyPressed

    private void button_search_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_search_customerActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_button_search_customerActionPerformed

    private void button_export_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_export_customerActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Table_customer_baku.getModel();
        ExportToExcel.writeToExcel(model, jPanel_Customer_baku);
    }//GEN-LAST:event_button_export_customerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_customer_baku;
    private javax.swing.JButton button_clear_customer_baku;
    public javax.swing.JButton button_delete_customer_baku;
    private javax.swing.JButton button_export_customer;
    public javax.swing.JButton button_insert_customer_baku;
    private javax.swing.JButton button_search_customer;
    public javax.swing.JButton button_update_customer_baku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel_Customer_baku;
    private javax.swing.JPanel jPanel_operation_customer;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel label_alamat_customer_baku;
    private javax.swing.JLabel label_nama_customer_baku;
    private javax.swing.JLabel label_nama_customer_baku1;
    private javax.swing.JLabel label_noTelp_customer_baku;
    private javax.swing.JLabel label_total_data_customer_baku;
    private javax.swing.JTextField txt_alamat_customer_baku;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_nama_customer_baku;
    private javax.swing.JTextField txt_no_telp_customer_baku;
    private javax.swing.JTextField txt_search_customer;
    // End of variables declaration//GEN-END:variables
}
