package waleta_system.Panel_produksi;

import waleta_system.Class.Utility;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import waleta_system.Browse_Karyawan;

public class JDialog_Edit_Data_Cuci extends javax.swing.JDialog {

    String sql = null;
    ResultSet rs;
    Date date = new Date();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    public JDialog_Edit_Data_Cuci(java.awt.Frame parent, boolean modal, String no_lp) {
        super(parent, modal);
        this.setResizable(false);
        initComponents();
        try {
            sql = "SELECT `no_laporan_produksi`, `tgl_masuk_cuci`, `cuci_diterima`, `cuci_diserahkan`, "
                    + "`cuci_kaki_besar`, `cuci_kaki_kecil`, `cuci_hilang_kaki`, \n"
                    + "`cuci_ada_susur`, `cuci_ada_susur_besar`, `cuci_tanpa_susur`, `cuci_utuh`, \n"
                    + "`cuci_hilang_ujung`, `cuci_pecah`, `cuci_pecah_2`, `cuci_sobek_lepas`, `cuci_gumpil`, `cuci_sobek`,  "
                    + "`tb_cuci`.`id_pegawai` AS 'id_pekerja_cuci', cuci.`nama_pegawai` AS 'nama_pekerja_cuci', `admin_cuci`, "
                    + "`pekerja_kopyok_cuci`, kopyok.`nama_pegawai` AS 'nama_pekerja_kopyok' "
                    + "FROM `tb_cuci` "
                    + "LEFT JOIN `tb_karyawan` cuci ON `tb_cuci`.`id_pegawai` = cuci.`id_pegawai`\n"
                    + "LEFT JOIN `tb_karyawan` kopyok ON `tb_cuci`.`pekerja_kopyok_cuci` = kopyok.`id_pegawai`\n"
                    + "WHERE `no_laporan_produksi` = '" + no_lp + "'";
            rs = Utility.db.getStatement().executeQuery(sql);
            if (rs.next()) {
                label_no_lp.setText(rs.getString("no_laporan_produksi"));
                Date_tgl_masuk.setDate(rs.getDate("tgl_masuk_cuci"));
                txt_diterima.setText(rs.getString("cuci_diterima"));
                txt_diserahkan.setText(rs.getString("cuci_diserahkan"));
                
                txt_kaki_besar.setText(rs.getString("cuci_kaki_besar"));
                txt_kaki_kecil.setText(rs.getString("cuci_kaki_kecil"));
                txt_tanpa_kaki.setText(rs.getString("cuci_hilang_kaki"));
                txt_cuci_ada_susur.setText(rs.getString("cuci_ada_susur"));
                txt_cuci_ada_susur_besar.setText(rs.getString("cuci_ada_susur_besar"));
                txt_cuci_tanpa_susur.setText(rs.getString("cuci_tanpa_susur"));
                
                txt_cuci_utuh.setText(rs.getString("cuci_utuh"));
                txt_hilang_ujung.setText(rs.getString("cuci_hilang_ujung"));
                txt_pecah.setText(rs.getString("cuci_pecah"));
                txt_pecah2.setText(rs.getString("cuci_pecah_2"));
                txt_sobek.setText(rs.getString("cuci_sobek"));
                txt_sobek_lepas.setText(rs.getString("cuci_sobek_lepas"));
                txt_gumpil.setText(rs.getString("cuci_gumpil"));
                
                txt_id_pekerja_cuci.setText(rs.getString("id_pekerja_cuci"));
                txt_nama_pekerja_cuci.setText(rs.getString("nama_pekerja_cuci"));
                txt_admin.setText(rs.getString("admin_cuci"));
                txt_id_pekerja_kopyok.setText(rs.getString("pekerja_kopyok_cuci"));
                txt_nama_pekerja_kopyok.setText(rs.getString("nama_pekerja_kopyok"));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(JDialog_Edit_Data_Cuci.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_admin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_nama_pekerja_cuci = new javax.swing.JTextField();
        txt_id_pekerja_cuci = new javax.swing.JTextField();
        label_no_lp = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_diserahkan = new javax.swing.JTextField();
        button_save = new javax.swing.JButton();
        button_pick_diserahkan = new javax.swing.JButton();
        button_pick_admin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_diterima = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Date_tgl_masuk = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        button_pick_pekerja_cuci = new javax.swing.JButton();
        button_pick_diterima = new javax.swing.JButton();
        txt_nama_pekerja_kopyok = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_id_pekerja_kopyok = new javax.swing.JTextField();
        button_pick_pekerja_kopyok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_kaki_besar = new javax.swing.JTextField();
        txt_kaki_kecil = new javax.swing.JTextField();
        txt_tanpa_kaki = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_cuci_utuh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_hilang_ujung = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_pecah = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_pecah2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_sobek = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_sobek_lepas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_gumpil = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_cuci_ada_susur = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_cuci_ada_susur_besar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_cuci_tanpa_susur = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Data Cabut");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txt_admin.setEditable(false);
        txt_admin.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Edit Data Cuci");

        txt_nama_pekerja_cuci.setEditable(false);
        txt_nama_pekerja_cuci.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_id_pekerja_cuci.setEditable(false);
        txt_id_pekerja_cuci.setBackground(new java.awt.Color(255, 255, 255));
        txt_id_pekerja_cuci.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        label_no_lp.setBackground(new java.awt.Color(255, 255, 255));
        label_no_lp.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label_no_lp.setText("NO. Laporan Produksi");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("Diserahkan Oleh :");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel11.setText("Admin :");

        txt_diserahkan.setEditable(false);
        txt_diserahkan.setBackground(new java.awt.Color(255, 255, 255));
        txt_diserahkan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        button_save.setBackground(new java.awt.Color(255, 255, 255));
        button_save.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        button_pick_diserahkan.setBackground(new java.awt.Color(255, 255, 255));
        button_pick_diserahkan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_pick_diserahkan.setText("...");
        button_pick_diserahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pick_diserahkanActionPerformed(evt);
            }
        });

        button_pick_admin.setBackground(new java.awt.Color(255, 255, 255));
        button_pick_admin.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_pick_admin.setText("...");
        button_pick_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pick_adminActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Diterima Oleh :");

        txt_diterima.setEditable(false);
        txt_diterima.setBackground(new java.awt.Color(255, 255, 255));
        txt_diterima.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel17.setText("Pekerja Cuci :");

        Date_tgl_masuk.setBackground(new java.awt.Color(255, 255, 255));
        Date_tgl_masuk.setDateFormatString("dd MMMM yyyy");
        Date_tgl_masuk.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Date_tgl_masuk.setMaxSelectableDate(new Date());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("Tanggal Cuci:");

        button_pick_pekerja_cuci.setBackground(new java.awt.Color(255, 255, 255));
        button_pick_pekerja_cuci.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_pick_pekerja_cuci.setText("...");
        button_pick_pekerja_cuci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pick_pekerja_cuciActionPerformed(evt);
            }
        });

        button_pick_diterima.setBackground(new java.awt.Color(255, 255, 255));
        button_pick_diterima.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_pick_diterima.setText("...");
        button_pick_diterima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pick_diterimaActionPerformed(evt);
            }
        });

        txt_nama_pekerja_kopyok.setEditable(false);
        txt_nama_pekerja_kopyok.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel18.setText("Pekerja Kopyok :");

        txt_id_pekerja_kopyok.setEditable(false);
        txt_id_pekerja_kopyok.setBackground(new java.awt.Color(255, 255, 255));
        txt_id_pekerja_kopyok.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        button_pick_pekerja_kopyok.setBackground(new java.awt.Color(255, 255, 255));
        button_pick_pekerja_kopyok.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_pick_pekerja_kopyok.setText("...");
        button_pick_pekerja_kopyok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pick_pekerja_kopyokActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel22.setText("Cuci Kaki Kecil :");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel21.setText("Cuci Kaki Besar :");

        txt_kaki_besar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_kaki_besar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_kaki_besar.setText("0");

        txt_kaki_kecil.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_kaki_kecil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_kaki_kecil.setText("0");

        txt_tanpa_kaki.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_tanpa_kaki.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_tanpa_kaki.setText("0");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel19.setText("Cuci Tanpa Kaki :");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel20.setText("Cuci Utuh :");

        txt_cuci_utuh.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_cuci_utuh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cuci_utuh.setText("0");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setText("Cuci Hilang Ujung:");

        txt_hilang_ujung.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_hilang_ujung.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_hilang_ujung.setText("0");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setText("Cuci Pecah :");

        txt_pecah.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_pecah.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pecah.setText("0");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel9.setText("Cuci Pecah 2 :");

        txt_pecah2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_pecah2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pecah2.setText("0");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setText("Cuci Sobek :");

        txt_sobek.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_sobek.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_sobek.setText("0");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel15.setText("Cuci Sobek Lepas :");

        txt_sobek_lepas.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_sobek_lepas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_sobek_lepas.setText("0");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel10.setText("Cuci Gumpil :");

        txt_gumpil.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_gumpil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_gumpil.setText("0");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel12.setText("Cuci ada susur :");

        txt_cuci_ada_susur.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_cuci_ada_susur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cuci_ada_susur.setText("0");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel13.setText("Cuci ada susur besar :");

        txt_cuci_ada_susur_besar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_cuci_ada_susur_besar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cuci_ada_susur_besar.setText("0");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel14.setText("Cuci tanpa susur :");

        txt_cuci_tanpa_susur.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_cuci_tanpa_susur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cuci_tanpa_susur.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cuci_ada_susur_besar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cuci_tanpa_susur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kaki_besar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tanpa_kaki, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kaki_kecil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cuci_ada_susur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_sobek, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sobek_lepas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gumpil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cuci_utuh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pecah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hilang_ujung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pecah2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kaki_besar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cuci_utuh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kaki_kecil, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hilang_ujung, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tanpa_kaki, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pecah, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pecah2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cuci_ada_susur, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cuci_ada_susur_besar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cuci_tanpa_susur, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sobek, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sobek_lepas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gumpil, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_diterima, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_pick_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_pick_pekerja_cuci, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_pick_diserahkan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_pick_diterima, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_id_pekerja_cuci, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nama_pekerja_cuci, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nama_pekerja_kopyok, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date_tgl_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(label_no_lp)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_diserahkan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(button_pick_pekerja_kopyok, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id_pekerja_kopyok, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_save)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_no_lp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Date_tgl_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_diterima, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_diserahkan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_id_pekerja_cuci, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(button_pick_diserahkan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_pick_pekerja_cuci, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button_pick_diterima, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nama_pekerja_cuci, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_id_pekerja_kopyok, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button_pick_pekerja_kopyok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nama_pekerja_kopyok, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button_pick_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_save)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        // TODO add your handling code here:
        try {
            if (txt_diterima.getText() == null || txt_diterima.getText().equals("")
                    || txt_diserahkan.getText() == null || txt_diserahkan.getText().equals("")
                    || txt_id_pekerja_cuci.getText() == null || txt_id_pekerja_cuci.getText().equals("")
                    || Date_tgl_masuk.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Silahkan lengkapi data diatas !");
            } else {
                String update_pekerja_kopyok = "`pekerja_kopyok_cuci`='" + txt_id_pekerja_kopyok.getText() + "',";
                if (txt_id_pekerja_kopyok.getText() == null || txt_id_pekerja_kopyok.getText().equals("")) {
                    update_pekerja_kopyok = "";
                }
                String Query = "UPDATE `tb_cuci` SET "
                        + "`tgl_masuk_cuci`='" + dateFormat.format(Date_tgl_masuk.getDate()) + "',"
                        + "`cuci_diterima`='" + txt_diterima.getText() + "',"
                        + "`cuci_diserahkan`='" + txt_diserahkan.getText() + "',"
                        
                        + "`cuci_kaki_besar`='" + txt_kaki_besar.getText() + "',"
                        + "`cuci_kaki_kecil`='" + txt_kaki_kecil.getText() + "',"
                        + "`cuci_hilang_kaki`='" + txt_tanpa_kaki.getText() + "',"
                        + "`cuci_ada_susur`='" + txt_cuci_ada_susur.getText() + "',"
                        + "`cuci_ada_susur_besar`='" + txt_cuci_ada_susur_besar.getText() + "',"
                        + "`cuci_tanpa_susur`='" + txt_cuci_tanpa_susur.getText() + "',"
                        
                        + "`cuci_utuh`='" + txt_cuci_utuh.getText() + "',"
                        + "`cuci_hilang_ujung`='" + txt_hilang_ujung.getText() + "',"
                        + "`cuci_pecah`='" + txt_pecah.getText() + "',"
                        + "`cuci_pecah_2`='" + txt_pecah2.getText() + "',"
                        + "`cuci_sobek`='" + txt_sobek.getText() + "',"
                        + "`cuci_sobek_lepas`='" + txt_sobek_lepas.getText() + "',"
                        + "`cuci_gumpil`='" + txt_gumpil.getText() + "',"
                        
                        + "`id_pegawai`='" + txt_id_pekerja_cuci.getText() + "',"
                        + update_pekerja_kopyok
                        + "`admin_cuci`='" + txt_admin.getText() + "' "
                        + "WHERE `no_laporan_produksi`='" + label_no_lp.getText() + "'";
                Utility.db.getConnection().createStatement();
                if ((Utility.db.getStatement().executeUpdate(Query)) == 1) {
                    JOptionPane.showMessageDialog(this, "Perubahan data berhasil disimpan");
                    this.dispose();
                    JPanel_DataCuci.button_search_cuci.doClick();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            Logger.getLogger(JDialog_Edit_Data_Cuci.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_saveActionPerformed

    private void button_pick_diterimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pick_diterimaActionPerformed
        // TODO add your handling code here:
        Browse_Karyawan dialog = new Browse_Karyawan(new javax.swing.JFrame(), true, null);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);

        int x = Browse_Karyawan.table_list_karyawan.getSelectedRow();
        if (x != -1) {
            txt_diterima.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 1).toString());
        }
    }//GEN-LAST:event_button_pick_diterimaActionPerformed

    private void button_pick_diserahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pick_diserahkanActionPerformed
        // TODO add your handling code here:
        Browse_Karyawan dialog = new Browse_Karyawan(new javax.swing.JFrame(), true, null);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);

        int x = Browse_Karyawan.table_list_karyawan.getSelectedRow();
        if (x != -1) {
            txt_diserahkan.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 1).toString());
        }
    }//GEN-LAST:event_button_pick_diserahkanActionPerformed

    private void button_pick_pekerja_cuciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pick_pekerja_cuciActionPerformed
        // TODO add your handling code here:
        Browse_Karyawan dialog = new Browse_Karyawan(new javax.swing.JFrame(), true, null);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);

        int x = Browse_Karyawan.table_list_karyawan.getSelectedRow();
        if (x != -1) {
            txt_id_pekerja_cuci.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 0).toString());
            txt_nama_pekerja_cuci.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 1).toString());
        }
    }//GEN-LAST:event_button_pick_pekerja_cuciActionPerformed

    private void button_pick_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pick_adminActionPerformed
        // TODO add your handling code here:
        Browse_Karyawan dialog = new Browse_Karyawan(new javax.swing.JFrame(), true, null);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);

        int x = Browse_Karyawan.table_list_karyawan.getSelectedRow();
        if (x != -1) {
            txt_admin.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 1).toString());
        }
    }//GEN-LAST:event_button_pick_adminActionPerformed

    private void button_pick_pekerja_kopyokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pick_pekerja_kopyokActionPerformed
        // TODO add your handling code here:
        Browse_Karyawan dialog = new Browse_Karyawan(new javax.swing.JFrame(), true, null);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);

        int x = Browse_Karyawan.table_list_karyawan.getSelectedRow();
        if (x != -1) {
            txt_id_pekerja_kopyok.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 0).toString());
            txt_nama_pekerja_kopyok.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 1).toString());
        }
    }//GEN-LAST:event_button_pick_pekerja_kopyokActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_tgl_masuk;
    private javax.swing.JButton button_pick_admin;
    private javax.swing.JButton button_pick_diserahkan;
    private javax.swing.JButton button_pick_diterima;
    private javax.swing.JButton button_pick_pekerja_cuci;
    private javax.swing.JButton button_pick_pekerja_kopyok;
    private javax.swing.JButton button_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_no_lp;
    private javax.swing.JTextField txt_admin;
    private javax.swing.JTextField txt_cuci_ada_susur;
    private javax.swing.JTextField txt_cuci_ada_susur_besar;
    private javax.swing.JTextField txt_cuci_tanpa_susur;
    private javax.swing.JTextField txt_cuci_utuh;
    private javax.swing.JTextField txt_diserahkan;
    private javax.swing.JTextField txt_diterima;
    private javax.swing.JTextField txt_gumpil;
    private javax.swing.JTextField txt_hilang_ujung;
    private javax.swing.JTextField txt_id_pekerja_cuci;
    private javax.swing.JTextField txt_id_pekerja_kopyok;
    private javax.swing.JTextField txt_kaki_besar;
    private javax.swing.JTextField txt_kaki_kecil;
    private javax.swing.JTextField txt_nama_pekerja_cuci;
    private javax.swing.JTextField txt_nama_pekerja_kopyok;
    private javax.swing.JTextField txt_pecah;
    private javax.swing.JTextField txt_pecah2;
    private javax.swing.JTextField txt_sobek;
    private javax.swing.JTextField txt_sobek_lepas;
    private javax.swing.JTextField txt_tanpa_kaki;
    // End of variables declaration//GEN-END:variables
}
