package waleta_system.Panel_produksi;

import waleta_system.Class.Utility;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import waleta_system.Browse_Karyawan;
import waleta_system.MainForm;

public class JDialog_Edit_Data_Cetak extends javax.swing.JDialog {

    String sql = null;
    ResultSet rs;
    Date date = new Date();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    public JDialog_Edit_Data_Cetak(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setResizable(false);
        initComponents();
        getdata();
    }

    public void getdata() {
        try {

            int i = JPanel_DataCetak.Table_Data_Cetak.getSelectedRow();
            sql = "SELECT `tb_cetak`.`no_laporan_produksi`, `jumlah_keping`, `tgl_mulai_cetak`, `cetak_diterima`, `tgl_selesai_cetak`, `cetak_diserahkan`, `cetak_dikerjakan`, "
                    + "`cetak_dikerjakan1`, CTK1.`nama_pegawai` AS 'pekerja_cetak1', `cetak_dikerjakan_level1`, CTK2.`nama_pegawai` AS 'pekerja_cetak2', `cetak_dikerjakan_grup`, `cetak_dikerjakan_level`, `cetak_dikoreksi`, `cetak_dikoreksi_id`, `cetak_dikoreksi_grup`, `cetak_dikoreksi_level`, `cetak_mangkok`, `cetak_pecah`, `cetak_flat`, `cetak_jidun`, `cetak_jidun_real`, `admin_cetak`, `tgl_jam_input_setor` \n"
                    + "FROM `tb_cetak` "
                    + "LEFT JOIN `tb_laporan_produksi` ON `tb_cetak`.`no_laporan_produksi` = `tb_laporan_produksi`.`no_laporan_produksi`\n"
                    + "LEFT JOIN `tb_karyawan` CTK1 ON `tb_cetak`.`cetak_dikerjakan1` = CTK1.`id_pegawai`\n"
                    + "LEFT JOIN `tb_karyawan` CTK2 ON `tb_cetak`.`cetak_dikerjakan` = CTK2.`id_pegawai`\n"
                    + "WHERE `tb_cetak`.`no_laporan_produksi` = '" + JPanel_DataCetak.Table_Data_Cetak.getValueAt(i, 0).toString() + "'";
            rs = Utility.db.getStatement().executeQuery(sql);
            if (rs.next()) {
                label_no_lp.setText(rs.getString("no_laporan_produksi"));
                label_total_keping.setText(rs.getString("jumlah_keping"));
                String tgl_masuk = rs.getString("tgl_mulai_cetak");
                Date_tgl_masuk.setDate(dateFormat.parse(tgl_masuk));
                txt_diterima.setText(rs.getString("cetak_diterima"));
//                if (rs.getString("tgl_selesai_cetak") == null) {
//                    Date_tgl_selesai.setDate(null);
//                } else {
//                    String tgl_setor = rs.getString("tgl_selesai_cetak");
//                    Date_tgl_selesai.setDate(dateFormat.parse(tgl_setor));
//                }
                txt_diserahkan.setText(rs.getString("cetak_diserahkan"));
                Date_tgl_selesai.setDate(rs.getDate("tgl_selesai_cetak"));
                txt_pekerja_cetak1_id.setText(rs.getString("cetak_dikerjakan1"));
                txt_pekerja_cetak1_nama.setText(rs.getString("pekerja_cetak1"));
                txt_pekerja_cetak2_id.setText(rs.getString("cetak_dikerjakan"));
                txt_pekerja_cetak2_nama.setText(rs.getString("pekerja_cetak2"));
                txt_pekerja_koreksi_id.setText(rs.getString("cetak_dikoreksi_id"));
                txt_pekerja_koreksi_nama.setText(rs.getString("cetak_dikoreksi"));
                txt_mk.setText(rs.getString("cetak_mangkok"));
                txt_mk_pecah.setText(rs.getString("cetak_pecah"));
                txt_flat.setText(rs.getString("cetak_flat"));
                txt_jidun.setText(rs.getString("cetak_jidun"));
                txt_jidun_real.setText(rs.getString("cetak_jidun_real"));
                txt_admin.setText(rs.getString("admin_cetak"));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(JDialog_Edit_Data_Cetak.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txt_admin = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_mk = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_diserahkan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        label_no_lp = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        button_pick_diterima = new javax.swing.JButton();
        button_pick_admin = new javax.swing.JButton();
        txt_jidun = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_pekerja_koreksi_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_diterima = new javax.swing.JTextField();
        txt_pekerja_cetak2_nama = new javax.swing.JTextField();
        label_total_keping = new javax.swing.JLabel();
        button_save = new javax.swing.JButton();
        txt_jidun_real = new javax.swing.JTextField();
        Date_tgl_selesai = new com.toedter.calendar.JDateChooser();
        txt_pekerja_cetak2_id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_pekerja_koreksi_nama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_flat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        button_pick_pekerja_koreksi = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_mk_pecah = new javax.swing.JTextField();
        button_pick_diserahkan = new javax.swing.JButton();
        Date_tgl_masuk = new com.toedter.calendar.JDateChooser();
        button_pilih_pekerja_cetak2 = new javax.swing.JButton();
        txt_pekerja_cetak1_nama = new javax.swing.JTextField();
        button_pilih_pekerja_cetak1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txt_pekerja_cetak1_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Data Cetak");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel19.setText("Jidun Real :");

        txt_admin.setEditable(false);
        txt_admin.setBackground(new java.awt.Color(255, 255, 255));
        txt_admin.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel17.setText("Pekerja Cetak 2:");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel13.setText("Keping");

        txt_mk.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_mk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mk.setText("0");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel18.setText("Dikoreksi Oleh :");

        txt_diserahkan.setEditable(false);
        txt_diserahkan.setBackground(new java.awt.Color(255, 255, 255));
        txt_diserahkan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel9.setText("Total Keping LP :");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel14.setText("Keping");

        label_no_lp.setBackground(new java.awt.Color(255, 255, 255));
        label_no_lp.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label_no_lp.setText("NO. Laporan Produksi");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("Tanggal Masuk:");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setText("Flat :");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel16.setText("Keping");

        button_pick_diterima.setBackground(new java.awt.Color(255, 255, 255));
        button_pick_diterima.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_pick_diterima.setText("...");
        button_pick_diterima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pick_diterimaActionPerformed(evt);
            }
        });

        button_pick_admin.setBackground(new java.awt.Color(255, 255, 255));
        button_pick_admin.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_pick_admin.setText("...");
        button_pick_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pick_adminActionPerformed(evt);
            }
        });

        txt_jidun.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_jidun.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_jidun.setText("0");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("Diserahkan Oleh :");

        txt_pekerja_koreksi_id.setEditable(false);
        txt_pekerja_koreksi_id.setBackground(new java.awt.Color(255, 255, 255));
        txt_pekerja_koreksi_id.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("Tanggal Selesai :");

        txt_diterima.setEditable(false);
        txt_diterima.setBackground(new java.awt.Color(255, 255, 255));
        txt_diterima.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_pekerja_cetak2_nama.setEditable(false);
        txt_pekerja_cetak2_nama.setBackground(new java.awt.Color(255, 255, 255));
        txt_pekerja_cetak2_nama.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        label_total_keping.setBackground(new java.awt.Color(255, 255, 255));
        label_total_keping.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_total_keping.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_total_keping.setText("88");

        button_save.setBackground(new java.awt.Color(255, 255, 255));
        button_save.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        txt_jidun_real.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_jidun_real.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_jidun_real.setText("0");

        Date_tgl_selesai.setBackground(new java.awt.Color(255, 255, 255));
        Date_tgl_selesai.setDateFormatString("dd MMMM yyyy");
        Date_tgl_selesai.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Date_tgl_selesai.setMaxSelectableDate(new Date());

        txt_pekerja_cetak2_id.setEditable(false);
        txt_pekerja_cetak2_id.setBackground(new java.awt.Color(255, 255, 255));
        txt_pekerja_cetak2_id.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel10.setText("Jidun :");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel15.setText("Keping");

        txt_pekerja_koreksi_nama.setEditable(false);
        txt_pekerja_koreksi_nama.setBackground(new java.awt.Color(255, 255, 255));
        txt_pekerja_koreksi_nama.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setText("Mangkok Pecah :");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel20.setText("Keping");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Edit Data Cetak");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel12.setText("Keping");

        txt_flat.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_flat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_flat.setText("0");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Diterima Oleh :");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel11.setText("Admin :");

        button_pick_pekerja_koreksi.setBackground(new java.awt.Color(255, 255, 255));
        button_pick_pekerja_koreksi.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_pick_pekerja_koreksi.setText("...");
        button_pick_pekerja_koreksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pick_pekerja_koreksiActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setText("Mangkok Utuh :");

        txt_mk_pecah.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_mk_pecah.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mk_pecah.setText("0");

        button_pick_diserahkan.setBackground(new java.awt.Color(255, 255, 255));
        button_pick_diserahkan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_pick_diserahkan.setText("...");
        button_pick_diserahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pick_diserahkanActionPerformed(evt);
            }
        });

        Date_tgl_masuk.setBackground(new java.awt.Color(255, 255, 255));
        Date_tgl_masuk.setDateFormatString("dd MMMM yyyy");
        Date_tgl_masuk.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Date_tgl_masuk.setMaxSelectableDate(new Date());

        button_pilih_pekerja_cetak2.setBackground(new java.awt.Color(255, 255, 255));
        button_pilih_pekerja_cetak2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_pilih_pekerja_cetak2.setText("...");
        button_pilih_pekerja_cetak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pilih_pekerja_cetak2ActionPerformed(evt);
            }
        });

        txt_pekerja_cetak1_nama.setEditable(false);
        txt_pekerja_cetak1_nama.setBackground(new java.awt.Color(255, 255, 255));
        txt_pekerja_cetak1_nama.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        button_pilih_pekerja_cetak1.setBackground(new java.awt.Color(255, 255, 255));
        button_pilih_pekerja_cetak1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_pilih_pekerja_cetak1.setText("...");
        button_pilih_pekerja_cetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pilih_pekerja_cetak1ActionPerformed(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel21.setText("Pekerja Cetak 1 :");

        txt_pekerja_cetak1_id.setEditable(false);
        txt_pekerja_cetak1_id.setBackground(new java.awt.Color(255, 255, 255));
        txt_pekerja_cetak1_id.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_no_lp)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Date_tgl_masuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_diterima)
                                .addGap(0, 0, 0)
                                .addComponent(button_pick_diterima, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Date_tgl_selesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_diserahkan)
                                .addGap(0, 0, 0)
                                .addComponent(button_pick_diserahkan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_pekerja_cetak2_id)
                                    .addComponent(txt_pekerja_koreksi_id))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_pilih_pekerja_cetak2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button_pick_pekerja_koreksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_admin, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(label_total_keping, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_mk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_mk_pecah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_flat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_jidun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_jidun_real, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel13))
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addComponent(button_pick_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_pekerja_cetak1_id)
                                .addGap(0, 0, 0)
                                .addComponent(button_pilih_pekerja_cetak1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_pekerja_cetak1_nama)
                            .addComponent(txt_pekerja_cetak2_nama)
                            .addComponent(txt_pekerja_koreksi_nama))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_save)
                        .addGap(10, 10, 10))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_no_lp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Date_tgl_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_diterima, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Date_tgl_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_diserahkan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_pick_diserahkan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(button_pick_diterima, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_pekerja_cetak1_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_pilih_pekerja_cetak1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pekerja_cetak1_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pekerja_cetak2_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_pilih_pekerja_cetak2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_pick_pekerja_koreksi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_pekerja_koreksi_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_pekerja_cetak2_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pekerja_koreksi_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_total_keping, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mk, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mk_pecah, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_flat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jidun, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jidun_real, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_pick_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_save, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        // TODO add your handling code here:
        Utility.db.getConnection();
        int mk = Integer.valueOf(txt_mk.getText());
        int pecah = Integer.valueOf(txt_mk_pecah.getText());
        int flat = Integer.valueOf(txt_flat.getText());
        int jidun = Integer.valueOf(txt_jidun.getText());
        int total_cetak = mk + pecah + flat + jidun;
        int total_keping = Integer.valueOf(label_total_keping.getText());
        String tgl_selesai = "";
        if (Date_tgl_selesai.getDate() != null) {
            tgl_selesai = dateFormat.format(Date_tgl_selesai.getDate());
        }
        String input_pekerja_cetak1 = "";
        if (txt_pekerja_cetak1_id.getText() != null && !txt_pekerja_cetak1_id.getText().equals("")) {
            input_pekerja_cetak1 = "`cetak_dikerjakan1`='" + txt_pekerja_cetak1_id.getText() + "', "
                    + "`cetak_dikerjakan_level1`=(SELECT `level_gaji` FROM `tb_karyawan` WHERE `id_pegawai` = '" + txt_pekerja_cetak1_id.getText() + "'), ";
        }
        String Query = "UPDATE `tb_cetak` SET "
                + "`cetak_diterima`='" + txt_diterima.getText() + "',"
                + "`tgl_mulai_cetak`='" + dateFormat.format(Date_tgl_masuk.getDate()) + "',"
                + "`cetak_diserahkan`='" + txt_diserahkan.getText() + "',"
                + "`tgl_selesai_cetak`='" + tgl_selesai + "',"
                + input_pekerja_cetak1
                + "`cetak_dikerjakan`='" + txt_pekerja_cetak2_id.getText() + "',"
                + "`cetak_dikerjakan_grup`=(SELECT `tb_bagian`.`nama_bagian` FROM `tb_karyawan` LEFT JOIN `tb_bagian` ON `tb_karyawan`.`kode_bagian` = `tb_bagian`.`kode_bagian` WHERE `tb_karyawan`.`id_pegawai` = '" + txt_pekerja_cetak2_id.getText() + "'),"
                + "`cetak_dikerjakan_level`=(SELECT `level_gaji` FROM `tb_karyawan` WHERE `id_pegawai` = '" + txt_pekerja_cetak2_id.getText() + "'),"
                + "`cetak_dikoreksi`='" + txt_pekerja_koreksi_nama.getText() + "',"
                + "`cetak_dikoreksi_id`='" + txt_pekerja_koreksi_id.getText() + "',"
                + "`cetak_dikoreksi_grup`=(SELECT `tb_bagian`.`nama_bagian` FROM `tb_karyawan` LEFT JOIN `tb_bagian` ON `tb_karyawan`.`kode_bagian` = `tb_bagian`.`kode_bagian` WHERE `tb_karyawan`.`id_pegawai` = '" + txt_pekerja_koreksi_id.getText() + "'),"
                + "`cetak_dikoreksi_level`=(SELECT `level_gaji` FROM `tb_karyawan` WHERE `id_pegawai` = '" + txt_pekerja_koreksi_id.getText() + "'),"
                + "`cetak_mangkok`='" + txt_mk.getText() + "',"
                + "`cetak_pecah`='" + txt_mk_pecah.getText() + "',"
                + "`cetak_flat`='" + txt_flat.getText() + "',"
                + "`cetak_jidun`='" + txt_jidun.getText() + "',"
                + "`cetak_jidun_real`='" + txt_jidun_real.getText() + "',"
                + "`admin_cetak`='" + txt_admin.getText() + "' "
                + "WHERE `no_laporan_produksi`='" + label_no_lp.getText() + "'";
        
        try {
            Utility.db.getConnection().createStatement();
            if (total_cetak == total_keping) {
                if ((Utility.db.getStatement().executeUpdate(Query)) == 1) {
                    JOptionPane.showMessageDialog(this, "perubahan data berhasil disimpan");
                    this.dispose();
                    JPanel_DataCetak.button_search_cetak.doClick();
                }
            } else {
                JOptionPane.showMessageDialog(this, "failed!, jumlah keping cetak tidak sama dengan jumlah keping LP\nSilahkan cek kembali, Terima kasih !");
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_saveActionPerformed

    private void button_pick_diterimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pick_diterimaActionPerformed
        // TODO add your handling code here:
        Browse_Karyawan dialog = new Browse_Karyawan(new javax.swing.JFrame(), true, null);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);

        int x = Browse_Karyawan.table_list_karyawan.getSelectedRow();
        if (x != -1) {
            txt_diterima.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 1).toString());
        }
    }//GEN-LAST:event_button_pick_diterimaActionPerformed

    private void button_pick_diserahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pick_diserahkanActionPerformed
        // TODO add your handling code here:
        Browse_Karyawan dialog = new Browse_Karyawan(new javax.swing.JFrame(), true, null);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);

        int x = Browse_Karyawan.table_list_karyawan.getSelectedRow();
        if (x != -1) {
            txt_diserahkan.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 1).toString());
        }
    }//GEN-LAST:event_button_pick_diserahkanActionPerformed

    private void button_pilih_pekerja_cetak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pilih_pekerja_cetak2ActionPerformed
        // TODO add your handling code here:
        Browse_Karyawan dialog = new Browse_Karyawan(new javax.swing.JFrame(), true, null);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);

        int x = Browse_Karyawan.table_list_karyawan.getSelectedRow();
        if (x != -1) {
            String id = Browse_Karyawan.table_list_karyawan.getValueAt(x, 0).toString();
            String nama = Browse_Karyawan.table_list_karyawan.getValueAt(x, 1).toString();
            txt_pekerja_cetak2_id.setText(id);
            txt_pekerja_cetak2_nama.setText(nama);
        }
    }//GEN-LAST:event_button_pilih_pekerja_cetak2ActionPerformed

    private void button_pick_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pick_adminActionPerformed
        // TODO add your handling code here:
        Browse_Karyawan dialog = new Browse_Karyawan(new javax.swing.JFrame(), true, null);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);

        int x = Browse_Karyawan.table_list_karyawan.getSelectedRow();
        if (x != -1) {
            txt_admin.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 1).toString());
        }
    }//GEN-LAST:event_button_pick_adminActionPerformed

    private void button_pick_pekerja_koreksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pick_pekerja_koreksiActionPerformed
        // TODO add your handling code here:
        Browse_Karyawan dialog = new Browse_Karyawan(new javax.swing.JFrame(), true, null);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);

        int x = Browse_Karyawan.table_list_karyawan.getSelectedRow();
        if (x != -1) {
            txt_pekerja_koreksi_id.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 0).toString());
            txt_pekerja_koreksi_nama.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 1).toString());
        }
    }//GEN-LAST:event_button_pick_pekerja_koreksiActionPerformed

    private void button_pilih_pekerja_cetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pilih_pekerja_cetak1ActionPerformed
        // TODO add your handling code here:
        String filter_tgl = "AND DATE(`att_log`.`scan_date`) = CURRENT_DATE()";
        Browse_Karyawan dialog = new Browse_Karyawan(new javax.swing.JFrame(), true, filter_tgl);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);

        int x = Browse_Karyawan.table_list_karyawan.getSelectedRow();
        if (x != -1) {
            txt_pekerja_cetak1_id.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 0).toString());
            txt_pekerja_cetak1_nama.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 1).toString());
        }
    }//GEN-LAST:event_button_pilih_pekerja_cetak1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_tgl_masuk;
    private com.toedter.calendar.JDateChooser Date_tgl_selesai;
    private javax.swing.JButton button_pick_admin;
    private javax.swing.JButton button_pick_diserahkan;
    private javax.swing.JButton button_pick_diterima;
    private javax.swing.JButton button_pick_pekerja_koreksi;
    private javax.swing.JButton button_pilih_pekerja_cetak1;
    private javax.swing.JButton button_pilih_pekerja_cetak2;
    private javax.swing.JButton button_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_no_lp;
    private javax.swing.JLabel label_total_keping;
    private javax.swing.JTextField txt_admin;
    private javax.swing.JTextField txt_diserahkan;
    private javax.swing.JTextField txt_diterima;
    private javax.swing.JTextField txt_flat;
    private javax.swing.JTextField txt_jidun;
    private javax.swing.JTextField txt_jidun_real;
    private javax.swing.JTextField txt_mk;
    private javax.swing.JTextField txt_mk_pecah;
    private javax.swing.JTextField txt_pekerja_cetak1_id;
    private javax.swing.JTextField txt_pekerja_cetak1_nama;
    private javax.swing.JTextField txt_pekerja_cetak2_id;
    private javax.swing.JTextField txt_pekerja_cetak2_nama;
    private javax.swing.JTextField txt_pekerja_koreksi_id;
    private javax.swing.JTextField txt_pekerja_koreksi_nama;
    // End of variables declaration//GEN-END:variables
}
