package waleta_system.Panel_produksi;

import waleta_system.Class.Utility;

import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import waleta_system.Browse_Karyawan;

public class JDialog_Terima_LP_F2 extends javax.swing.JDialog {

    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date date = new Date();
    PreparedStatement pst;
    String sql = null;
    ResultSet rs;

    public JDialog_Terima_LP_F2(java.awt.Frame parent, boolean modal, String lp) {
        super(parent, modal);
        initComponents();
        label_title_terima_lp.setText("Terima LP Masuk F2");
        txt_no_lp.setText(lp);
        this.setResizable(false);
    }

    public void input_f2() {
        try {
            Boolean Check = true;
            if (txt_no_lp.getText().toUpperCase().contains("WL-")) {
                Date tgl_selesai_cetak = null;
                String cetak_diserahkan = null, lp_cetak = null;
                sql = "SELECT `no_laporan_produksi`, `tgl_selesai_cetak`, `cetak_diserahkan` FROM `tb_cetak` WHERE `no_laporan_produksi` = '" + txt_no_lp.getText() + "'";
                rs = Utility.db.getStatement().executeQuery(sql);
                if (rs.next()) {
                    lp_cetak = rs.getString("no_laporan_produksi");
                    tgl_selesai_cetak = rs.getDate("tgl_selesai_cetak");
                    cetak_diserahkan = rs.getString("cetak_diserahkan");
                }
                if (lp_cetak == null) {
                    JOptionPane.showMessageDialog(this, "LP belum Masuk Cetak !!");
                    Check = false;
                } else if ("-".equals(cetak_diserahkan) || tgl_selesai_cetak == null) {
                    JOptionPane.showMessageDialog(this, "LP Sedang di cetak, belum di setorkan!!");
                    Check = false;
                } else if (Date_terima.getDate().before(tgl_selesai_cetak)) {
                    JOptionPane.showMessageDialog(this, "Tanggal masuk F2 harus setelah tanggal setor cetak\ntanggal setor cetak LP " + txt_no_lp.getText() + " : " + new SimpleDateFormat("dd MMMM yyyy").format(tgl_selesai_cetak));
                    Check = false;
                }
            }

            if (Check) {
                String Query = "INSERT INTO `tb_finishing_2`(`no_laporan_produksi`, `tgl_masuk_f2`, `f2_diterima`) "
                        + "VALUES ('" + txt_no_lp.getText() + "','" + dateFormat.format(Date_terima.getDate()) + "','" + txt_diterima.getText() + "') "
                        + "ON DUPLICATE KEY UPDATE "
                        + "`tgl_masuk_f2`='" + dateFormat.format(Date_terima.getDate()) + "', `f2_diterima`='" + txt_diterima.getText() + "' ";
                if ((Utility.db.getStatement().executeUpdate(Query)) == 1) {
                    this.dispose();
                    JOptionPane.showMessageDialog(this, "Data Inserted !");
                }
            }
        } catch (HeadlessException | SQLException e) {
            Logger.getLogger(JDialog_Terima_LP_F2.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_title_terima_lp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_no_lp = new javax.swing.JTextField();
        button_save = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Date_terima = new com.toedter.calendar.JDateChooser();
        button_pick_diserahkan = new javax.swing.JButton();
        txt_diterima = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Terima LP Oleh Cabut");
        setResizable(false);

        label_title_terima_lp.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        label_title_terima_lp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title_terima_lp.setText("Terima LP");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("No. Laporan Produksi :");

        txt_no_lp.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_no_lp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_no_lpKeyTyped(evt);
            }
        });

        button_save.setBackground(new java.awt.Color(255, 255, 255));
        button_save.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        button_cancel.setBackground(new java.awt.Color(255, 255, 255));
        button_cancel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_cancel.setText("Cancel");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("Tanggal Masuk :");

        Date_terima.setBackground(new java.awt.Color(255, 255, 255));
        Date_terima.setDateFormatString("dd MMMM yyyy");
        Date_terima.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        Date_terima.setMaxSelectableDate(new Date());

        button_pick_diserahkan.setBackground(new java.awt.Color(255, 255, 255));
        button_pick_diserahkan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_pick_diserahkan.setText("...");
        button_pick_diserahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pick_diserahkanActionPerformed(evt);
            }
        });

        txt_diterima.setEditable(false);
        txt_diterima.setBackground(new java.awt.Color(255, 255, 255));
        txt_diterima.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setText("Diterima Oleh :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_title_terima_lp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_save))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_diterima)
                                .addGap(0, 0, 0)
                                .addComponent(button_pick_diserahkan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Date_terima, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(txt_no_lp, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_title_terima_lp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_no_lp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_terima, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_diterima, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_pick_diserahkan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_save, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_button_cancelActionPerformed

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        input_f2();
    }//GEN-LAST:event_button_saveActionPerformed

    private void button_pick_diserahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pick_diserahkanActionPerformed
        // TODO add your handling code here:
        String filter_tgl = "AND DATE(`att_log`.`scan_date`) = CURRENT_DATE()";
        Browse_Karyawan dialog = new Browse_Karyawan(new javax.swing.JFrame(), true, filter_tgl);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);
        int x = waleta_system.Browse_Karyawan.table_list_karyawan.getSelectedRow();
        if (x != -1) {
            txt_diterima.setText(waleta_system.Browse_Karyawan.table_list_karyawan.getValueAt(x, 1).toString());
        }
    }//GEN-LAST:event_button_pick_diserahkanActionPerformed

    private void txt_no_lpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_no_lpKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            char e = evt.getKeyChar();
            String c = String.valueOf(e);
            evt.consume();
            txt_no_lp.setText(txt_no_lp.getText() + c.toUpperCase());
        }
    }//GEN-LAST:event_txt_no_lpKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_terima;
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_pick_diserahkan;
    private javax.swing.JButton button_save;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel label_title_terima_lp;
    private javax.swing.JTextField txt_diterima;
    public javax.swing.JTextField txt_no_lp;
    // End of variables declaration//GEN-END:variables
}
