package waleta_system.Panel_produksi;

import waleta_system.Class.Utility;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import waleta_system.MainForm;

public class JDialog_Edit_Data_Kaki_F2 extends javax.swing.JDialog {

    String sql = null;
    ResultSet rs;
    Date date = new Date();
    int keping_awal = 0, jidun_awal = 0;
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    public void getdata() {
        try {
            int i = JPanel_Finishing2.Table_Data_f2.getSelectedRow();
            label_no_lp.setText(JPanel_Finishing2.Table_Data_f2.getValueAt(i, 0).toString());
            txt_tambah_kaki1.setText(JPanel_Finishing2.Table_Data_f2.getValueAt(i, 33).toString());
            txt_lp_kaki1.setText(JPanel_Finishing2.Table_Data_f2.getValueAt(i, 34).toString());
            txt_tambah_kaki2.setText(JPanel_Finishing2.Table_Data_f2.getValueAt(i, 35).toString());
            txt_lp_kaki2.setText(JPanel_Finishing2.Table_Data_f2.getValueAt(i, 36).toString());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(JDialog_Edit_Data_Cabut.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public JDialog_Edit_Data_Kaki_F2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setResizable(false);
        initComponents();
        getdata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txt_tambah_kaki1 = new javax.swing.JTextField();
        txt_lp_kaki1 = new javax.swing.JTextField();
        button_LPkaki2 = new javax.swing.JButton();
        button_LPkaki1 = new javax.swing.JButton();
        txt_lp_kaki2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_tambah_kaki2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        label_no_lp = new javax.swing.JLabel();
        button_save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bagian Finishing 2");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel31.setText("Tambah Kaki 2 :");

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel27.setText("Tambah Kaki 1 :");

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel28.setText("Grams");

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel32.setText("LP Kaki 2 :");

        txt_tambah_kaki1.setEditable(false);
        txt_tambah_kaki1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_tambah_kaki1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_tambah_kaki1.setText("0");

        txt_lp_kaki1.setEditable(false);
        txt_lp_kaki1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_lp_kaki1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_lp_kaki1.setText("-");

        button_LPkaki2.setBackground(new java.awt.Color(255, 255, 255));
        button_LPkaki2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_LPkaki2.setText("LP kaki 2");
        button_LPkaki2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_LPkaki2ActionPerformed(evt);
            }
        });

        button_LPkaki1.setBackground(new java.awt.Color(255, 255, 255));
        button_LPkaki1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_LPkaki1.setText("LP kaki 1");
        button_LPkaki1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_LPkaki1ActionPerformed(evt);
            }
        });

        txt_lp_kaki2.setEditable(false);
        txt_lp_kaki2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_lp_kaki2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_lp_kaki2.setText("-");

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel29.setText("Grams");

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel30.setText("LP Kaki 1 :");

        txt_tambah_kaki2.setEditable(false);
        txt_tambah_kaki2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_tambah_kaki2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_tambah_kaki2.setText("0");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Edit Kaki Finishing 2");

        label_no_lp.setBackground(new java.awt.Color(255, 255, 255));
        label_no_lp.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        label_no_lp.setText("NO. Laporan Produksi");

        button_save.setBackground(new java.awt.Color(255, 255, 255));
        button_save.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_lp_kaki1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_tambah_kaki1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28))
                            .addComponent(txt_lp_kaki2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_tambah_kaki2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_LPkaki1)
                            .addComponent(button_LPkaki2)))
                    .addComponent(jLabel1)
                    .addComponent(label_no_lp)
                    .addComponent(button_save, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_no_lp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tambah_kaki1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lp_kaki1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_LPkaki1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tambah_kaki2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lp_kaki2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_LPkaki2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_save)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        // TODO add your handling code here:
        Utility.db.getConnection();
        try {
            boolean check = true;
            Utility.db.getConnection().createStatement();
            String Query1 = "UPDATE `tb_finishing_2` SET "
                    + "`tambahan_kaki1`='" + txt_tambah_kaki1.getText() + "',"
                    + "`lp_kaki1`='" + txt_lp_kaki1.getText() + "',"
                    + "`tambahan_kaki2`='" + txt_tambah_kaki2.getText() + "',"
                    + "`lp_kaki2`='" + txt_lp_kaki2.getText() + "' "
                    + "WHERE `no_laporan_produksi`='" + label_no_lp.getText() + "'";

            if (check) {
                if ((Utility.db.getStatement().executeUpdate(Query1)) == 1) {
                    JOptionPane.showMessageDialog(this, "Data kaki " + label_no_lp.getText() + " berhasil diubah");
                    this.dispose();
                }
            }

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_saveActionPerformed

    private void button_LPkaki1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_LPkaki1ActionPerformed
        // TODO add your handling code here:
        JDialog_Choose_LPkaki dialog = new JDialog_Choose_LPkaki(new javax.swing.JFrame(), true);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);
        txt_lp_kaki1.setText(dialog.get_lpKaki());
        txt_tambah_kaki1.setText(Float.toString(dialog.get_gramKaki()));
    }//GEN-LAST:event_button_LPkaki1ActionPerformed

    private void button_LPkaki2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_LPkaki2ActionPerformed
        // TODO add your handling code here:
        JDialog_Choose_LPkaki dialog = new JDialog_Choose_LPkaki(new javax.swing.JFrame(), true);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);
        txt_lp_kaki2.setText(dialog.get_lpKaki());
        txt_tambah_kaki2.setText(Float.toString(dialog.get_gramKaki()));
    }//GEN-LAST:event_button_LPkaki2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_LPkaki1;
    private javax.swing.JButton button_LPkaki2;
    private javax.swing.JButton button_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_no_lp;
    private javax.swing.JTextField txt_lp_kaki1;
    private javax.swing.JTextField txt_lp_kaki2;
    private javax.swing.JTextField txt_tambah_kaki1;
    private javax.swing.JTextField txt_tambah_kaki2;
    // End of variables declaration//GEN-END:variables
}
