package waleta_system.Panel_produksi;

import waleta_system.Class.Utility;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import waleta_system.Browse_Karyawan;

public class JDialog_Terima_LP_Cabut_OM extends javax.swing.JDialog {

    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date date = new Date();
    PreparedStatement pst;
    String sql = null;
    ResultSet rs;
    Boolean Check = true;
    Date tgl_masuk = null;

    public JDialog_Terima_LP_Cabut_OM(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
    }

    public void input_cabut() {
        try {
            if (txt_no_lp.getText() == null || "".equals(txt_no_lp.getText())) {
                JOptionPane.showMessageDialog(this, "Silahkan masukan No Laporan Produksi !!");
                Check = false;
            } else if (txt_ketua_regu.getText() == null || "".equals(txt_ketua_regu.getText())) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih penerima LP !!");
                Check = false;
            } else {
                sql = "SELECT `tb_laporan_produksi`.`no_laporan_produksi`, `tb_laporan_produksi`.`ruangan`, `jenis_bulu_lp`, `tb_cabut`.`no_laporan_produksi` AS 'lp_cabut' \n"
                        + "FROM `tb_laporan_produksi` \n"
                        + "LEFT JOIN `tb_cabut` ON `tb_laporan_produksi`.`no_laporan_produksi` = `tb_cabut`.`no_laporan_produksi` \n"
                        + "WHERE `tb_laporan_produksi`.`no_laporan_produksi` = '" + txt_no_lp.getText() + "'";
                rs = Utility.db.getStatement().executeQuery(sql);
                if (rs.next()) {
                    if (rs.getString("lp_cabut") != null) {
                        JOptionPane.showMessageDialog(this, "No Laporan Produksi (" + txt_no_lp.getText() + ") sudah masuk !");
                        Check = false;
                    } else if (!rs.getString("ruangan").equals("C") && !rs.getString("ruangan").equals("CABUTO")) {//LP SUB
                        int dialogResult = JOptionPane.showConfirmDialog(this, "Ruangan bukan merupakan ruangan CABUTO\nApakah yakin ingin dilanjutkan?", "Warning", 0);
                        Check = dialogResult == JOptionPane.YES_OPTION;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No Laporan Produksi (" + txt_no_lp.getText() + ") tidak ditemukan !");
                    Check = false;
                }
            }

            if (Check) {
                String Query = "INSERT INTO `tb_cabut`(`no_laporan_produksi`, `ketua_regu`, `tgl_mulai_cabut`) "
                        + "VALUES ('" + txt_no_lp.getText() + "','" + txt_ketua_regu.getText() + "',CURRENT_DATE())";
                Utility.db.getConnection().createStatement();
                if ((Utility.db.getStatement().executeUpdate(Query)) == 1) {
                    JPanel_DataCabut.button_search_cabut.doClick();
                    this.dispose();
                    JOptionPane.showMessageDialog(this, "Data Inserted !");
                }
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            Logger.getLogger(JDialog_Terima_LP_Cabut_OM.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        button_cancel = new javax.swing.JButton();
        button_pick_ketua = new javax.swing.JButton();
        button_save = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        label_title_terima_lp = new javax.swing.JLabel();
        txt_ketua_regu = new javax.swing.JTextField();
        txt_tgl_masuk = new javax.swing.JTextField();
        txt_no_lp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Terima LP Oleh Cabut");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("No. Laporan Produksi :");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("Tanggal Terima :");

        button_cancel.setBackground(new java.awt.Color(255, 255, 255));
        button_cancel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_cancel.setText("Cancel");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        button_pick_ketua.setBackground(new java.awt.Color(255, 255, 255));
        button_pick_ketua.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_pick_ketua.setText("...");
        button_pick_ketua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pick_ketuaActionPerformed(evt);
            }
        });

        button_save.setBackground(new java.awt.Color(255, 255, 255));
        button_save.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setText("Ketua Grup Cabut :");

        label_title_terima_lp.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        label_title_terima_lp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title_terima_lp.setText("Terima LP CABUT OM");

        txt_ketua_regu.setEditable(false);
        txt_ketua_regu.setBackground(new java.awt.Color(255, 255, 255));
        txt_ketua_regu.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_tgl_masuk.setEditable(false);
        txt_tgl_masuk.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_no_lp.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_no_lp.setText("WL-");
        txt_no_lp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_no_lpFocusLost(evt);
            }
        });
        txt_no_lp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_no_lpKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(button_cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_save))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_title_terima_lp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_ketua_regu)
                                        .addGap(0, 0, 0)
                                        .addComponent(button_pick_ketua, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_no_lp, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_tgl_masuk))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_title_terima_lp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_no_lp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ketua_regu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_pick_ketua, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tgl_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_save, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_button_cancelActionPerformed

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        input_cabut();
    }//GEN-LAST:event_button_saveActionPerformed

    private void button_pick_ketuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pick_ketuaActionPerformed
        // TODO add your handling code here:
//        String filter_tgl = "AND DATE(`att_log`.`scan_date`) = CURRENT_DATE()";
        String filter_tgl = "";
        Browse_Karyawan dialog = new Browse_Karyawan(new javax.swing.JFrame(), true, filter_tgl);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);
        int x = waleta_system.Browse_Karyawan.table_list_karyawan.getSelectedRow();
        if (x != -1) {
            txt_ketua_regu.setText(waleta_system.Browse_Karyawan.table_list_karyawan.getValueAt(x, 1).toString());
        }
    }//GEN-LAST:event_button_pick_ketuaActionPerformed

    private void txt_no_lpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_no_lpKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            char e = evt.getKeyChar();
            String c = String.valueOf(e);
            evt.consume();
            txt_no_lp.setText(txt_no_lp.getText() + c.toUpperCase());
        }
    }//GEN-LAST:event_txt_no_lpKeyTyped

    private void txt_no_lpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_no_lpFocusLost
        try {
            // TODO add your handling code here:
            String id = null, cuci_diserahkan = null, no_lp = null, no_lp_cuci = null;
            sql = "SELECT `tb_laporan_produksi`.`no_laporan_produksi`, `jenis_bulu_lp`, `id_pegawai`, `cuci_diserahkan`, `tgl_masuk_cuci`, `tb_cuci`.`no_laporan_produksi` AS 'lp_cuci' "
                    + "FROM `tb_laporan_produksi` "
                    + "LEFT JOIN `tb_cuci` ON `tb_laporan_produksi`.`no_laporan_produksi` = `tb_cuci`.`no_laporan_produksi` \n"
                    + "WHERE `tb_laporan_produksi`.`no_laporan_produksi` = '" + txt_no_lp.getText() + "'";
            rs = Utility.db.getStatement().executeQuery(sql);
            if (rs.next()) {
                no_lp = rs.getString("lp_cuci");
                no_lp_cuci = rs.getString("lp_cuci");
                id = rs.getString("id_pegawai");
                cuci_diserahkan = rs.getString("cuci_diserahkan");
//                txt_tgl_masuk.setText(new SimpleDateFormat("dd MMMM yyyy").format(rs.getDate("tgl_masuk_cuci")));
//                tgl_masuk = rs.getDate("tgl_masuk_cuci");
                txt_tgl_masuk.setText(new SimpleDateFormat("dd MMMM yyyy").format(new Date()));
                tgl_masuk = new Date();
            }
            if (no_lp == null) {
                Check = false;
            } else if (no_lp_cuci == null) {
                JOptionPane.showMessageDialog(this, "LP belum Masuk Cuci !!");
                Check = false;
            } else if ("-".equals(cuci_diserahkan) || id == null) {
                JOptionPane.showMessageDialog(this, "LP Sedang di cuci, belum di setorkan!!");
                Check = false;
            } else {
                Check = true;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(JDialog_Terima_LP_Cabut_OM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_no_lpFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_pick_ketua;
    private javax.swing.JButton button_save;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_title_terima_lp;
    private javax.swing.JTextField txt_ketua_regu;
    private javax.swing.JTextField txt_no_lp;
    private javax.swing.JTextField txt_tgl_masuk;
    // End of variables declaration//GEN-END:variables
}
