package waleta_system.Panel_produksi;

import waleta_system.Class.Utility;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import waleta_system.Class.ColumnsAutoSizer;
import waleta_system.Class.ExportToExcel;
import waleta_system.MainForm;

public class JPanel_DataTRSela extends javax.swing.JPanel {

    String sql = null;
    ResultSet rs;
    Date date = new Date();
    DecimalFormat decimalFormat = new DecimalFormat();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    DefaultTableCellRenderer TableAlignment = new DefaultTableCellRenderer();

    public JPanel_DataTRSela() {
        initComponents();
        Table_Data_tr_sela.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting() && Table_Data_tr_sela.getSelectedRow() != -1) {
                    int i = Table_Data_tr_sela.getSelectedRow();
                    if (i != -1) {

                    }
                }
            }
        });
    }

    public void init() {
        refreshTable_TR_Sela();
    }

    public void refreshTable_TR_Sela() {
        try {
            decimalFormat.setMaximumFractionDigits(2);
            float total_kpg = 0, total_gram = 0;
            DefaultTableModel model = (DefaultTableModel) Table_Data_tr_sela.getModel();
            model.setRowCount(0);
            String filter_tanggal = "";
            if (Date1_tr_sela.getDate() != null && Date2_tr_sela.getDate() != null) {
                filter_tanggal = "AND `tanggal_tr_sela` BETWEEN '" + dateFormat.format(Date1_tr_sela.getDate()) + "' and '" + dateFormat.format(Date2_tr_sela.getDate()) + "'";
            }
            sql = "SELECT `nomor`, `tb_treatment_sela`.`no_laporan_produksi`, `kode_grade`, `jumlah_keping`, `berat_basah`, `tb_treatment_sela`.`id_pegawai`, `tb_karyawan`.`nama_pegawai`, `waktu`, `tanggal_tr_sela` \n"
                    + "FROM `tb_treatment_sela` \n"
                    + "LEFT JOIN `tb_laporan_produksi` ON `tb_treatment_sela`.`no_laporan_produksi` = `tb_laporan_produksi`.`no_laporan_produksi`\n"
                    + "LEFT JOIN `tb_karyawan` ON `tb_treatment_sela`.`id_pegawai` = `tb_karyawan`.`id_pegawai`\n"
                    + "WHERE `tb_treatment_sela`.`no_laporan_produksi` LIKE '%" + txt_search_no_lp.getText() + "%'"
                    + filter_tanggal
                    + "ORDER BY `tanggal_tr_sela` DESC";
            rs = Utility.db.getStatement().executeQuery(sql);
            Object[] row = new Object[15];
            while (rs.next()) {
                row[0] = rs.getInt("nomor");
                row[1] = rs.getString("no_laporan_produksi");
                row[2] = rs.getString("kode_grade");
                row[3] = rs.getFloat("jumlah_keping");
                row[4] = rs.getFloat("berat_basah");
                row[5] = rs.getString("id_pegawai");
                row[6] = rs.getString("nama_pegawai");
                row[7] = rs.getTime("waktu");
                row[8] = rs.getDate("tanggal_tr_sela");
                model.addRow(row);
                total_kpg = total_kpg + rs.getFloat("jumlah_keping");
                total_gram = total_gram + rs.getFloat("berat_basah");
            }
            ColumnsAutoSizer.sizeColumnsToFit(Table_Data_tr_sela);
            int rowData = Table_Data_tr_sela.getRowCount();
            label_total_data_tr_sela.setText(Integer.toString(rowData));
            label_total_kpg_tr_sela.setText(decimalFormat.format(total_kpg));
            label_total_gram_tr_sela.setText(decimalFormat.format(total_gram));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(JPanel_DataTRSela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Table_Data_tr_sela = new javax.swing.JTable();
        button_edit_tr_sela = new javax.swing.JButton();
        button_delete_tr_sela = new javax.swing.JButton();
        label_total_data_tr_sela = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        button_export_tr_sela = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        label_total_kpg_tr_sela = new javax.swing.JLabel();
        label_total_gram_tr_sela = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_search_no_lp = new javax.swing.JTextField();
        button_search_tr_sela = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Date1_tr_sela = new com.toedter.calendar.JDateChooser();
        Date2_tr_sela = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data TR Sela", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Table_Data_tr_sela.setAutoCreateRowSorter(true);
        Table_Data_tr_sela.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Table_Data_tr_sela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor Tr", "No LP", "Grade", "Keping", "Gram", "ID pekerja", "Nama Pekerja", "Durasi Treatment", "Tanggal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Data_tr_sela.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(Table_Data_tr_sela);

        button_edit_tr_sela.setBackground(new java.awt.Color(255, 255, 255));
        button_edit_tr_sela.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_edit_tr_sela.setText("Edit");
        button_edit_tr_sela.setEnabled(false);
        button_edit_tr_sela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_edit_tr_selaActionPerformed(evt);
            }
        });

        button_delete_tr_sela.setBackground(new java.awt.Color(255, 255, 255));
        button_delete_tr_sela.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_delete_tr_sela.setText("Delete");
        button_delete_tr_sela.setEnabled(false);
        button_delete_tr_sela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_delete_tr_selaActionPerformed(evt);
            }
        });

        label_total_data_tr_sela.setBackground(new java.awt.Color(255, 255, 255));
        label_total_data_tr_sela.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label_total_data_tr_sela.setText("TOTAL");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Total Data :");

        button_export_tr_sela.setBackground(new java.awt.Color(255, 255, 255));
        button_export_tr_sela.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_export_tr_sela.setText("Export to Excel");
        button_export_tr_sela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_export_tr_selaActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Total Keping :");

        label_total_kpg_tr_sela.setBackground(new java.awt.Color(255, 255, 255));
        label_total_kpg_tr_sela.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        label_total_kpg_tr_sela.setText("TOTAL");

        label_total_gram_tr_sela.setBackground(new java.awt.Color(255, 255, 255));
        label_total_gram_tr_sela.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        label_total_gram_tr_sela.setText("TOTAL");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Total Gram :");

        txt_search_no_lp.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_search_no_lp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_search_no_lpKeyPressed(evt);
            }
        });

        button_search_tr_sela.setBackground(new java.awt.Color(255, 255, 255));
        button_search_tr_sela.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_search_tr_sela.setText("Search");
        button_search_tr_sela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_search_tr_selaActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Laporan Produksi :");

        Date1_tr_sela.setBackground(new java.awt.Color(255, 255, 255));
        Date1_tr_sela.setDate(new Date(new Date().getTime()- (7 * 24 * 60 * 60 * 1000)));
        Date1_tr_sela.setDateFormatString("dd MMMM yyyy");
        Date1_tr_sela.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        Date2_tr_sela.setBackground(new java.awt.Color(255, 255, 255));
        Date2_tr_sela.setDate(new Date());
        Date2_tr_sela.setDateFormatString("dd MMMM yyyy");
        Date2_tr_sela.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("Tanggal :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_total_data_tr_sela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_total_kpg_tr_sela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_total_gram_tr_sela))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_search_no_lp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Date1_tr_sela, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Date2_tr_sela, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(button_search_tr_sela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_edit_tr_sela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_delete_tr_sela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_export_tr_sela)))
                        .addGap(0, 422, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search_no_lp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date1_tr_sela, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date2_tr_sela, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_search_tr_sela, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(button_edit_tr_sela, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_delete_tr_sela, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_export_tr_sela, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_total_data_tr_sela, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_total_kpg_tr_sela, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_total_gram_tr_sela, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_search_no_lpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_no_lpKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            refreshTable_TR_Sela();
        }
    }//GEN-LAST:event_txt_search_no_lpKeyPressed

    private void button_search_tr_selaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_search_tr_selaActionPerformed
        // TODO add your handling code here:
        refreshTable_TR_Sela();
    }//GEN-LAST:event_button_search_tr_selaActionPerformed

    private void button_delete_tr_selaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_delete_tr_selaActionPerformed
        // TODO add your handling code here:
        try {
            int j = Table_Data_tr_sela.getSelectedRow();
            if (j == -1) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data yang ingin di hapus !");
            } else {
                sql = "SELECT `no_laporan_produksi` FROM `tb_finishing_2` WHERE `tb_finishing_2`.`no_laporan_produksi` = '" + Table_Data_tr_sela.getValueAt(j, 0) + "'";
                rs = Utility.db.getStatement().executeQuery(sql);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Maaf tidak bisa hapus No LP ini karena sudah masuk F2, mohon hapus data F2 terlebih dahulu!");
                } else {
                    int dialogResult = JOptionPane.showConfirmDialog(this, "Yakin hapus data ini?", "Warning", 0);
                    if (dialogResult == JOptionPane.YES_OPTION) {
                        // delete code here
                        String Query = "DELETE FROM `tb_cetak` WHERE `tb_cetak`.`no_laporan_produksi` = '" + Table_Data_tr_sela.getValueAt(j, 0) + "'";
                        Utility.db.getConnection().createStatement();
                        if ((Utility.db.getStatement().executeUpdate(Query)) == 1) {
                            JOptionPane.showMessageDialog(this, "data deleted!");
                            refreshTable_TR_Sela();
                        } else {
                            JOptionPane.showMessageDialog(this, "Delete Failed!");
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_delete_tr_selaActionPerformed

    private void button_edit_tr_selaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_edit_tr_selaActionPerformed
        // TODO add your handling code here:
        try {
            int j = Table_Data_tr_sela.getSelectedRow();
            if (j == -1) {
                JOptionPane.showMessageDialog(this, "Please Select Row Data that you want to change !");
            } else {
                JDialog_Edit_Data_Cetak edit_cetak = new JDialog_Edit_Data_Cetak(new javax.swing.JFrame(), true);
                edit_cetak.pack();
                edit_cetak.setLocationRelativeTo(this);
                edit_cetak.setVisible(true);
                edit_cetak.setEnabled(true);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_edit_tr_selaActionPerformed

    private void button_export_tr_selaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_export_tr_selaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Table_Data_tr_sela.getModel();
        ExportToExcel.writeToExcel(model, jPanel1);
    }//GEN-LAST:event_button_export_tr_selaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date1_tr_sela;
    private com.toedter.calendar.JDateChooser Date2_tr_sela;
    public static javax.swing.JTable Table_Data_tr_sela;
    public static javax.swing.JButton button_delete_tr_sela;
    public static javax.swing.JButton button_edit_tr_sela;
    private javax.swing.JButton button_export_tr_sela;
    public static javax.swing.JButton button_search_tr_sela;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_total_data_tr_sela;
    private javax.swing.JLabel label_total_gram_tr_sela;
    private javax.swing.JLabel label_total_kpg_tr_sela;
    private javax.swing.JTextField txt_search_no_lp;
    // End of variables declaration//GEN-END:variables

}
