package waleta_system.RND;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import waleta_system.Class.ColumnsAutoSizer;
import waleta_system.Class.Utility;

public class JPanel_DataKaryawanATB extends javax.swing.JPanel {

    String sql = null;
    ResultSet rs;
    Date date = new Date();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    public JPanel_DataKaryawanATB() {
        initComponents();
    }

    public void init() {
        refreshTable();
        Table_pegawaiATB.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting() && Table_pegawaiATB.getSelectedRow() != -1) {
                    int i = Table_pegawaiATB.getSelectedRow();
                    txt_id_pegawai_atb.setText(Table_pegawaiATB.getValueAt(i, 0).toString());
                    try {
                        Date_masuk.setDate(dateFormat.parse(Table_pegawaiATB.getValueAt(i, 1).toString()));
                    } catch (Exception e) {
                    }
                    txt_R.setText(Table_pegawaiATB.getValueAt(i, 2).toString());
                    txt_T.setText(Table_pegawaiATB.getValueAt(i, 3).toString());
                    txt_D.setText(Table_pegawaiATB.getValueAt(i, 4).toString());
                    if (Table_pegawaiATB.getValueAt(i, 5) != null) {
                        txt_keterangan.setText(Table_pegawaiATB.getValueAt(i, 5).toString());
                    }
                }
            }
        });
    }

    public void refreshTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) Table_pegawaiATB.getModel();
            model.setRowCount(0);
            sql = "SELECT `id_pegawai_atb`, `tanggal_masuk`, `rpm`, `time`, `dinamo`, `keterangan` "
                    + "FROM `tb_karyawan_atb` "
                    + "WHERE `id_pegawai_atb` LIKE '%" + txt_search_id_pegawai_atb.getText() + "%'";
            rs = Utility.db.getStatement().executeQuery(sql);
            Object[] row = new Object[10];
            while (rs.next()) {
                row[0] = rs.getString("id_pegawai_atb");
                row[1] = rs.getDate("tanggal_masuk");
                row[2] = rs.getInt("rpm");
                row[3] = rs.getInt("time");
                row[4] = rs.getString("dinamo");
                row[5] = rs.getString("keterangan");
                model.addRow(row);
            }
            ColumnsAutoSizer.sizeColumnsToFit(Table_pegawaiATB);
            int rowData = Table_pegawaiATB.getRowCount();
            label_total_data_customer_baku.setText(Integer.toString(rowData));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(JPanel_DataKaryawanATB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_search_id_pegawai_atb = new javax.swing.JTextField();
        button_search = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        Table_pegawaiATB = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        label_total_data_customer_baku = new javax.swing.JLabel();
        jPanel_operation_customer = new javax.swing.JPanel();
        button_new_pegawai_atb = new javax.swing.JButton();
        button_edit_pegawai_atb = new javax.swing.JButton();
        button_clear = new javax.swing.JButton();
        button_delete_pegawai_atb = new javax.swing.JButton();
        txt_D = new javax.swing.JTextField();
        txt_T = new javax.swing.JTextField();
        label_nama_customer_baku = new javax.swing.JLabel();
        label_alamat_customer_baku = new javax.swing.JLabel();
        label_noTelp_customer_baku = new javax.swing.JLabel();
        label_nama_customer_baku1 = new javax.swing.JLabel();
        txt_id_pegawai_atb = new javax.swing.JTextField();
        txt_R = new javax.swing.JTextField();
        label_noTelp_customer_baku1 = new javax.swing.JLabel();
        txt_keterangan = new javax.swing.JTextField();
        label_nama_customer_baku2 = new javax.swing.JLabel();
        Date_masuk = new com.toedter.calendar.JDateChooser();
        button_print_1_id_karyawan = new javax.swing.JButton();
        button_print_semua_id_karyawan = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Data Karyawan ATB");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("ID Pegawai ATB :");

        txt_search_id_pegawai_atb.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_search_id_pegawai_atb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_search_id_pegawai_atbKeyPressed(evt);
            }
        });

        button_search.setBackground(new java.awt.Color(255, 255, 255));
        button_search.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_search.setText("Search");
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });

        Table_pegawaiATB.setAutoCreateRowSorter(true);
        Table_pegawaiATB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pegawai ATB", "Tgl Masuk", "R", "T", "D", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_pegawaiATB.getTableHeader().setReorderingAllowed(false);
        jScrollPane8.setViewportView(Table_pegawaiATB);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Total Data :");

        label_total_data_customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        label_total_data_customer_baku.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label_total_data_customer_baku.setText("TOTAL");

        jPanel_operation_customer.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_operation_customer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_operation_customer.setName("aah"); // NOI18N

        button_new_pegawai_atb.setBackground(new java.awt.Color(255, 255, 255));
        button_new_pegawai_atb.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_new_pegawai_atb.setText("New");
        button_new_pegawai_atb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_new_pegawai_atbActionPerformed(evt);
            }
        });

        button_edit_pegawai_atb.setBackground(new java.awt.Color(255, 255, 255));
        button_edit_pegawai_atb.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_edit_pegawai_atb.setText("Edit");
        button_edit_pegawai_atb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_edit_pegawai_atbActionPerformed(evt);
            }
        });

        button_clear.setBackground(new java.awt.Color(255, 255, 255));
        button_clear.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_clear.setText("Clear Text");
        button_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clearActionPerformed(evt);
            }
        });

        button_delete_pegawai_atb.setBackground(new java.awt.Color(255, 255, 255));
        button_delete_pegawai_atb.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_delete_pegawai_atb.setText("Delete");
        button_delete_pegawai_atb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_delete_pegawai_atbActionPerformed(evt);
            }
        });

        txt_D.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_T.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        label_nama_customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        label_nama_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_nama_customer_baku.setText("ID Pegawai ATB :");

        label_alamat_customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        label_alamat_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_alamat_customer_baku.setText("T :");

        label_noTelp_customer_baku.setBackground(new java.awt.Color(255, 255, 255));
        label_noTelp_customer_baku.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_noTelp_customer_baku.setText("D :");

        label_nama_customer_baku1.setBackground(new java.awt.Color(255, 255, 255));
        label_nama_customer_baku1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_nama_customer_baku1.setText("Tanggal Masuk :");

        txt_id_pegawai_atb.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_R.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        label_noTelp_customer_baku1.setBackground(new java.awt.Color(255, 255, 255));
        label_noTelp_customer_baku1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_noTelp_customer_baku1.setText("Keterangan :");

        txt_keterangan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        label_nama_customer_baku2.setBackground(new java.awt.Color(255, 255, 255));
        label_nama_customer_baku2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_nama_customer_baku2.setText("R :");

        Date_masuk.setBackground(new java.awt.Color(255, 255, 255));
        Date_masuk.setDateFormatString("dd MMM yyyy");
        Date_masuk.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel_operation_customerLayout = new javax.swing.GroupLayout(jPanel_operation_customer);
        jPanel_operation_customer.setLayout(jPanel_operation_customerLayout);
        jPanel_operation_customerLayout.setHorizontalGroup(
            jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_operation_customerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_operation_customerLayout.createSequentialGroup()
                        .addComponent(label_nama_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id_pegawai_atb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_operation_customerLayout.createSequentialGroup()
                        .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nama_customer_baku1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_alamat_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_nama_customer_baku2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_T, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txt_R, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(Date_masuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel_operation_customerLayout.createSequentialGroup()
                        .addComponent(label_noTelp_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_D, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_operation_customerLayout.createSequentialGroup()
                        .addComponent(label_noTelp_customer_baku1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_operation_customerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_new_pegawai_atb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_edit_pegawai_atb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_delete_pegawai_atb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_clear)
                .addContainerGap())
        );
        jPanel_operation_customerLayout.setVerticalGroup(
            jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_operation_customerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id_pegawai_atb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nama_customer_baku1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama_customer_baku2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_R, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_alamat_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_T, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_D, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_noTelp_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_noTelp_customer_baku1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_edit_pegawai_atb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_new_pegawai_atb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_delete_pegawai_atb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        button_print_1_id_karyawan.setBackground(new java.awt.Color(255, 255, 255));
        button_print_1_id_karyawan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_print_1_id_karyawan.setText("Print 1 ID Karyawan");
        button_print_1_id_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_print_1_id_karyawanActionPerformed(evt);
            }
        });

        button_print_semua_id_karyawan.setBackground(new java.awt.Color(255, 255, 255));
        button_print_semua_id_karyawan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_print_semua_id_karyawan.setText("Print Semua ID Karyawan");
        button_print_semua_id_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_print_semua_id_karyawanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_operation_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_search_id_pegawai_atb, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_total_data_customer_baku, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_print_1_id_karyawan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_print_semua_id_karyawan)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search_id_pegawai_atb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_total_data_customer_baku)
                    .addComponent(jLabel12)
                    .addComponent(button_print_1_id_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_print_semua_id_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel_operation_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_search_id_pegawai_atbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_id_pegawai_atbKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            refreshTable();
        }
    }//GEN-LAST:event_txt_search_id_pegawai_atbKeyPressed

    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_searchActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_button_searchActionPerformed

    private void button_new_pegawai_atbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_new_pegawai_atbActionPerformed
        // TODO add your handling code here:
        Boolean Check = true;
        try {
            if (txt_id_pegawai_atb.getText() == null || txt_id_pegawai_atb.getText().equals("")
                    || txt_R.getText() == null || txt_R.getText().equals("")
                    || txt_T.getText() == null || txt_T.getText().equals("")
                    || txt_D.getText() == null || txt_D.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Silahkan Lengkapi data diatas");
                Check = false;
            }

            if (Check) {
                String Query = "INSERT INTO `tb_karyawan_atb`(`id_pegawai_atb`, `tanggal_masuk`, `rpm`, `time`, `dinamo`, `keterangan`)"
                        + "VALUES ('" + txt_id_pegawai_atb.getText() + "', '" + dateFormat.format(Date_masuk.getDate()) + "', '" + txt_R.getText() + "', '" + txt_T.getText() + "', '" + txt_D.getText() + "', '" + txt_keterangan.getText() + "')";
                if ((Utility.db.getStatement().executeUpdate(Query)) == 1) {
                    JOptionPane.showMessageDialog(this, "data SAVED!");
                    refreshTable();
                    button_clear.doClick();
                } else {
                    JOptionPane.showMessageDialog(this, "FAILED!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            Logger.getLogger(JPanel_DataKaryawanATB.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_new_pegawai_atbActionPerformed

    private void button_edit_pegawai_atbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_edit_pegawai_atbActionPerformed
        // TODO add your handling code here:
        int j = Table_pegawaiATB.getSelectedRow();
        Boolean Check = true;
        try {
            if (j == -1) {
                JOptionPane.showMessageDialog(this, "Silahkan klik data pada tabel terlebih dulu!");
            } else {
                if (txt_id_pegawai_atb.getText() == null || txt_id_pegawai_atb.getText().equals("")
                        || Date_masuk.getDate() == null
                        || txt_R.getText() == null || txt_R.getText().equals("")
                        || txt_T.getText() == null || txt_T.getText().equals("")
                        || txt_D.getText() == null || txt_D.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Silahkan Lengkapi data diatas");
                    Check = false;
                }
                if (Check) {
                    String Query = "UPDATE `tb_karyawan_atb` SET "
                            + "`id_pegawai_atb` = '" + txt_id_pegawai_atb.getText() + "', "
                            + "`tanggal_masuk` = '" + dateFormat.format(Date_masuk.getDate()) + "', "
                            + "`rpm` = '" + txt_R.getText() + "', "
                            + "`time` = '" + txt_T.getText() + "', "
                            + "`dinamo` = '" + txt_D.getText() + "', "
                            + "`keterangan` = '" + txt_keterangan.getText() + "' "
                            + "WHERE `id_pegawai_atb` = '" + Table_pegawaiATB.getValueAt(j, 0).toString() + "'";
                    if ((Utility.db.getStatement().executeUpdate(Query)) >= 0) {
                        JOptionPane.showMessageDialog(this, "data SAVED!");
                        refreshTable();
                        button_clear.doClick();
                    } else {
                        JOptionPane.showMessageDialog(this, "FAILED!");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            Logger.getLogger(JPanel_DataKaryawanATB.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_edit_pegawai_atbActionPerformed

    private void button_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clearActionPerformed
        // TODO add your handling code here:
        txt_id_pegawai_atb.setText(null);
        txt_R.setText(null);
        txt_T.setText(null);
        txt_D.setText(null);
        txt_keterangan.setText(null);
    }//GEN-LAST:event_button_clearActionPerformed

    private void button_delete_pegawai_atbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_delete_pegawai_atbActionPerformed
        // TODO add your handling code here:
        try {
            int j = Table_pegawaiATB.getSelectedRow();
            if (j == -1) {
                JOptionPane.showMessageDialog(this, "Silahkan klik data pada tabel terlebih dulu!");
            } else {
                int dialogResult = JOptionPane.showConfirmDialog(this, "Yakin akan hapus data ini?", "Warning", 0);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    // delete code here
                    String Query = "DELETE FROM `tb_karyawan_atb` WHERE `id_pegawai_atb` = '" + Table_pegawaiATB.getValueAt(j, 0).toString() + "'";
                    if ((Utility.db.getStatement().executeUpdate(Query)) == 1) {
                        JOptionPane.showMessageDialog(this, "data SAVED!");
                        refreshTable();
                        button_clear.doClick();
                    } else {
                        JOptionPane.showMessageDialog(this, "FAILED!");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            Logger.getLogger(JPanel_DataKaryawanATB.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_delete_pegawai_atbActionPerformed

    private void button_print_1_id_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_print_1_id_karyawanActionPerformed
        // TODO add your handling code here:
        int j = Table_pegawaiATB.getSelectedRow();
        if (j == -1) {
            JOptionPane.showMessageDialog(this, "Silahkan klik data pada tabel terlebih dulu!");
        } else {
            try {
                String id_pegawai = "'" + Table_pegawaiATB.getValueAt(j, 0).toString() + "'";
                String Query = "SELECT `id_pegawai_atb`, `tanggal_masuk`, `rpm`, `time`, `dinamo`, `keterangan` FROM `tb_karyawan_atb` "
                        + "WHERE `id_pegawai_atb` IN (" + id_pegawai + ")";

                JRDesignQuery newQuery = new JRDesignQuery();
                newQuery.setText(Query);
                //String REPORT = "C:\\Users\\Z475\\Documents\\NetBeansProjects\\JavaApplication5\\src\\javaapplication5\\report1.jrxml";
                JasperDesign JASP_DESIGN = JRXmlLoader.load("Report\\Label_Karyawan_ATB.jrxml");
                JASP_DESIGN.setQuery(newQuery);

                JasperReport JASP_REP = JasperCompileManager.compileReport(JASP_DESIGN);
                JasperPrint JASP_PRINT = JasperFillManager.fillReport(JASP_REP, null, Utility.db.getConnection());
                JasperViewer.viewReport(JASP_PRINT, false);//isExitOnClose (false)
            } catch (JRException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                Logger.getLogger(JPanel_DataKaryawanATB.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_button_print_1_id_karyawanActionPerformed

    private void button_print_semua_id_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_print_semua_id_karyawanActionPerformed
        // TODO add your handling code here:
        try {
            String id_pegawai = "";
            for (int i = 0; i < Table_pegawaiATB.getRowCount(); i++) {
                if (i != 0) {
                    id_pegawai = id_pegawai + ", ";
                }
                id_pegawai = id_pegawai + "'" + Table_pegawaiATB.getValueAt(i, 0).toString() + "'";
            }
            String Query = "SELECT `id_pegawai_atb`, `tanggal_masuk`, `rpm`, `time`, `dinamo`, `keterangan` FROM `tb_karyawan_atb` "
                    + "WHERE `id_pegawai_atb` IN (" + id_pegawai + ")";

            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(Query);
            //String REPORT = "C:\\Users\\Z475\\Documents\\NetBeansProjects\\JavaApplication5\\src\\javaapplication5\\report1.jrxml";
            JasperDesign JASP_DESIGN = JRXmlLoader.load("Report\\Label_Karyawan_ATB.jrxml");
            JASP_DESIGN.setQuery(newQuery);

            JasperReport JASP_REP = JasperCompileManager.compileReport(JASP_DESIGN);
            JasperPrint JASP_PRINT = JasperFillManager.fillReport(JASP_REP, null, Utility.db.getConnection());
            JasperViewer.viewReport(JASP_PRINT, false);//isExitOnClose (false)
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            Logger.getLogger(JPanel_DataKaryawanATB.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_print_semua_id_karyawanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_masuk;
    private javax.swing.JTable Table_pegawaiATB;
    private javax.swing.JButton button_clear;
    public javax.swing.JButton button_delete_pegawai_atb;
    public javax.swing.JButton button_edit_pegawai_atb;
    public javax.swing.JButton button_new_pegawai_atb;
    public javax.swing.JButton button_print_1_id_karyawan;
    public javax.swing.JButton button_print_semua_id_karyawan;
    private javax.swing.JButton button_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_operation_customer;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel label_alamat_customer_baku;
    private javax.swing.JLabel label_nama_customer_baku;
    private javax.swing.JLabel label_nama_customer_baku1;
    private javax.swing.JLabel label_nama_customer_baku2;
    private javax.swing.JLabel label_noTelp_customer_baku;
    private javax.swing.JLabel label_noTelp_customer_baku1;
    private javax.swing.JLabel label_total_data_customer_baku;
    private javax.swing.JTextField txt_D;
    private javax.swing.JTextField txt_R;
    private javax.swing.JTextField txt_T;
    private javax.swing.JTextField txt_id_pegawai_atb;
    private javax.swing.JTextField txt_keterangan;
    private javax.swing.JTextField txt_search_id_pegawai_atb;
    // End of variables declaration//GEN-END:variables
}
