/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package waleta_system.Maintenance.view.lantai;

import javax.swing.JOptionPane;
import waleta_system.Maintenance.controller.LantaiDAO;
import waleta_system.Maintenance.controller.PathHelper;
import waleta_system.Maintenance.model.Lantai;
import waleta_system.Maintenance.view.MainFrame_Maintenance;

/**
 *
 * @author User
 */
public class TambahUbahLantaiJDialog extends javax.swing.JDialog {

    private MainFrame_Maintenance mainJFrame;
    private String idLantaiUpdate;
    public enum KategoriDialog {
        TAMBAH,
        UBAH
    }
    private KategoriDialog kategoriDialog;

    /**
     * Creates new form TambahLantaiJDialog
     */
    public TambahUbahLantaiJDialog(java.awt.Frame parent, boolean modal, MainFrame_Maintenance mainJFrame, KategoriDialog kategoriDialog, Lantai lantai) {
        this(parent, modal, mainJFrame, kategoriDialog);
        idLantaiUpdate = lantai.getIdLantai();
        jTextFieldNamaLantai.setText(lantai.getNamaLantai());
        jTextFieldGambar.setText(lantai.getGambar());
        javax.swing.ImageIcon currImageIcon;
        if (lantai.getGambar() == null) {
            currImageIcon = null;
        } else {
            currImageIcon = new javax.swing.ImageIcon((PathHelper.path + "lantai/" + lantai.getGambar()));
        }
        jLabelPratinjauGambar.setIcon(currImageIcon);
    }

    public TambahUbahLantaiJDialog(java.awt.Frame parent, boolean modal, MainFrame_Maintenance mainJFrame, KategoriDialog kategoriDialog) {
        super(parent, modal);
        initComponents();
        this.mainJFrame = mainJFrame;
        this.kategoriDialog = kategoriDialog;
        switch (kategoriDialog) {
            case TAMBAH:
                setTitle("Waleta Maintenance - Waleta Maintenance - Tambah Lantai");
                break;
            case UBAH:
                setTitle("Waleta Maintenance - Waleta Maintenance - Ubah Lantai");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserGambar = new javax.swing.JFileChooser();
        jButtonSimpan = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldNamaLantai = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldGambar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelPratinjauGambar = new javax.swing.JLabel();
        jButtonPilihBerkas = new javax.swing.JButton();

        jFileChooserGambar.setDialogTitle("Pilih Berkas Gambar");
        jFileChooserGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserGambarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Waleta Maintenance - Tambah Lantai");

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jButtonBatal.setText("Batal");
        jButtonBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setPreferredSize(new java.awt.Dimension(500, 346));

        jLabel2.setText("Nama Lantai");

        jLabel3.setText("Gambar");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pratinjau Gambar"));

        jLabelPratinjauGambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane1.setViewportView(jLabelPratinjauGambar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonPilihBerkas.setText("Pilih Berkas");
        jButtonPilihBerkas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPilihBerkas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPilihBerkasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldGambar, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPilihBerkas))
                            .addComponent(jTextFieldNamaLantai))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNamaLantai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPilihBerkas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 417, Short.MAX_VALUE)
                        .addComponent(jButtonBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSimpan)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSimpan)
                    .addComponent(jButtonBatal))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(546, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPilihBerkasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPilihBerkasActionPerformed
        jFileChooserGambar.showDialog(TambahUbahLantaiJDialog.this, "Pilih");
    }//GEN-LAST:event_jButtonPilihBerkasActionPerformed

    private void jFileChooserGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserGambarActionPerformed
        jTextFieldGambar.setText(jFileChooserGambar.getSelectedFile().getAbsolutePath());
        javax.swing.ImageIcon currImageIcon;
        if (jFileChooserGambar.getSelectedFile().getAbsolutePath() == null) {
            currImageIcon = null;
        } else {
            currImageIcon = new javax.swing.ImageIcon(jFileChooserGambar.getSelectedFile().getAbsolutePath());
        }
        jLabelPratinjauGambar.setIcon(currImageIcon);
    }//GEN-LAST:event_jFileChooserGambarActionPerformed

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        switch (kategoriDialog) {
            case TAMBAH:
                try {
                    Lantai newLantai = new Lantai(jTextFieldNamaLantai.getText(), jTextFieldGambar.getText());
                    if(new LantaiDAO().insert(mainJFrame, newLantai))
                    {
                        JOptionPane.showMessageDialog(TambahUbahLantaiJDialog.this, "Sukses menyimpan lantai", "Sukses Simpan", JOptionPane.INFORMATION_MESSAGE);
                        mainJFrame.refreshLantai();
                        dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(TambahUbahLantaiJDialog.this, "Gagal menyimpan lantai", "Sukses Simpan", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(TambahUbahLantaiJDialog.this, "Gagal menyimpan lantai: "+e.getLocalizedMessage(), "Gagal Simpan", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case UBAH:
                try {
                    Lantai newLantai = new Lantai(jTextFieldNamaLantai.getText(), jTextFieldGambar.getText());
                    if(new LantaiDAO().update(mainJFrame, idLantaiUpdate, newLantai))
                    {
                        JOptionPane.showMessageDialog(TambahUbahLantaiJDialog.this, "Sukses menyimpan lantai", "Sukses Simpan", JOptionPane.INFORMATION_MESSAGE);
                        mainJFrame.refreshLantai();
                        dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(TambahUbahLantaiJDialog.this, "Gagal menyimpan lantai", "Sukses Simpan", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(TambahUbahLantaiJDialog.this, "Gagal menyimpan lantai: "+e.getLocalizedMessage(), "Gagal Simpan", JOptionPane.ERROR_MESSAGE);
                }
                break;
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonPilihBerkas;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JFileChooser jFileChooserGambar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelPratinjauGambar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldGambar;
    private javax.swing.JTextField jTextFieldNamaLantai;
    // End of variables declaration//GEN-END:variables
}
