package waleta_system.SubWaleta;

import waleta_system.Class.Utility;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class JDialog_karyawan_keluar_masuk_sub extends javax.swing.JDialog {

    String sql = null;
    ResultSet rs;
    PreparedStatement pst;
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String id = null;
    Date tanggal_masuk = null;
    String status;

    public JDialog_karyawan_keluar_masuk_sub(java.awt.Frame parent, boolean modal, String id, String status) {
        super(parent, modal);
        initComponents();
        this.id = id;
        this.status = status;
        try {
            Utility.db_sub.connect();
            sql = "SELECT `id_pegawai`, `nama_pegawai`, `tanggal_masuk`, `tanggal_keluar` "
                    + "FROM `tb_karyawan` "
                    + "WHERE `id_pegawai` = '" + id + "'";
            rs = Utility.db_sub.getStatement().executeQuery(sql);
            if (rs.next()) {
                label_id.setText(rs.getString("id_pegawai"));
                label_nama.setText(rs.getString("nama_pegawai"));
                tanggal_masuk = rs.getDate("tanggal_masuk");
                if (status.equals("keluar")) {
                    label_tanggal.setText("Tanggal Keluar :");
                    Date_Tanggal.setDate(rs.getDate("tanggal_keluar"));
                } else {
                    label_tanggal.setText("Tanggal Masuk :");
                    Date_Tanggal.setDate(rs.getDate("tanggal_masuk"));
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(JDialog_karyawan_keluar_masuk_sub.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void keluar() {
        try {
            Utility.db_sub.connect();
            if (tanggal_masuk.after(Date_Tanggal.getDate())) {
                JOptionPane.showMessageDialog(this, "Maaf tanggal keluar tidak bisa lebih muda dari tanggal masuk!");
            } else {
                String sql_update = "UPDATE `tb_karyawan` SET "
                        + "`tanggal_keluar`='" + dateFormat.format(Date_Tanggal.getDate()) + "', "
                        + "`status`='OUT-SUB' "
                        + "WHERE `id_pegawai` = '" + id + "'";
                Utility.db_sub.getConnection().createStatement();
                if ((Utility.db_sub.getStatement().executeUpdate(sql_update)) == 1) {
                    JOptionPane.showMessageDialog(this, "Data Saved, Harap menghapus data user pada mesin absen fingerspot!");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "failed");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(JDialog_karyawan_keluar_masuk_sub.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void masuk() {
        try {
            Utility.db_sub.connect();
            sql = "UPDATE `tb_karyawan` SET "
                    + "`tanggal_masuk`='" + dateFormat.format(Date_Tanggal.getDate()) + "', "
                    + "`tanggal_keluar`=NULL, "
                    + "`status`='IN-SUB' "
                    + "WHERE `id_pegawai` = '" + id + "'";
            Utility.db_sub.getConnection().createStatement();
            if ((Utility.db_sub.getStatement().executeUpdate(sql)) == 1) {
                JOptionPane.showMessageDialog(this, "success");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "failed");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(JDialog_karyawan_keluar_masuk_sub.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_tanggal = new javax.swing.JLabel();
        Date_Tanggal = new com.toedter.calendar.JDateChooser();
        button_ok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_nama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        label_tanggal.setBackground(new java.awt.Color(255, 255, 255));
        label_tanggal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        label_tanggal.setText("Tanggal  Keluar :");

        Date_Tanggal.setBackground(new java.awt.Color(255, 255, 255));
        Date_Tanggal.setDate(new Date());
        Date_Tanggal.setDateFormatString("dd MMM yyyy");
        Date_Tanggal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Date_Tanggal.setMaxSelectableDate(new Date());

        button_ok.setBackground(new java.awt.Color(255, 255, 255));
        button_ok.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        button_ok.setText("SAVE");
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("ID Pegawai :");

        label_id.setBackground(new java.awt.Color(255, 255, 255));
        label_id.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        label_id.setText("-");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Nama :");

        label_nama.setBackground(new java.awt.Color(255, 255, 255));
        label_nama.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        label_nama.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_ok)
                .addGap(10, 10, 10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Date_Tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(label_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_id, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Date_Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
        if (status.equals("keluar")) {
            keluar();
        } else {
            masuk();
        }
    }//GEN-LAST:event_button_okActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_Tanggal;
    private javax.swing.JButton button_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_tanggal;
    // End of variables declaration//GEN-END:variables
}
