package waleta_system.SubWaleta;

import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import waleta_system.Class.Utility;

public class JDialog_Edit_DataKaryawanSUB_Online extends javax.swing.JDialog {

    String sql = null;
    ResultSet rs;
    PreparedStatement pst;
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String imgPath = null;
    Boolean Check = true;
    String id_pegawai;
    Date today = new Date();

    public JDialog_Edit_DataKaryawanSUB_Online(java.awt.Frame parent, boolean modal, String ID_pegawai) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.id_pegawai = ID_pegawai;
        txt_id_pegawai.setText(ID_pegawai);
        try {
            Utility.db_sub.connect();
            ComboBox_bagian.removeAllItems();
            sql = "SELECT `kode_sub` FROM `tb_sub_waleta` WHERE 1";
            rs = Utility.db_sub.getStatement().executeQuery(sql);
            while (rs.next()) {
                ComboBox_bagian.addItem(rs.getString("kode_sub"));
            }

            ComboBox_levelGaji.removeAllItems();
            sql = "SELECT `level_gaji` FROM `tb_level_gaji` WHERE 1 ORDER BY `upah_per_hari` DESC";
            rs = Utility.db_sub.getStatement().executeQuery(sql);
            while (rs.next()) {
                ComboBox_levelGaji.addItem(rs.getString("level_gaji"));
            }
            loadData_edit(ID_pegawai);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            Logger.getLogger(JDialog_Edit_DataKaryawanSUB_Online.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    public void loadData_edit(String id) {
        try {
            String get_karyawan_sql = "SELECT `id_pegawai`, `nama_pegawai`, `jenis_kelamin`, `tgl_lahir`, `no_hp`, `email`, `saldo`, `bagian`, `divisi`, `jenis_pegawai`, `level_gaji`, `status`, `tanggal_masuk`, `tanggal_keluar`, `login_username`, `login_pin`, `foto_ktp` "
                    + "FROM `tb_karyawan` WHERE `id_pegawai`='" + id_pegawai + "'";
            rs = Utility.db_sub.getStatement().executeQuery(get_karyawan_sql);
            if (rs.next()) {
                txt_id_pegawai.setText(rs.getString("id_pegawai"));
                txt_nama.setText(rs.getString("nama_pegawai"));
                ComboBox_Kelamin.setSelectedItem(rs.getString("jenis_kelamin"));
                Date_tgl_lahir.setDate(rs.getDate("tgl_lahir"));
                txt_no_telp.setText(rs.getString("no_hp"));
                txt_email.setText(rs.getString("email"));
                ComboBox_bagian.setSelectedItem(rs.getString("bagian"));
                ComboBox_divisi.setSelectedItem(rs.getString("divisi"));
                ComboBox_posisi.setSelectedItem(rs.getString("jenis_pegawai"));
                ComboBox_levelGaji.setSelectedItem(rs.getString("level_gaji"));
                Date_masuk.setDate(rs.getDate("tanggal_masuk"));
                Date_keluar.setDate(rs.getDate("tanggal_keluar"));
                txt_login_username.setText(rs.getString("login_username"));
                txt_login_pin.setText(rs.getString("login_pin"));
                lbl_Image_ktp.setIcon(Utility.ResizeImage("https://waleta019.com/subwaleta/assets/foto_ktp/subwaleta_temp_foto_ktp_1096356267050937179.jpg", null, lbl_Image_ktp.getWidth(), lbl_Image_ktp.getHeight()));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            Logger.getLogger(JDialog_Edit_DataKaryawanSUB_Online.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        label_title_op_karyawan = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_id_pegawai = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        ComboBox_Kelamin = new javax.swing.JComboBox<>();
        Date_tgl_lahir = new com.toedter.calendar.JDateChooser();
        txt_no_telp = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        Date_masuk = new com.toedter.calendar.JDateChooser();
        Date_keluar = new com.toedter.calendar.JDateChooser();
        ComboBox_posisi = new javax.swing.JComboBox<>();
        ComboBox_bagian = new javax.swing.JComboBox<>();
        ComboBox_levelGaji = new javax.swing.JComboBox<>();
        txt_login_username = new javax.swing.JTextField();
        txt_login_pin = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        ComboBox_divisi = new javax.swing.JComboBox<>();
        lbl_Image_ktp = new javax.swing.JLabel();
        label_ktp_location = new javax.swing.JLabel();
        button_browse_ktp = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        button_proceed_insert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        label_title_op_karyawan.setBackground(new java.awt.Color(255, 255, 255));
        label_title_op_karyawan.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        label_title_op_karyawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title_op_karyawan.setText("Edit Data Karyawan Sub Online");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        jLabel7.setText("Tanggal Lahir :");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        jLabel5.setText("Nama Lengkap :");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        jLabel8.setText("Jenis Kelamin :");

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        jLabel29.setText("No Telp :");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        jLabel17.setText("ID Pegawai :");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        jLabel20.setText("Posisi :");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        jLabel21.setText("Bagian / Sub :");

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        jLabel22.setText("Tanggal Masuk :");

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        jLabel23.setText("Level Gaji Sub :");

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        jLabel30.setText("Email :");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        jLabel24.setText("Tanggal Keluar :");

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        jLabel25.setText("Login Username :");

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        jLabel26.setText("Login PIN :");

        txt_id_pegawai.setEditable(false);
        txt_id_pegawai.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_nama.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        ComboBox_Kelamin.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        ComboBox_Kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "P" }));

        Date_tgl_lahir.setBackground(new java.awt.Color(255, 255, 255));
        Date_tgl_lahir.setDateFormatString("dd MMMM yyyy");
        Date_tgl_lahir.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Date_tgl_lahir.setMaxSelectableDate(new Date());

        txt_no_telp.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_no_telp.setText("-");

        txt_email.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_email.setText("-");

        Date_masuk.setBackground(new java.awt.Color(255, 255, 255));
        Date_masuk.setDate(new Date());
        Date_masuk.setDateFormatString("dd MMMM yyyy");
        Date_masuk.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N

        Date_keluar.setBackground(new java.awt.Color(255, 255, 255));
        Date_keluar.setDate(new Date());
        Date_keluar.setDateFormatString("dd MMMM yyyy");
        Date_keluar.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N

        ComboBox_posisi.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        ComboBox_posisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KARYAWAN", "KEPALA" }));

        ComboBox_bagian.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        ComboBox_levelGaji.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_login_username.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_login_pin.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        jLabel27.setText("Divisi :");

        ComboBox_divisi.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        ComboBox_divisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuci", "Cabut", "Cetak", "Koreksi", "Trainer", "Admin" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_Kelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_nama)
                            .addComponent(Date_tgl_lahir, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(txt_no_telp)
                            .addComponent(ComboBox_posisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBox_bagian, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_id_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(ComboBox_levelGaji, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_email)
                            .addComponent(txt_login_username)
                            .addComponent(txt_login_pin)
                            .addComponent(ComboBox_divisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date_masuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date_keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt_id_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_Kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_no_telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_posisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_bagian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_divisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_levelGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_login_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_login_pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_Image_ktp.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Image_ktp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Image_ktp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label_ktp_location.setBackground(new java.awt.Color(255, 255, 255));
        label_ktp_location.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        label_ktp_location.setText("Image Location");
        label_ktp_location.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_ktp_location.setMaximumSize(new java.awt.Dimension(280, 15));

        button_browse_ktp.setBackground(new java.awt.Color(255, 255, 255));
        button_browse_ktp.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        button_browse_ktp.setText("Browse Scan KTP");
        button_browse_ktp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_browse_ktpActionPerformed(evt);
            }
        });

        button_cancel.setBackground(new java.awt.Color(255, 255, 255));
        button_cancel.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        button_cancel.setText("Cancel");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        button_proceed_insert.setBackground(new java.awt.Color(255, 255, 255));
        button_proceed_insert.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        button_proceed_insert.setText("Save");
        button_proceed_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_proceed_insertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_title_op_karyawan, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Image_ktp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(label_ktp_location, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_browse_ktp))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(button_cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_proceed_insert)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_title_op_karyawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Image_ktp, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_ktp_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_browse_ktp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_proceed_insert)
                    .addComponent(button_cancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_button_cancelActionPerformed

    private void button_proceed_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_proceed_insertActionPerformed
        try {
            boolean cek = true;
            if (txt_id_pegawai.getText() == null || txt_id_pegawai.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "id pegawai tidak boleh kosong !");
                cek = false;
            } else if (txt_nama.getText() == null || txt_nama.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "nama karyawan tidak boleh kosong !");
                cek = false;
            } else if (Date_tgl_lahir.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Tanggal lahir karyawan tidak boleh kosong !");
                cek = false;
            } else if (txt_no_telp.getText() == null || txt_no_telp.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "No telp karyawan tidak boleh kosong !");
                cek = false;
            } else if (txt_email.getText() == null || txt_email.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Email karyawan tidak boleh kosong !");
                cek = false;
            } else if (txt_login_username.getText() == null || txt_login_username.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Login Username tidak boleh kosong !");
                cek = false;
            } else if (txt_login_pin.getText() == null || txt_login_pin.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Login Pin tidak boleh kosong !");
                cek = false;
            } else if (Date_masuk.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Tanggal masuk tidak boleh kosong !");
                cek = false;
            }
            if (cek) {
                String update_image_path = "";
                if (imgPath != null) {
                    update_image_path = "`foto_ktp`=[value-16], ";
                }
                String status = "";
                if (Date_keluar.getDate() == null) {
                    status = "`status`='IN-SUB',"
                        + "`tanggal_keluar`=NULL,";
                } else {
                    status = "`status`='OUT-SUB',"
                        + "`tanggal_keluar`='"+dateFormat.format(Date_keluar.getDate())+"',";
                }
                sql = "UPDATE `tb_karyawan` SET "
                        + "`nama_pegawai`='"+txt_nama.getText()+"',"
                        + "`jenis_kelamin`='"+ComboBox_Kelamin.getSelectedItem().toString()+"',"
                        + "`tgl_lahir`='"+dateFormat.format(Date_tgl_lahir.getDate())+"',"
                        + "`no_hp`='"+txt_no_telp.getText()+"',"
                        + "`email`='"+txt_email.getText()+"',"
                        + "`bagian`='"+ComboBox_bagian.getSelectedItem().toString()+"',"
                        + "`divisi`='"+ComboBox_divisi.getSelectedItem().toString()+"',"
                        + "`jenis_pegawai`='"+ComboBox_posisi.getSelectedItem().toString()+"',"
                        + "`level_gaji`='"+ComboBox_levelGaji.getSelectedItem().toString()+"',"
                        + "`tanggal_masuk`='"+dateFormat.format(Date_masuk.getDate())+"',"
                        + status
                        + "`login_username`='"+txt_login_username.getText()+"',"
                        + "`login_pin`='"+txt_login_pin.getText()+"' "
                        + "WHERE `id_pegawai` = '" + id_pegawai + "'";
                Utility.db_sub.connect();
                Utility.db_sub.getConnection().createStatement();
                if ((Utility.db_sub.getStatement().executeUpdate(sql)) == 1) {
                    JOptionPane.showMessageDialog(this, "Edit data online berhasil !!!");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Edit data online gagal !!!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            Logger.getLogger(JDialog_Edit_DataKaryawanSUB_Online.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_proceed_insertActionPerformed

    private void button_browse_ktpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_browse_ktpActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter files extension
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lbl_Image_ktp.setIcon(Utility.ResizeImage(path, null, lbl_Image_ktp.getWidth(), lbl_Image_ktp.getHeight()));
            label_ktp_location.setText(path);
            imgPath = path;
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("NO FILE SELECTED !");
        }
    }//GEN-LAST:event_button_browse_ktpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> ComboBox_Kelamin;
    public static javax.swing.JComboBox<String> ComboBox_bagian;
    public static javax.swing.JComboBox<String> ComboBox_divisi;
    public static javax.swing.JComboBox<String> ComboBox_levelGaji;
    public static javax.swing.JComboBox<String> ComboBox_posisi;
    public static com.toedter.calendar.JDateChooser Date_keluar;
    public static com.toedter.calendar.JDateChooser Date_masuk;
    public static com.toedter.calendar.JDateChooser Date_tgl_lahir;
    private javax.swing.JButton button_browse_ktp;
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_proceed_insert;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_ktp_location;
    public static javax.swing.JLabel label_title_op_karyawan;
    private javax.swing.JLabel lbl_Image_ktp;
    public static javax.swing.JTextField txt_email;
    public static javax.swing.JTextField txt_id_pegawai;
    public static javax.swing.JTextField txt_login_pin;
    public static javax.swing.JTextField txt_login_username;
    public static javax.swing.JTextField txt_nama;
    public static javax.swing.JTextField txt_no_telp;
    // End of variables declaration//GEN-END:variables
}
