package waleta_system.SubWaleta;

import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import waleta_system.Class.ColumnsAutoSizer;
import waleta_system.Class.Utility;

public class JDialog_input_absen extends javax.swing.JDialog {

    String sql = null;
    ResultSet rs;

    public JDialog_input_absen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        refreshTable();
    }

    public void refreshTable() {
        try {
            Utility.db_sub.connect();
            DefaultTableModel model = (DefaultTableModel) table_list_karyawan.getModel();
            model.setRowCount(0);
            String bagian = " AND `bagian` = '" + ComboBox_sub.getSelectedItem().toString() + "' ";
            if (ComboBox_sub.getSelectedItem().toString().equals("All")) {
                bagian = "";
            }
            sql = "SELECT `id_pegawai`, `nama_pegawai`, `bagian`, `jenis_pegawai`, `status` "
                    + "FROM `tb_karyawan` "
                    + "WHERE `nama_pegawai` LIKE '%" + txt_search_nama_pegawai.getText() + "%' "
                    + " AND `status` = '" + ComboBox_status.getSelectedItem().toString() + "' "
                    + bagian
                    + "GROUP BY `tb_karyawan`.`id_pegawai` "
                    + "ORDER BY `tb_karyawan`.`id_pegawai` DESC";
            rs = Utility.db_sub.getStatement().executeQuery(sql);
            Object[] row = new Object[5];
            while (rs.next()) {
                row[0] = rs.getString("id_pegawai");
                row[1] = rs.getString("nama_pegawai");
                row[2] = rs.getString("bagian");
                row[3] = rs.getString("jenis_pegawai");
                row[4] = rs.getString("status");
                model.addRow(row);
            }
            ColumnsAutoSizer.sizeColumnsToFit(table_list_karyawan);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            Logger.getLogger(JDialog_input_absen.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    public boolean duplicate_id(String input_id) {
        boolean output = false;
        for (int i = 0; i < table_list_karyawan_terpilih.getRowCount(); i++) {
            if (input_id.equals(table_list_karyawan_terpilih.getValueAt(i, 0).toString())) {
                output = true;
                break;
            }
        }
        ColumnsAutoSizer.sizeColumnsToFit(table_list_karyawan_terpilih);
        return output;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ComboBox_jam = new javax.swing.JComboBox<>();
        ComboBox_menit = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        button_simpan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ComboBox_sub = new javax.swing.JComboBox<>();
        txt_search_id_pegawai = new javax.swing.JTextField();
        txt_search_nama_pegawai = new javax.swing.JTextField();
        ComboBox_status = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_list_karyawan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        button_search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_list_karyawan_terpilih = new javax.swing.JTable();
        Date_tanggal_absen = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Input Absen :");

        ComboBox_jam.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ComboBox_jam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        ComboBox_menit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ComboBox_menit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Input Absen Sub Manual");

        button_simpan.setBackground(new java.awt.Color(255, 255, 255));
        button_simpan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        button_simpan.setText("Simpan");
        button_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_simpanActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        ComboBox_sub.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        ComboBox_sub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        ComboBox_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_subActionPerformed(evt);
            }
        });

        txt_search_id_pegawai.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_search_id_pegawai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_search_id_pegawaiKeyPressed(evt);
            }
        });

        txt_search_nama_pegawai.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_search_nama_pegawai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_search_nama_pegawaiKeyPressed(evt);
            }
        });

        ComboBox_status.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        ComboBox_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IN-SUB" }));
        ComboBox_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_statusActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("Status :");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Sub :");

        table_list_karyawan.setAutoCreateRowSorter(true);
        table_list_karyawan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        table_list_karyawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Sub", "Posisi", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_list_karyawan.getTableHeader().setReorderingAllowed(false);
        table_list_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_list_karyawanMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_list_karyawan);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Nama :");

        button_search.setBackground(new java.awt.Color(255, 255, 255));
        button_search.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_search.setText("Search");
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("ID :");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jLabel11.setText("Note : klik 2x untuk memilih");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_search_id_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_search_nama_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBox_sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBox_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_search)
                        .addGap(0, 106, Short.MAX_VALUE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboBox_status, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_search_id_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_search_nama_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ComboBox_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        table_list_karyawan_terpilih.setAutoCreateRowSorter(true);
        table_list_karyawan_terpilih.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        table_list_karyawan_terpilih.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Sub"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_list_karyawan_terpilih.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(table_list_karyawan_terpilih);

        Date_tanggal_absen.setBackground(new java.awt.Color(255, 255, 255));
        Date_tanggal_absen.setDate(new Date());
        Date_tanggal_absen.setDateFormatString("dd MMM yyyy");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Jam :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Date_tanggal_absen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBox_jam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBox_menit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_simpan)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_simpan)
                            .addComponent(Date_tanggal_absen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_jam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_menit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_simpanActionPerformed
        try {
            // TODO add your handling code here:
            InetAddress inetAddress = InetAddress.getLocalHost();
            boolean cek = true;
            int inoutmode = 0, jam = Integer.valueOf(ComboBox_jam.getSelectedItem().toString()), jumlah_update = 0;
            if (new SimpleDateFormat("yyyy-MM-dd").format(Date_tanggal_absen.getDate()).equalsIgnoreCase("SUNDAY")) {
                JOptionPane.showMessageDialog(this, "tidak bisa absen hari minggu");
                cek = false;
            } else if (new SimpleDateFormat("yyyy-MM-dd").format(Date_tanggal_absen.getDate()).equalsIgnoreCase("SATURDAY")) {
                if (jam > 6 && jam < 8) {
                    inoutmode = 1;
                } else if (jam > 12 && jam < 15) {
                    inoutmode = 2;
                } else {
                    JOptionPane.showMessageDialog(this, "Belum saatnya jam absen!");
                    cek = false;
                }
            } else {
                if (jam > 6 && jam < 8) {
                    inoutmode = 1;
                } else if (jam > 15 && jam < 18) {
                    inoutmode = 2;
                } else {
                    JOptionPane.showMessageDialog(this, "Belum saatnya jam absen!");
                    cek = false;
                }
            }

            if (cek) {
                Utility.db_sub.connect();
                Utility.db_sub.getConnection().setAutoCommit(false);
                for (int i = 0; i < table_list_karyawan_terpilih.getRowCount(); i++) {
                    int pin = Integer.valueOf(table_list_karyawan_terpilih.getValueAt(i, 0).toString().substring(6));
                    sql = "INSERT INTO `att_log`(`sn`, `scan_date`, `pin`, `verifymode`, `inoutmode`, `device_ip`, `pin2`) "
                            + "VALUES ("
                            + "'" + inetAddress.getHostName() + "',"
                            + "'" + new SimpleDateFormat("yyyy-MM-dd").format(Date_tanggal_absen.getDate()) + " " + ComboBox_jam.getSelectedItem().toString() + ":" + ComboBox_menit.getSelectedItem().toString() + ":00',"
                            + "'" + pin + "',"
                            + "'0',"
                            + "'" + inoutmode + "',"
                            + "'" + inetAddress.getHostAddress() + "',"
                            + "'" + table_list_karyawan_terpilih.getValueAt(i, 0).toString() + "'"
                            + ")";
                    Utility.db_sub.getConnection().createStatement();
                    if ((Utility.db_sub.getStatement().executeUpdate(sql)) == 1) {
                        jumlah_update++;
                    }
                }
                Utility.db_sub.getConnection().commit();
                JOptionPane.showMessageDialog(this, "Sukses input " + jumlah_update + " data");
                this.dispose();
            }
        } catch (Exception ex) {
            try {
                Utility.db_sub.getConnection().rollback();
            } catch (SQLException ex1) {
                Logger.getLogger(JDialog_input_absen.class.getName()).log(Level.SEVERE, null, ex1);
            }
            JOptionPane.showMessageDialog(this, "failed : " + ex);
            Logger.getLogger(JDialog_input_absen.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                Utility.db_sub.getConnection().setAutoCommit(true);
            } catch (SQLException ex) {
                Logger.getLogger(JDialog_input_absen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_button_simpanActionPerformed

    private void ComboBox_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_statusActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_ComboBox_statusActionPerformed

    private void txt_search_id_pegawaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_id_pegawaiKeyPressed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_list_karyawan_terpilih.getModel();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            refreshTable();
            if (table_list_karyawan.getRowCount() == 1) {
                if (duplicate_id(table_list_karyawan.getValueAt(0, 0).toString())) {
                    JOptionPane.showMessageDialog(this, "Karyawan sudah masuk dalam list");
                } else {
                    model.addRow(new Object[]{table_list_karyawan.getValueAt(0, 0).toString(), table_list_karyawan.getValueAt(0, 1).toString(), table_list_karyawan.getValueAt(0, 2).toString()});
                }
            }
        }
    }//GEN-LAST:event_txt_search_id_pegawaiKeyPressed

    private void table_list_karyawanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_list_karyawanMousePressed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_list_karyawan_terpilih.getModel();
        int i = table_list_karyawan.getSelectedRow();
        if (evt.getClickCount() == 2) {
            if (duplicate_id(table_list_karyawan.getValueAt(0, 0).toString())) {
                JOptionPane.showMessageDialog(this, "Karyawan sudah masuk dalam list");
            } else {
                model.addRow(new Object[]{table_list_karyawan.getValueAt(i, 0).toString(), table_list_karyawan.getValueAt(i, 1).toString(), table_list_karyawan.getValueAt(i, 2).toString()});
            }
        }
    }//GEN-LAST:event_table_list_karyawanMousePressed

    private void ComboBox_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_subActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_ComboBox_subActionPerformed

    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_searchActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_button_searchActionPerformed

    private void txt_search_nama_pegawaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_nama_pegawaiKeyPressed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_list_karyawan_terpilih.getModel();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            refreshTable();
            if (table_list_karyawan.getRowCount() == 1) {
                if (duplicate_id(table_list_karyawan.getValueAt(0, 0).toString())) {
                    JOptionPane.showMessageDialog(this, "Karyawan sudah masuk dalam list");
                } else {
                    model.addRow(new Object[]{table_list_karyawan.getValueAt(0, 0).toString(), table_list_karyawan.getValueAt(0, 1).toString(), table_list_karyawan.getValueAt(0, 2).toString()});
                }
            }
        }
    }//GEN-LAST:event_txt_search_nama_pegawaiKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialog_input_absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialog_input_absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialog_input_absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialog_input_absen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog_input_absen dialog = new JDialog_input_absen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_jam;
    private javax.swing.JComboBox<String> ComboBox_menit;
    public static javax.swing.JComboBox<String> ComboBox_status;
    public static javax.swing.JComboBox<String> ComboBox_sub;
    private com.toedter.calendar.JDateChooser Date_tanggal_absen;
    private javax.swing.JButton button_search;
    private javax.swing.JButton button_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable table_list_karyawan;
    public static javax.swing.JTable table_list_karyawan_terpilih;
    private javax.swing.JTextField txt_search_id_pegawai;
    private javax.swing.JTextField txt_search_nama_pegawai;
    // End of variables declaration//GEN-END:variables
}
