package waleta_system.BahanJadi;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import static org.apache.commons.lang.StringUtils.containsIgnoreCase;
import waleta_system.Browse_Karyawan;
import waleta_system.Class.Utility;

public class JDialog_reProses_pencabut extends javax.swing.JDialog {

     
    String sql = null;
    ResultSet rs;
    Date date = new Date();
    DecimalFormat decimalFormat = new DecimalFormat();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    DefaultTableCellRenderer TableAlignment = new DefaultTableCellRenderer();
    String no_reproses = null, id_lama = null, tgl_lama = null;

    public JDialog_reProses_pencabut(java.awt.Frame parent, boolean modal, String fungsi, String no_reproses, String id_lama, String tgl_lama) {
        super(parent, modal);
        initComponents();
        this.no_reproses = no_reproses;
        if (fungsi.equals("edit")) {
            this.id_lama = id_lama;
            this.tgl_lama = tgl_lama;
            button_add_pencabut.setVisible(false);
            button_edit_pencabut.setVisible(true);
            try {
                
                sql = "SELECT `no_reproses`, `tb_reproses_pencabut`.`id_pegawai`, `tb_karyawan`.`nama_pegawai`, `tb_bagian`.`nama_bagian`, `tanggal_cabut`, `jumlah_cabut`, `jumlah_gram`, `grup_cabut` "
                        + "FROM `tb_reproses_pencabut` "
                        + "LEFT JOIN `tb_karyawan` ON `tb_reproses_pencabut`.`id_pegawai` = `tb_karyawan`.`id_pegawai` "
                        + "LEFT JOIN `tb_bagian` ON `tb_karyawan`.`kode_bagian` = `tb_bagian`.`kode_bagian` "
                        + "WHERE `no_reproses` = '" + no_reproses + "' AND `tb_reproses_pencabut`.`id_pegawai` = '" + id_lama + "' AND `tanggal_cabut` = '" + tgl_lama + "'";
//                System.out.println(sql);
                rs = Utility.db.getStatement().executeQuery(sql);
                if (rs.next()) {
                    txt_id_pegawai.setText(rs.getString("id_pegawai"));
                    txt_nama_pegawai.setText(rs.getString("nama_pegawai"));
                    txt_bagian.setText(rs.getString("nama_bagian"));
                    Date_cabut.setDate(rs.getDate("tanggal_cabut"));
                    txt_jmlh_keping.setText(rs.getString("jumlah_cabut"));
                }
            } catch (Exception ex) {
                Logger.getLogger(JDialog_reProses_pencabut.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (fungsi.equals("new")) {
            button_add_pencabut.setVisible(true);
            button_edit_pencabut.setVisible(false);
        }
        try {
            
        } catch (Exception ex) {
            Logger.getLogger(JDialog_reProses_pencabut.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button_edit_pencabut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_id_pegawai = new javax.swing.JTextField();
        txt_nama_pegawai = new javax.swing.JTextField();
        txt_jmlh_keping = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Date_cabut = new com.toedter.calendar.JDateChooser();
        button_add_pencabut = new javax.swing.JButton();
        button_pick_pencabut = new javax.swing.JButton();
        button_clear_pencabut = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txt_bagian = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Input Pencabut Reproses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        button_edit_pencabut.setBackground(new java.awt.Color(255, 255, 255));
        button_edit_pencabut.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_edit_pencabut.setText("Edit");
        button_edit_pencabut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_edit_pencabutActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("ID Pegawai :");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("Nama Pegawai :");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("Tanggal :");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setText("Jumlah Cabutan :");

        txt_id_pegawai.setEditable(false);
        txt_id_pegawai.setBackground(new java.awt.Color(255, 255, 255));
        txt_id_pegawai.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_nama_pegawai.setEditable(false);
        txt_nama_pegawai.setBackground(new java.awt.Color(255, 255, 255));
        txt_nama_pegawai.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_jmlh_keping.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setText("Keping (1 keping = 6gram)");

        Date_cabut.setBackground(new java.awt.Color(255, 255, 255));
        Date_cabut.setDate(new Date());
        Date_cabut.setDateFormatString("dd MMMM yyyy");
        Date_cabut.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        button_add_pencabut.setBackground(new java.awt.Color(255, 255, 255));
        button_add_pencabut.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_add_pencabut.setText("Add");
        button_add_pencabut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_add_pencabutActionPerformed(evt);
            }
        });

        button_pick_pencabut.setBackground(new java.awt.Color(255, 255, 255));
        button_pick_pencabut.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_pick_pencabut.setText("...");
        button_pick_pencabut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pick_pencabutActionPerformed(evt);
            }
        });

        button_clear_pencabut.setBackground(new java.awt.Color(255, 255, 255));
        button_clear_pencabut.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_clear_pencabut.setText("Cancel");
        button_clear_pencabut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clear_pencabutActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel14.setText("Bagian :");

        txt_bagian.setEditable(false);
        txt_bagian.setBackground(new java.awt.Color(255, 255, 255));
        txt_bagian.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_nama_pegawai, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_id_pegawai)
                        .addGap(0, 0, 0)
                        .addComponent(button_pick_pencabut, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Date_cabut, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(txt_bagian, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_jmlh_keping, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(button_clear_pencabut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_edit_pencabut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_add_pencabut)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_pick_pencabut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nama_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bagian, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_cabut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jmlh_keping, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_edit_pencabut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_add_pencabut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_clear_pencabut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_edit_pencabutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_edit_pencabutActionPerformed
        // TODO add your handling code here:
        try {
            decimalFormat.setGroupingUsed(false);
            decimalFormat.setMaximumFractionDigits(2);
            float keping_cabut = Float.valueOf(txt_jmlh_keping.getText());
            float berat_box = 0, kpg_box = 0, gram_cabutan = 0;
            String query = "SELECT `keping`, `gram` FROM `tb_reproses` WHERE `no_reproses` = '" + no_reproses + "'";
            ResultSet result = Utility.db.getStatement().executeQuery(query);
            if (result.next()) {
                berat_box = result.getFloat("gram");
                kpg_box = result.getFloat("keping");
                if (kpg_box > 0) {
                    gram_cabutan = (berat_box / kpg_box) * keping_cabut;
                } else {
                    gram_cabutan = (berat_box / Math.round(berat_box / 6)) * keping_cabut;
                }
            }

            String nama_grup = null;
            String query_grup = "SELECT `kode_grup` FROM `tb_grup_cabut` WHERE `id_pegawai` = '" + txt_id_pegawai.getText() + "'";
            ResultSet result_grup = Utility.db.getStatement().executeQuery(query_grup);
            if (result_grup.next()) {
                nama_grup = result_grup.getString("kode_grup");
            } else {
                nama_grup = "-";
            }

            sql = "UPDATE `tb_reproses_pencabut` SET "
                    + "`id_pegawai`='" + txt_id_pegawai.getText() + "',"
                    + "`tanggal_cabut`='" + dateFormat.format(Date_cabut.getDate()) + "',"
                    + "`jumlah_cabut`='" + keping_cabut + "', "
                    + "`jumlah_gram`='" + decimalFormat.format(gram_cabutan) + "', "
                    + "`grup_cabut`='" + nama_grup + "' "
                    + "WHERE "
                    + "`no_reproses`='" + no_reproses + "' AND "
                    + "`id_pegawai`='" + id_lama + "' AND "
                    + "`tanggal_cabut`='" + tgl_lama + "'";
            Utility.db.getConnection().createStatement();
            if ((Utility.db.getStatement().executeUpdate(sql)) == 1) {
                JOptionPane.showMessageDialog(this, "data Saved !");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Failed !");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(JDialog_reProses_pencabut.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_edit_pencabutActionPerformed

    private void button_add_pencabutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_add_pencabutActionPerformed
        // TODO add your handling code here:
        try {
            decimalFormat.setGroupingUsed(false);
            decimalFormat.setMaximumFractionDigits(2);
            float keping_cabut = Float.valueOf(txt_jmlh_keping.getText());
            float berat_box = 0, kpg_box = 0, gram_cabutan = 0;
            String query = "SELECT `keping`, `gram` FROM `tb_reproses` WHERE `no_reproses` = '" + no_reproses + "'";
            ResultSet result = Utility.db.getStatement().executeQuery(query);
            if (result.next()) {
                berat_box = result.getFloat("gram");
                kpg_box = result.getFloat("keping");
                if (kpg_box > 0) {
                    gram_cabutan = (berat_box / kpg_box) * keping_cabut;
                } else {
                    gram_cabutan = (berat_box / Math.round(berat_box / 6)) * keping_cabut;
                }
            }

            String nama_grup = null;
            String query_grup = "SELECT `kode_grup` FROM `tb_grup_cabut` WHERE `id_pegawai` = '" + txt_id_pegawai.getText() + "'";
            ResultSet result_grup = Utility.db.getStatement().executeQuery(query_grup);
            if (result_grup.next()) {
                nama_grup = result_grup.getString("kode_grup");
            } else {
                nama_grup = "-";
            }

            boolean input_pertama = false;
            String query_input_pertama = "SELECT * FROM `tb_reproses_pencabut` WHERE `no_reproses` = '" + no_reproses + "'";
            ResultSet result_input_pertama = Utility.db.getStatement().executeQuery(query_input_pertama);
            input_pertama = result_input_pertama.next();

            if (containsIgnoreCase(txt_bagian.getText(), "CABUT")) {
                if (!input_pertama) {
                    sql = "UPDATE `tb_reproses` SET `tgl_cabut`=CURRENT_DATE WHERE `no_reproses` = '" + no_reproses + "'";
                    Utility.db.getConnection().createStatement();
                    Utility.db.getStatement().executeUpdate(sql);
                }
                sql = "INSERT INTO `tb_reproses_pencabut`(`no_reproses`, `id_pegawai`, `tanggal_cabut`, `jumlah_cabut`, `jumlah_gram`, `grup_cabut`) "
                        + "VALUES ('" + no_reproses + "','" + txt_id_pegawai.getText() + "','" + dateFormat.format(Date_cabut.getDate()) + "','" + keping_cabut + "', " + decimalFormat.format(gram_cabutan) + ", '" + nama_grup + "')";
                System.out.println(sql);
                Utility.db.getConnection().createStatement();
                if ((Utility.db.getStatement().executeUpdate(sql)) == 1) {
                    JOptionPane.showMessageDialog(this, "data Saved !");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed !");
                }
            } else {
                int dialogResult = JOptionPane.showConfirmDialog(null, "Apakah anda yakin pegawai bukan dari bagian CABUT?", "Warning", JOptionPane.YES_NO_OPTION);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    // Saving code here
                    if (!input_pertama) {
                        sql = "UPDATE `tb_reproses` SET `tgl_cabut`=CURRENT_DATE WHERE `no_reproses` = '" + no_reproses + "'";
                        Utility.db.getConnection().createStatement();
                        Utility.db.getStatement().executeUpdate(sql);
                    }
                    sql = "INSERT INTO `tb_reproses_pencabut`(`no_reproses`, `id_pegawai`, `tanggal_cabut`, `jumlah_cabut`, `jumlah_gram`, `grup_cabut`) "
                            + "VALUES ('" + no_reproses + "','" + txt_id_pegawai.getText() + "','" + dateFormat.format(Date_cabut.getDate()) + "','" + keping_cabut + "', " + decimalFormat.format(gram_cabutan) + ", '" + nama_grup + "')";
                    Utility.db.getConnection().createStatement();
                    if ((Utility.db.getStatement().executeUpdate(sql)) == 1) {
                        JOptionPane.showMessageDialog(this, "data Saved !");
                    } else {
                        JOptionPane.showMessageDialog(this, "Failed !");
                    }
                } else if (dialogResult == JOptionPane.NO_OPTION) {

                }
            }
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(JDialog_reProses_pencabut.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_add_pencabutActionPerformed

    private void button_pick_pencabutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pick_pencabutActionPerformed
        // TODO add your handling code here:
        String filter = "AND `tb_bagian`.`kode_departemen` = 'PRODUKSI' ";
        Browse_Karyawan dialog = new Browse_Karyawan(new javax.swing.JFrame(), true, filter);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);

        int x = Browse_Karyawan.table_list_karyawan.getSelectedRow();
        if (x != -1) {
            txt_id_pegawai.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 0).toString());
            txt_nama_pegawai.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 1).toString());
            txt_bagian.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 2).toString());
        }
    }//GEN-LAST:event_button_pick_pencabutActionPerformed

    private void button_clear_pencabutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clear_pencabutActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_button_clear_pencabutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialog_reProses_pencabut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialog_reProses_pencabut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialog_reProses_pencabut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialog_reProses_pencabut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog_reProses_pencabut dialog = new JDialog_reProses_pencabut(new javax.swing.JFrame(), true, "new", "", "", "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_cabut;
    public javax.swing.JButton button_add_pencabut;
    private javax.swing.JButton button_clear_pencabut;
    public javax.swing.JButton button_edit_pencabut;
    private javax.swing.JButton button_pick_pencabut;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_bagian;
    private javax.swing.JTextField txt_id_pegawai;
    private javax.swing.JTextField txt_jmlh_keping;
    private javax.swing.JTextField txt_nama_pegawai;
    // End of variables declaration//GEN-END:variables
}
