package waleta_system.BahanJadi;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import waleta_system.Browse_Karyawan;
import waleta_system.Class.Utility;

public class JDialog_Insert_Edit_kinerjaGBJ extends javax.swing.JDialog {

     
    String sql = null;
    ResultSet rs;
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date date = new Date();//date berisikan tanggal hari ini
    DecimalFormat decimalFormat = new DecimalFormat();
    float keping_box = 0, gram_box = 0;

    public JDialog_Insert_Edit_kinerjaGBJ(java.awt.Frame parent, boolean modal, String no) {
        super(parent, modal);
        initComponents();
        try {
            
            if (no == null) {
                label_no.setText("-");
                button_edit.setVisible(false);
            } else {
                label_no.setText(no);
                button_insert.setVisible(false);
                sql = "SELECT `no`, `tanggal_pengerjaan`, `pekerja_gbj`, `tb_karyawan`.`nama_pegawai`, `tb_kinerja_gbj`.`no_box`, `tb_grade_bahan_jadi`.`kode_grade`, `tb_box_bahan_jadi`.`keping`, `tb_box_bahan_jadi`.`berat`, `keping_dikerjakan`, `gram_dikerjakan`, `catatan` \n"
                        + "FROM `tb_kinerja_gbj` \n"
                        + "LEFT JOIN `tb_box_bahan_jadi` ON `tb_kinerja_gbj`.`no_box` = `tb_box_bahan_jadi`.`no_box`\n"
                        + "LEFT JOIN `tb_grade_bahan_jadi` ON `tb_box_bahan_jadi`.`kode_grade_bahan_jadi` = `tb_grade_bahan_jadi`.`kode`\n"
                        + "LEFT JOIN `tb_karyawan` ON `tb_kinerja_gbj`.`pekerja_gbj` = `tb_karyawan`.`id_pegawai`\n"
                        + "WHERE `no` = '" + no + "'";
                rs = Utility.db.getStatement().executeQuery(sql);
                if (rs.next()) {
                    Date_dikerjakan.setDate(rs.getDate("tanggal_pengerjaan"));
                    Label_id.setText(rs.getString("pekerja_gbj"));
                    Label_nama.setText(rs.getString("nama_pegawai"));
                    txt_no_box.setText(rs.getString("no_box"));
                    label_grade.setText(rs.getString("kode_grade"));
                    label_keping_box.setText(rs.getString("keping"));
                    label_gram_box.setText(rs.getString("berat"));
                    txt_kpg_dikerjakan.setText(rs.getString("keping_dikerjakan"));
                    txt_gram_dikerjakan.setText(rs.getString("gram_dikerjakan"));
                    txt_catatan.setText(rs.getString("catatan"));
                    keping_box = rs.getFloat("keping");
                    gram_box = rs.getFloat("berat");
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(JDialog_Insert_Edit_kinerjaGBJ.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void getdatabox() {
        try {
            if (txt_no_box.getText() != null && !txt_no_box.getText().equals("")) {
                sql = "SELECT `tb_grade_bahan_jadi`.`kode_grade`, `keping`, `berat` "
                        + "FROM `tb_box_bahan_jadi` LEFT JOIN `tb_grade_bahan_jadi` ON `tb_box_bahan_jadi`.`kode_grade_bahan_jadi` = `tb_grade_bahan_jadi`.`kode` "
                        + "WHERE `no_box` = '" + txt_no_box.getText() + "'";
                rs = Utility.db.getStatement().executeQuery(sql);
                if (rs.next()) {
                    label_grade.setText(rs.getString("kode_grade"));
                    label_keping_box.setText(rs.getString("keping"));
                    label_gram_box.setText(rs.getString("berat"));
                    keping_box = rs.getFloat("keping");
                    gram_box = rs.getFloat("berat");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(JDialog_Insert_Edit_kinerjaGBJ.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_operation_lp = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        label_jumlah_sobek_lp = new javax.swing.JLabel();
        label_no = new javax.swing.JLabel();
        Date_dikerjakan = new com.toedter.calendar.JDateChooser();
        label_tgl_lp = new javax.swing.JLabel();
        button_pilih_pekerja = new javax.swing.JButton();
        label_kode_grade_lp = new javax.swing.JLabel();
        label_kartu_waleta_LP = new javax.swing.JLabel();
        Label_nama = new javax.swing.JLabel();
        Label_id = new javax.swing.JLabel();
        label_jumlah_sobek_lp1 = new javax.swing.JLabel();
        txt_no_box = new javax.swing.JTextField();
        label_jumlah_pecah_lp2 = new javax.swing.JLabel();
        txt_catatan = new javax.swing.JTextField();
        label_jumlah_hilang_kaki_lp = new javax.swing.JLabel();
        label_grade = new javax.swing.JLabel();
        label_jumlah_hilang_kaki_lp1 = new javax.swing.JLabel();
        txt_gram_dikerjakan = new javax.swing.JTextField();
        label_jumlah_hilang_ujung_lp = new javax.swing.JLabel();
        txt_kpg_dikerjakan = new javax.swing.JTextField();
        button_insert = new javax.swing.JButton();
        button_edit = new javax.swing.JButton();
        label_berat_kering = new javax.swing.JLabel();
        label_gram_box = new javax.swing.JLabel();
        label_keping_box = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel_operation_lp.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_operation_lp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_operation_lp.setName("aah"); // NOI18N

        label_title.setBackground(new java.awt.Color(255, 255, 255));
        label_title.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_title.setText("Insert / Edit Data Kinerja GBJ");

        label_jumlah_sobek_lp.setBackground(new java.awt.Color(255, 255, 255));
        label_jumlah_sobek_lp.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_jumlah_sobek_lp.setText("No :");

        label_no.setBackground(new java.awt.Color(255, 255, 255));
        label_no.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_no.setText("0");

        Date_dikerjakan.setBackground(new java.awt.Color(255, 255, 255));
        Date_dikerjakan.setDate(date);
        Date_dikerjakan.setDateFormatString("dd MMM yyyy");

        label_tgl_lp.setBackground(new java.awt.Color(255, 255, 255));
        label_tgl_lp.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_tgl_lp.setText("Tanggal dikerjakan :");

        button_pilih_pekerja.setBackground(new java.awt.Color(255, 255, 255));
        button_pilih_pekerja.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_pilih_pekerja.setText("Pilih Pekerja");
        button_pilih_pekerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pilih_pekerjaActionPerformed(evt);
            }
        });

        label_kode_grade_lp.setBackground(new java.awt.Color(255, 255, 255));
        label_kode_grade_lp.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_kode_grade_lp.setText("Nama :");

        label_kartu_waleta_LP.setBackground(new java.awt.Color(255, 255, 255));
        label_kartu_waleta_LP.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_kartu_waleta_LP.setText("ID pekerja :");

        Label_nama.setBackground(new java.awt.Color(255, 255, 255));
        Label_nama.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Label_nama.setText("-");
        Label_nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        Label_id.setBackground(new java.awt.Color(255, 255, 255));
        Label_id.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Label_id.setText("-");
        Label_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        label_jumlah_sobek_lp1.setBackground(new java.awt.Color(255, 255, 255));
        label_jumlah_sobek_lp1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_jumlah_sobek_lp1.setText("No Box :");

        txt_no_box.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_no_box.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_no_boxFocusLost(evt);
            }
        });

        label_jumlah_pecah_lp2.setBackground(new java.awt.Color(255, 255, 255));
        label_jumlah_pecah_lp2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_jumlah_pecah_lp2.setText("Catatan :");

        txt_catatan.setText("-");

        label_jumlah_hilang_kaki_lp.setBackground(new java.awt.Color(255, 255, 255));
        label_jumlah_hilang_kaki_lp.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_jumlah_hilang_kaki_lp.setText("Grade :");

        label_grade.setBackground(new java.awt.Color(255, 255, 255));
        label_grade.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_grade.setText("-");

        label_jumlah_hilang_kaki_lp1.setBackground(new java.awt.Color(255, 255, 255));
        label_jumlah_hilang_kaki_lp1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_jumlah_hilang_kaki_lp1.setText("Gram dikerjakan :");

        txt_gram_dikerjakan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_gram_dikerjakan.setText("0");

        label_jumlah_hilang_ujung_lp.setBackground(new java.awt.Color(255, 255, 255));
        label_jumlah_hilang_ujung_lp.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_jumlah_hilang_ujung_lp.setText("Keping dikerjakan :");

        txt_kpg_dikerjakan.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_kpg_dikerjakan.setText("0");

        button_insert.setBackground(new java.awt.Color(255, 255, 255));
        button_insert.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_insert.setText("Insert");
        button_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_insertActionPerformed(evt);
            }
        });

        button_edit.setBackground(new java.awt.Color(255, 255, 255));
        button_edit.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        button_edit.setText("Edit");
        button_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editActionPerformed(evt);
            }
        });

        label_berat_kering.setBackground(new java.awt.Color(255, 255, 255));
        label_berat_kering.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_berat_kering.setText("Keping Box :");

        label_gram_box.setBackground(new java.awt.Color(255, 255, 255));
        label_gram_box.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_gram_box.setText("0");

        label_keping_box.setBackground(new java.awt.Color(255, 255, 255));
        label_keping_box.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        label_keping_box.setText("0");

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel25.setText("Gram Box :");

        javax.swing.GroupLayout jPanel_operation_lpLayout = new javax.swing.GroupLayout(jPanel_operation_lp);
        jPanel_operation_lp.setLayout(jPanel_operation_lpLayout);
        jPanel_operation_lpLayout.setHorizontalGroup(
            jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_operation_lpLayout.createSequentialGroup()
                .addGroup(jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_operation_lpLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_jumlah_sobek_lp1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_jumlah_hilang_kaki_lp1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_jumlah_hilang_ujung_lp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_berat_kering, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_kode_grade_lp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_kartu_waleta_LP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_jumlah_pecah_lp2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_jumlah_sobek_lp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_jumlah_hilang_kaki_lp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_tgl_lp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_no, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_gram_dikerjakan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button_pilih_pekerja, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_grade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_catatan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_gram_box, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_no_box, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_kpg_dikerjakan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Date_dikerjakan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_keping_box, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Label_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Label_id, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel_operation_lpLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(label_title))
                        .addComponent(button_insert, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(button_edit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel_operation_lpLayout.setVerticalGroup(
            jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_operation_lpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_title, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_jumlah_sobek_lp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_no, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(label_tgl_lp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_dikerjakan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_kartu_waleta_LP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_pilih_pekerja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_operation_lpLayout.createSequentialGroup()
                        .addGroup(jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_kode_grade_lp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(label_jumlah_sobek_lp1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_no_box, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_jumlah_hilang_kaki_lp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_grade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_keping_box, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_berat_kering, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_gram_box, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(label_jumlah_hilang_ujung_lp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kpg_dikerjakan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(label_jumlah_hilang_kaki_lp1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gram_dikerjakan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_operation_lpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_jumlah_pecah_lp2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_catatan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_operation_lp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_operation_lp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_pilih_pekerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pilih_pekerjaActionPerformed
        String filter = "AND `tb_bagian`.`kode_departemen` = 'EKSPOR' ";
        Browse_Karyawan dialog = new Browse_Karyawan(new javax.swing.JFrame(), true, filter);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        dialog.setEnabled(true);

        int x = Browse_Karyawan.table_list_karyawan.getSelectedRow();
        if (x != -1) {
            Label_id.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 0).toString());
            Label_nama.setText(Browse_Karyawan.table_list_karyawan.getValueAt(x, 1).toString());
        }
    }//GEN-LAST:event_button_pilih_pekerjaActionPerformed

    private void button_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editActionPerformed
        try {
            boolean check = true;
            float keping_dikerjakan = 0, gram_dikerjakan = 0;
            try {
                keping_dikerjakan = Float.valueOf(txt_kpg_dikerjakan.getText());
                gram_dikerjakan = Float.valueOf(txt_gram_dikerjakan.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Format angka salah, silahkan cek pada inputan angka");
                check = false;
            }
            
            if (gram_dikerjakan == 0) {
                JOptionPane.showMessageDialog(this, "Maaf jumlah gram dikerjakan tidak bisa 0 !");
                check = false;
            } else if (keping_dikerjakan > keping_box) {
                JOptionPane.showMessageDialog(this, "Maaf jumlah keping dikerjakan tidak bisa melebihi jumlah keping box !");
                check = false;
            } else if (gram_dikerjakan > gram_box) {
                JOptionPane.showMessageDialog(this, "Maaf jumlah gram dikerjakan tidak bisa melebihi jumlah gram box !");
                check = false;
            }

            if (check) {
                sql = "UPDATE `tb_kinerja_gbj` SET "
                        + "`tanggal_pengerjaan` = '" + dateFormat.format(Date_dikerjakan.getDate()) + "', "
                        + "`pekerja_gbj` = '" + Label_id.getText() + "', "
                        + "`no_box` = '" + txt_no_box.getText() + "', "
                        + "`keping_dikerjakan` = '" + txt_kpg_dikerjakan.getText() + "', "
                        + "`gram_dikerjakan` = '" + txt_gram_dikerjakan.getText() + "', "
                        + "`catatan` = '" + txt_catatan.getText() + "' "
                        + "WHERE `no` = '" + label_no.getText() + "'";
                Utility.db.getConnection().createStatement();
                if ((Utility.db.getStatement().executeUpdate(sql)) == 1) {
                    JOptionPane.showMessageDialog(this, "data inserted Successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "insert failed!");
                }
                this.dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(JDialog_Insert_Edit_kinerjaGBJ.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_editActionPerformed

    private void button_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_insertActionPerformed
        try {
            boolean check = true;
            float keping_dikerjakan = 0, gram_dikerjakan = 0;
            try {
                keping_dikerjakan = Float.valueOf(txt_kpg_dikerjakan.getText());
                gram_dikerjakan = Float.valueOf(txt_gram_dikerjakan.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Format angka salah, silahkan cek pada inputan angka");
                check = false;
            }
            sql = "SELECT * FROM `tb_kinerja_gbj` "
                    + "WHERE `tanggal_pengerjaan` = '" + dateFormat.format(Date_dikerjakan.getDate()) + "' "
                    + "AND `pekerja_gbj` = '" + Label_id.getText() + "' "
                    + "AND `no_box` = '" + txt_no_box.getText() + "'";
            rs = Utility.db.getStatement().executeQuery(sql);
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Data sudah diinput, silahkan cek kembali!");
                check = false;
            } else if (gram_dikerjakan == 0) {
                JOptionPane.showMessageDialog(this, "Maaf jumlah gram dikerjakan tidak bisa 0 !");
                check = false;
            } else if (keping_dikerjakan > keping_box) {
                JOptionPane.showMessageDialog(this, "Maaf jumlah keping dikerjakan tidak bisa melebihi jumlah keping box !");
                check = false;
            } else if (gram_dikerjakan > gram_box) {
                JOptionPane.showMessageDialog(this, "Maaf jumlah gram dikerjakan tidak bisa melebihi jumlah gram box !");
                check = false;
            }

            if (check) {
                sql = "INSERT INTO `tb_kinerja_gbj`(`tanggal_pengerjaan`, `pekerja_gbj`, `no_box`, `keping_dikerjakan`, `gram_dikerjakan`, `catatan`) "
                        + "VALUES ("
                        + "'" + dateFormat.format(Date_dikerjakan.getDate()) + "',"
                        + "'" + Label_id.getText() + "',"
                        + "'" + txt_no_box.getText() + "',"
                        + "'" + txt_kpg_dikerjakan.getText() + "',"
                        + "'" + txt_gram_dikerjakan.getText() + "', "
                        + "'" + txt_catatan.getText() + "')";
                Utility.db.getConnection().createStatement();
                if ((Utility.db.getStatement().executeUpdate(sql)) == 1) {
                    JOptionPane.showMessageDialog(this, "data inserted Successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "insert failed!");
                }
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            Logger.getLogger(JDialog_Insert_Edit_kinerjaGBJ.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_button_insertActionPerformed

    private void txt_no_boxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_no_boxFocusLost
        // TODO add your handling code here:
        getdatabox();
    }//GEN-LAST:event_txt_no_boxFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialog_Insert_Edit_kinerjaGBJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialog_Insert_Edit_kinerjaGBJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialog_Insert_Edit_kinerjaGBJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialog_Insert_Edit_kinerjaGBJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog_Insert_Edit_kinerjaGBJ dialog = new JDialog_Insert_Edit_kinerjaGBJ(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_dikerjakan;
    public static javax.swing.JLabel Label_id;
    public static javax.swing.JLabel Label_nama;
    private javax.swing.JButton button_edit;
    private javax.swing.JButton button_insert;
    private javax.swing.JButton button_pilih_pekerja;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel_operation_lp;
    private javax.swing.JLabel label_berat_kering;
    private javax.swing.JLabel label_grade;
    private javax.swing.JLabel label_gram_box;
    private javax.swing.JLabel label_jumlah_hilang_kaki_lp;
    private javax.swing.JLabel label_jumlah_hilang_kaki_lp1;
    private javax.swing.JLabel label_jumlah_hilang_ujung_lp;
    private javax.swing.JLabel label_jumlah_pecah_lp2;
    private javax.swing.JLabel label_jumlah_sobek_lp;
    private javax.swing.JLabel label_jumlah_sobek_lp1;
    private javax.swing.JLabel label_kartu_waleta_LP;
    private javax.swing.JLabel label_keping_box;
    private javax.swing.JLabel label_kode_grade_lp;
    private javax.swing.JLabel label_no;
    private javax.swing.JLabel label_tgl_lp;
    private javax.swing.JLabel label_title;
    private javax.swing.JTextField txt_catatan;
    private javax.swing.JTextField txt_gram_dikerjakan;
    private javax.swing.JTextField txt_kpg_dikerjakan;
    private javax.swing.JTextField txt_no_box;
    // End of variables declaration//GEN-END:variables
}
