/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package waleta_system.Maintenance.view.ruangan;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import waleta_system.Maintenance.controller.LantaiDAO;
import waleta_system.Maintenance.controller.RuanganDAO;
import waleta_system.Maintenance.model.Lantai;
import waleta_system.Maintenance.model.Ruangan;
import waleta_system.Maintenance.view.MainFrame_Maintenance;

/**
 *
 * @author User
 */
public class TambahUbahRuanganJDialog extends javax.swing.JDialog {

    private MainFrame_Maintenance mainJFrame;
    private String idRuanganUpdate;
    private ArrayList<Lantai> lantais;
    public enum KategoriDialog {
        TAMBAH,
        UBAH
    }
    private KategoriDialog kategoriDialog;

    /**
     * Creates new form TambahRuanganJDialog
     */
    public TambahUbahRuanganJDialog(java.awt.Frame parent, boolean modal, MainFrame_Maintenance mainJFrame, KategoriDialog kategoriDialog, Ruangan ruangan) {
        this(parent, modal, mainJFrame, kategoriDialog);
        idRuanganUpdate = ruangan.getIdRuangan();
        jTextFieldNamaRuangan.setText(ruangan.getNamaRuangan());
        for (int i = 0; i < lantais.size(); i++) {
            if(lantais.get(i).getIdLantai() == ruangan.getLantai().getIdLantai())
            {
                jComboBoxLantai.setSelectedIndex(i);
                break;
            }
        }
    }

    public TambahUbahRuanganJDialog(java.awt.Frame parent, boolean modal, MainFrame_Maintenance mainJFrame, KategoriDialog kategoriDialog) {
        super(parent, modal);
        initComponents();
        try {
            lantais = new LantaiDAO().selectAll();
            if(lantais.size()>0)
            {
                String[] dataLantaiString = new String[lantais.size()];
                for (int i = 0; i < lantais.size(); i++) {
                    dataLantaiString[i] = lantais.get(i).getNamaLantai();
                }
                jComboBoxLantai.setModel(new javax.swing.DefaultComboBoxModel<>(dataLantaiString));
                this.mainJFrame = mainJFrame;
                this.kategoriDialog = kategoriDialog;
                switch (kategoriDialog) {
                    case TAMBAH:
                        setTitle("Waleta Maintenance - Waleta Maintenance - Tambah Ruangan");
                        break;
                    case UBAH:
                        setTitle("Waleta Maintenance - Waleta Maintenance - Ubah Ruangan");
                        break;
                }
            }
            else
            {
                JOptionPane.showMessageDialog(TambahUbahRuanganJDialog.this, "Gagal mengambil data Lantai: Pastikan terdapat setidaknya satu buah data lantai", "Gagal", JOptionPane.ERROR_MESSAGE);
                dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(TambahUbahRuanganJDialog.this, "Gagal mengambil data Lantai: " + ex.getLocalizedMessage(), "Gagal", JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSimpan = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jTextFieldNamaRuangan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxLantai = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Waleta Maintenance - Tambah Ruangan");

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jButtonBatal.setText("Batal");
        jButtonBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Ruangan");

        jLabel3.setText("Lantai");

        jComboBoxLantai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jComboBoxLantai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(60, 60, 60)
                        .addComponent(jComboBoxLantai, 0, 424, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNamaRuangan))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSimpan)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxLantai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNamaRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSimpan)
                    .addComponent(jButtonBatal))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(546, 145));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        switch (kategoriDialog) {
            case TAMBAH:
                try {
                    Ruangan newRuangan = new Ruangan(jTextFieldNamaRuangan.getText(), new Lantai(lantais.get(jComboBoxLantai.getSelectedIndex()).getIdLantai()));
                    if(new RuanganDAO().insert(mainJFrame, newRuangan))
                    {
                        JOptionPane.showMessageDialog(TambahUbahRuanganJDialog.this, "Sukses menyimpan ruangan", "Sukses Simpan", JOptionPane.INFORMATION_MESSAGE);
                        mainJFrame.refreshRuangan();
                        dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(TambahUbahRuanganJDialog.this, "Gagal menyimpan ruangan", "Sukses Simpan", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(TambahUbahRuanganJDialog.this, "Gagal menyimpan ruangan: "+e.getLocalizedMessage(), "Gagal Simpan", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case UBAH:
                try {
                    Ruangan newRuangan = new Ruangan(jTextFieldNamaRuangan.getText(), new Lantai(lantais.get(jComboBoxLantai.getSelectedIndex()).getIdLantai()));
                    if(new RuanganDAO().update(mainJFrame, idRuanganUpdate, newRuangan))
                    {
                        JOptionPane.showMessageDialog(TambahUbahRuanganJDialog.this, "Sukses menyimpan ruangan", "Sukses Simpan", JOptionPane.INFORMATION_MESSAGE);
                        mainJFrame.refreshRuangan();
                        dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(TambahUbahRuanganJDialog.this, "Gagal menyimpan ruangan", "Sukses Simpan", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(TambahUbahRuanganJDialog.this, "Gagal menyimpan ruangan: "+e.getLocalizedMessage(), "Gagal Simpan", JOptionPane.ERROR_MESSAGE);
                }
                break;
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JComboBox<String> jComboBoxLantai;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldNamaRuangan;
    // End of variables declaration//GEN-END:variables
}
