package waleta_system.Maintenance.view.alat;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;
import javax.swing.border.TitledBorder;
import waleta_system.Maintenance.view.MainFrame_Maintenance;

public class DaftarAlatJPanel extends javax.swing.JPanel {

    private final MainFrame_Maintenance mainJFrame;
    private final int idAlat;
    private final java.awt.event.ActionListener jToggleButtonPerkecilActionEvent;
    
    /**
     * Creates new form DaftarAlatJPanel
     * @param mainJFrame
     * @param idAlat
     */
    public DaftarAlatJPanel(MainFrame_Maintenance mainJFrame, int idAlat) {
        this.mainJFrame = mainJFrame;
        this.idAlat = idAlat;
        initComponents();

        if (mainJFrame.alats.get(idAlat).getStatusAlat() == 1) {
            setBackground(new Color(100, 200, 100));
            jPanelAlat.setBackground(new Color(100, 200, 100));
        } else if (mainJFrame.alats.get(idAlat).getStatusAlat() == 2) {
            setBackground(new Color(255, 200, 100));
            jPanelAlat.setBackground(new Color(255, 200, 100));
        } else if (mainJFrame.alats.get(idAlat).getStatusAlat() == 3) {
            setBackground(new Color(255, 150, 150));
            jPanelAlat.setBackground(new Color(255, 150, 150));
        } else {
            setBackground(new Color(100, 200, 100));
            jPanelAlat.setBackground(new Color(100, 200, 100));
        }
        jToggleButtonPerkecilActionEvent = new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPerkecilActionPerformed(evt);
            }
        };
        jToggleButtonPerkecil.addActionListener(jToggleButtonPerkecilActionEvent);

        TitledBorder title = javax.swing.BorderFactory.createTitledBorder(mainJFrame.alats.get(idAlat).getIdAlat());
        title.setTitlePosition(TitledBorder.BELOW_TOP);
        setBorder(title);
        
        if (mainJFrame.alats.get(idAlat).getRuangan() == null) {
            jLabelRuangan.setText("-");
        } else if (mainJFrame.alats.get(idAlat).getRuangan().getNamaRuangan().equals("")) {
            jLabelRuangan.setText("-");
        } else {
            jLabelRuangan.setText(mainJFrame.alats.get(idAlat).getRuangan().getNamaRuangan());
        }
        if (mainJFrame.alats.get(idAlat).getKategoriAlat() == null) {
            jLabelKategoriAlat.setText("-");
        } else if (mainJFrame.alats.get(idAlat).getKategoriAlat().getNamaAlat().equals("")) {
            jLabelKategoriAlat.setText("-");
        } else {
            jLabelKategoriAlat.setText(mainJFrame.alats.get(idAlat).getKategoriAlat().getNamaAlat());
        }
        if (mainJFrame.alats.get(idAlat).getMerk().equals("")) {
            jLabelMerk.setText("-");
        } else {
            jLabelMerk.setText(mainJFrame.alats.get(idAlat).getMerk());
        }

        jTextAreaSpesifikasi.setText(mainJFrame.alats.get(idAlat).getSpesifikasi());
        jToggleButtonPerkecil.setSelected(true);
        jToggleButtonPerkecil.setText("🗖");
        jPanelAlat.setVisible(false);
        jButtonFoto.setVisible(false);
        jButtonUbah.setVisible(false);
        jButtonHapus.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAlat = new javax.swing.JPanel();
        jLabelKategoriAlat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSpesifikasi = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMerk = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonHapus = new javax.swing.JButton();
        jButtonUbah = new javax.swing.JButton();
        jButtonFoto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelRuangan = new javax.swing.JLabel();
        jCheckBoxPilih = new javax.swing.JCheckBox();
        jToggleButtonPerkecil = new javax.swing.JToggleButton();
        jButtonUbah2 = new javax.swing.JButton();
        jButtonHapus2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonFoto2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Alat 1"));
        setMaximumSize(new java.awt.Dimension(325, 32767));
        setMinimumSize(new java.awt.Dimension(325, 0));

        jLabelKategoriAlat.setText("-");

        jTextAreaSpesifikasi.setEditable(false);
        jTextAreaSpesifikasi.setColumns(20);
        jTextAreaSpesifikasi.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSpesifikasi);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Merk ");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Spesifikasi");

        jLabelMerk.setText("-");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Kategori Alat");

        jButtonHapus.setText("Hapus");
        jButtonHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonUbah.setText("Ubah");
        jButtonUbah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbahActionPerformed(evt);
            }
        });

        jButtonFoto.setText("Foto");
        jButtonFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFotoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Ruangan");

        jLabelRuangan.setText("-");

        javax.swing.GroupLayout jPanelAlatLayout = new javax.swing.GroupLayout(jPanelAlat);
        jPanelAlat.setLayout(jPanelAlatLayout);
        jPanelAlatLayout.setHorizontalGroup(
            jPanelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAlatLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMerk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelAlatLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelKategoriAlat, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                    .addGroup(jPanelAlatLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelAlatLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonFoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonUbah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonHapus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlatLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAlatLayout.setVerticalGroup(
            jPanelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlatLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRuangan)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKategoriAlat)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelMerk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAlatLayout.createSequentialGroup()
                        .addComponent(jButtonFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHapus))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jCheckBoxPilih.setText("Pilih");
        jCheckBoxPilih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBoxPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPilihActionPerformed(evt);
            }
        });

        jToggleButtonPerkecil.setText("🗕");
        jToggleButtonPerkecil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonPerkecil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonPerkecil.setMaximumSize(new java.awt.Dimension(40, 24));
        jToggleButtonPerkecil.setMinimumSize(new java.awt.Dimension(40, 24));

        jButtonUbah2.setText("✎");
        jButtonUbah2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUbah2.setMaximumSize(new java.awt.Dimension(40, 24));
        jButtonUbah2.setMinimumSize(new java.awt.Dimension(40, 24));
        jButtonUbah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbah2ActionPerformed(evt);
            }
        });

        jButtonHapus2.setText("Del");
        jButtonHapus2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHapus2.setMaximumSize(new java.awt.Dimension(40, 24));
        jButtonHapus2.setMinimumSize(new java.awt.Dimension(40, 24));
        jButtonHapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapus2ActionPerformed(evt);
            }
        });

        jButtonFoto2.setText("🖻");
        jButtonFoto2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFoto2.setMaximumSize(new java.awt.Dimension(40, 24));
        jButtonFoto2.setMinimumSize(new java.awt.Dimension(40, 24));
        jButtonFoto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoto2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelAlat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxPilih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUbah2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHapus2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonPerkecil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxPilih)
                    .addComponent(jToggleButtonPerkecil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUbah2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHapus2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public JCheckBox getjCheckBoxPilih() {
        return jCheckBoxPilih;
    }

    public JToggleButton getjToggleButtonPerkecil() {
        return jToggleButtonPerkecil;
    }

    public ActionListener getjToggleButtonPerkecilActionEvent() {
        return jToggleButtonPerkecilActionEvent;
    }

    public JLabel getjLabelRuangan() {
        return jLabelRuangan;
    }

    public JLabel getjLabelKategoriAlat() {
        return jLabelKategoriAlat;
    }

    public JLabel getjLabelMerk() {
        return jLabelMerk;
    }

    public JTextArea getjTextAreaSpesifikasi() {
        return jTextAreaSpesifikasi;
    }

    private void jButtonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbahActionPerformed
        mainJFrame.jButtonUbahAlatActionPerformed(idAlat);
    }//GEN-LAST:event_jButtonUbahActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        mainJFrame.jButtonHapusAlatActionPerformed(idAlat);
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jCheckBoxPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPilihActionPerformed
        mainJFrame.jCheckBoxPilihAlatActionPerformed(idAlat);
    }//GEN-LAST:event_jCheckBoxPilihActionPerformed

    private void jButtonUbah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbah2ActionPerformed
        jButtonUbahActionPerformed(evt);
    }//GEN-LAST:event_jButtonUbah2ActionPerformed

    private void jButtonHapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapus2ActionPerformed
        jButtonHapusActionPerformed(evt);
    }//GEN-LAST:event_jButtonHapus2ActionPerformed

    private void jButtonFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFotoActionPerformed

    private void jButtonFoto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoto2ActionPerformed
        jButtonFotoActionPerformed(evt);
    }//GEN-LAST:event_jButtonFoto2ActionPerformed

    private void jToggleButtonPerkecilActionPerformed(java.awt.event.ActionEvent evt) {
        checkJToggleButtonPerkecil(jToggleButtonPerkecil.isSelected());
        mainJFrame.jToggleButtonPerkecilActionPerformed(idAlat);
    }

    public void checkJToggleButtonPerkecil(boolean checked) {
        if (checked) {
            jToggleButtonPerkecil.setText("🗖");
            jPanelAlat.setVisible(false);
            jButtonFoto2.setVisible(true);
            jButtonUbah2.setVisible(true);
            jButtonHapus2.setVisible(true);
            jButtonFoto.setVisible(false);
            jButtonUbah.setVisible(false);
            jButtonHapus.setVisible(false);
        } else {
            jToggleButtonPerkecil.setText("🗕");
            jPanelAlat.setVisible(true);
            jButtonFoto2.setVisible(false);
            jButtonUbah2.setVisible(false);
            jButtonHapus2.setVisible(false);
            jButtonFoto.setVisible(true);
            jButtonUbah.setVisible(true);
            jButtonHapus.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFoto;
    private javax.swing.JButton jButtonFoto2;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonHapus2;
    private javax.swing.JButton jButtonUbah;
    private javax.swing.JButton jButtonUbah2;
    private javax.swing.JCheckBox jCheckBoxPilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelKategoriAlat;
    private javax.swing.JLabel jLabelMerk;
    private javax.swing.JLabel jLabelRuangan;
    private javax.swing.JPanel jPanelAlat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextAreaSpesifikasi;
    private javax.swing.JToggleButton jToggleButtonPerkecil;
    // End of variables declaration//GEN-END:variables
}
