/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package waleta_system.Maintenance.view.alat;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.TimeZone;
import java.util.function.Consumer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.border.TitledBorder;
import waleta_system.Maintenance.controller.IconTitleBorderFactory;
import waleta_system.Maintenance.view.MainFrame_Maintenance;

/**
 *
 * @author User
 */
public class DaftarTemuanJPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form DaftarAlatJPanel
     * @param mainJFrame
     * @param idAlat
     */
    public DaftarTemuanJPanel(final MainFrame_Maintenance mainJFrame, final int idAlat) {
        initComponents();

        String gambar = "";
        if (mainJFrame.alats.get(idAlat).getStatusTemuan()== 1) {//pending
            gambar = "box_important.png";
            setBackground(new Color(255, 150, 150));
            jPanelAlat.setBackground(new Color(255, 150, 150));
        } else if (mainJFrame.alats.get(idAlat).getStatusTemuan() == 2) {//on work
            gambar = "work.png";
            setBackground(new Color(255, 200, 100));
            jPanelAlat.setBackground(new Color(255, 200, 100));
        } else if (mainJFrame.alats.get(idAlat).getStatusTemuan() == 3) {//on progress
            gambar = "time.png";
            setBackground(new Color(255, 150, 150));
            jPanelAlat.setBackground(new Color(255, 150, 150));
        } else if (mainJFrame.alats.get(idAlat).getStatusTemuan() == 4) {//finish
            gambar = "task_completed.png";
            setBackground(new Color(100, 200, 100));
            jPanelAlat.setBackground(new Color(100, 200, 100));
        }
        final SimpleDateFormat simpleDateFormat = new SimpleDateFormat("EEEEE, dd MMMM yyyy - HH:mm:ss", new Locale("in", "ID"));
        simpleDateFormat.setTimeZone(TimeZone.getTimeZone("Asia/Jakarta"));
        //TitledBorder title = javax.swing.BorderFactory.createTitledBorder(mainJFrame.alats.get(idAlat).getIdAlat() + " (" + simpleDateFormat.format(mainJFrame.alats.get(idAlat).getTglLapor()) + ")");
        
        try {
            Image image = ImageIO.read(new File(getClass().getResource("/waleta_system/Images/"+gambar).toString().replace("file:/", "").replace("%20", " ")));
            final Image newImage = image.getScaledInstance(16, 16, Image.SCALE_SMOOTH);
            IconTitleBorderFactory.CustomTitledBorder title = (IconTitleBorderFactory.CustomTitledBorder) IconTitleBorderFactory.create(new Consumer<JLabel>() {
                @Override
                public void accept(JLabel t) {
                    t.setText(mainJFrame.alats.get(idAlat).getIdAlat() + " (" + simpleDateFormat.format(mainJFrame.alats.get(idAlat).getTglLapor()) + ")");
                }
            }, new Consumer<JLabel>() {
                @Override
                public void accept(JLabel t) {
                    t.setIcon(new ImageIcon(newImage));
                }
            });
            title.setTitlePosition(TitledBorder.BELOW_TOP);
            setBorder(title);
        } catch (IOException ex) {
            Logger.getLogger(DaftarTemuanJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (mainJFrame.alats.get(idAlat).getRuangan() == null) {
            jLabelRuangan.setText("-");
        } else if (mainJFrame.alats.get(idAlat).getRuangan().getNamaRuangan().equals("")) {
            jLabelRuangan.setText("-");
        } else {
            jLabelRuangan.setText(mainJFrame.alats.get(idAlat).getRuangan().getNamaRuangan());
        }
        if (mainJFrame.alats.get(idAlat).getKategoriAlat() == null) {
            jLabelKategoriAlat.setText("-");
        } else if (mainJFrame.alats.get(idAlat).getKategoriAlat().getNamaAlat().equals("")) {
            jLabelKategoriAlat.setText("-");
        } else {
            jLabelKategoriAlat.setText(mainJFrame.alats.get(idAlat).getKategoriAlat().getNamaAlat());
        }
        if (mainJFrame.alats.get(idAlat).getMerk().equals("")) {
            jLabelMerk.setText("-");
        } else {
            jLabelMerk.setText(mainJFrame.alats.get(idAlat).getMerk());
        }

        jTextAreaKeluhan.setText(mainJFrame.alats.get(idAlat).getKeluhan());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAlat = new javax.swing.JPanel();
        jLabelKategoriAlat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaKeluhan = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMerk = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelRuangan = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Alat 1"));
        setMaximumSize(new java.awt.Dimension(325, 32767));
        setMinimumSize(new java.awt.Dimension(325, 0));

        jLabelKategoriAlat.setText("-");

        jTextAreaKeluhan.setEditable(false);
        jTextAreaKeluhan.setColumns(20);
        jTextAreaKeluhan.setRows(5);
        jScrollPane1.setViewportView(jTextAreaKeluhan);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Merk ");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Keluhan");

        jLabelMerk.setText("-");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Kategori Alat");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Ruangan");

        jLabelRuangan.setText("-");

        javax.swing.GroupLayout jPanelAlatLayout = new javax.swing.GroupLayout(jPanelAlat);
        jPanelAlat.setLayout(jPanelAlatLayout);
        jPanelAlatLayout.setHorizontalGroup(
            jPanelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlatLayout.createSequentialGroup()
                        .addGroup(jPanelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanelAlatLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMerk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelAlatLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelAlatLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelKategoriAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanelAlatLayout.setVerticalGroup(
            jPanelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelMerk)
                    .addComponent(jLabel4)
                    .addComponent(jLabelRuangan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelKategoriAlat)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAlat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelKategoriAlat;
    private javax.swing.JLabel jLabelMerk;
    private javax.swing.JLabel jLabelRuangan;
    private javax.swing.JPanel jPanelAlat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaKeluhan;
    // End of variables declaration//GEN-END:variables
}
