/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package waleta_system.Maintenance.view.kategoriAlat;

import javax.swing.JOptionPane;
import waleta_system.Maintenance.controller.KategoriAlatDAO;
import waleta_system.Maintenance.controller.PathHelper;
import waleta_system.Maintenance.model.KategoriAlat;
import waleta_system.Maintenance.view.MainFrame_Maintenance;

/**
 *
 * @author User
 */
public class TambahUbahKategoriAlatJDialog extends javax.swing.JDialog {

    private MainFrame_Maintenance mainJFrame;
    private int idKategoriAlatUpdate;
    public enum KategoriDialog {
        TAMBAH,
        UBAH
    }
    private KategoriDialog kategoriDialog;

    /**
     * Creates new form TambahKategoriAlatJDialog
     */
    public TambahUbahKategoriAlatJDialog(java.awt.Frame parent, boolean modal, MainFrame_Maintenance mainJFrame, KategoriDialog kategoriDialog, KategoriAlat kategoriAlat) {
        this(parent, modal, mainJFrame, kategoriDialog);
        idKategoriAlatUpdate = kategoriAlat.getIdKategoriAlat();
        jTextFieldNamaAlat.setText(kategoriAlat.getNamaAlat());
        jTextFieldIconHealthy.setText(kategoriAlat.getIconHealthy());
        jTextFieldIconInRepair.setText(kategoriAlat.getIconInRepair());
        jTextFieldIconDamaged.setText(kategoriAlat.getIconDamaged());
        javax.swing.ImageIcon currImageIconHealthy;
        if (kategoriAlat.getIconHealthy() == null) {
            currImageIconHealthy = null;
        } else {
            currImageIconHealthy = new javax.swing.ImageIcon((PathHelper.path + "kategori_alat/icon_healthy/" + kategoriAlat.getIconHealthy()));
        }
        jLabelPratinjauIconHealthy.setIcon(currImageIconHealthy);
        
        javax.swing.ImageIcon currImageIconInRepair;
        if (kategoriAlat.getIconInRepair() == null) {
            currImageIconInRepair = null;
        } else {
            currImageIconInRepair = new javax.swing.ImageIcon((PathHelper.path + "kategori_alat/icon_in_repair/" + kategoriAlat.getIconInRepair()));
        }
        jLabelPratinjauIconInRepair.setIcon(currImageIconInRepair);
        
        
        javax.swing.ImageIcon currImageIconDamaged;
        if (kategoriAlat.getIconDamaged() == null) {
            currImageIconDamaged = null;
        } else {
            currImageIconDamaged = new javax.swing.ImageIcon((PathHelper.path + "kategori_alat/icon_damaged/" + kategoriAlat.getIconDamaged()));
        }
        jLabelPratinjauIconDamaged.setIcon(currImageIconDamaged);
    }

    public TambahUbahKategoriAlatJDialog(java.awt.Frame parent, boolean modal, MainFrame_Maintenance mainJFrame, KategoriDialog kategoriDialog) {
        super(parent, modal);
        initComponents();
        this.mainJFrame = mainJFrame;
        this.kategoriDialog = kategoriDialog;
        switch (kategoriDialog) {
            case TAMBAH:
                setTitle("Waleta Maintenance - Waleta Maintenance - Tambah Kategori Alat");
                break;
            case UBAH:
                setTitle("Waleta Maintenance - Waleta Maintenance - Ubah Kategori Alat");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserIconHealthy = new javax.swing.JFileChooser();
        jFileChooserIconInRepair = new javax.swing.JFileChooser();
        jFileChooserIconDamaged = new javax.swing.JFileChooser();
        jButtonSimpan = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonPilihBerkasIconHealthy = new javax.swing.JButton();
        jButtonPilihBerkasIconInRepair = new javax.swing.JButton();
        jTextFieldIconDamaged = new javax.swing.JTextField();
        jButtonPilihBerkasIconDamaged = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelPratinjauIconHealthy = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIconInRepair = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabelPratinjauIconInRepair = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabelPratinjauIconDamaged = new javax.swing.JLabel();
        jTextFieldNamaAlat = new javax.swing.JTextField();
        jTextFieldIconHealthy = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jFileChooserIconHealthy.setDialogTitle("Pilih Berkas Icon Healthy");
        jFileChooserIconHealthy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserIconHealthyActionPerformed(evt);
            }
        });

        jFileChooserIconInRepair.setDialogTitle("Pilih Berkas Icon In Repair");
        jFileChooserIconInRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserIconInRepairActionPerformed(evt);
            }
        });

        jFileChooserIconDamaged.setDialogTitle("Pilih Berkas Icon Damaged");
        jFileChooserIconDamaged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserIconDamagedActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Waleta Maintenance - Tambah Kategori Alat");

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jButtonBatal.setText("Batal");
        jButtonBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel4.setPreferredSize(new java.awt.Dimension(500, 459));

        jLabel2.setText("Nama Alat");

        jButtonPilihBerkasIconHealthy.setText("Pilih Berkas");
        jButtonPilihBerkasIconHealthy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPilihBerkasIconHealthy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPilihBerkasIconHealthyActionPerformed(evt);
            }
        });

        jButtonPilihBerkasIconInRepair.setText("Pilih Berkas");
        jButtonPilihBerkasIconInRepair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPilihBerkasIconInRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPilihBerkasIconInRepairActionPerformed(evt);
            }
        });

        jButtonPilihBerkasIconDamaged.setText("Pilih Berkas");
        jButtonPilihBerkasIconDamaged.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPilihBerkasIconDamaged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPilihBerkasIconDamagedActionPerformed(evt);
            }
        });

        jLabel5.setText("Icon Damaged");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pratinjau Icon Healthy"));

        jLabelPratinjauIconHealthy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane1.setViewportView(jLabelPratinjauIconHealthy);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setText("Icon In Repair");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pratinjau Icon In Repair"));

        jLabelPratinjauIconInRepair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane2.setViewportView(jLabelPratinjauIconInRepair);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pratinjau Icon Damaged"));

        jLabelPratinjauIconDamaged.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane3.setViewportView(jLabelPratinjauIconDamaged);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setText("Icon Healthy");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextFieldIconHealthy, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPilihBerkasIconHealthy))
                            .addComponent(jTextFieldNamaAlat)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(9, 9, 9)
                        .addComponent(jTextFieldIconInRepair, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPilihBerkasIconInRepair))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(9, 9, 9)
                        .addComponent(jTextFieldIconDamaged, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPilihBerkasIconDamaged))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNamaAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldIconHealthy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPilihBerkasIconHealthy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldIconInRepair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPilihBerkasIconInRepair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldIconDamaged, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPilihBerkasIconDamaged))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane4.setViewportView(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 417, Short.MAX_VALUE)
                        .addComponent(jButtonBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSimpan)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSimpan)
                    .addComponent(jButtonBatal))
                .addGap(8, 8, 8))
        );

        setSize(new java.awt.Dimension(546, 512));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPilihBerkasIconHealthyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPilihBerkasIconHealthyActionPerformed
        jFileChooserIconHealthy.showDialog(TambahUbahKategoriAlatJDialog.this, "Pilih");
    }//GEN-LAST:event_jButtonPilihBerkasIconHealthyActionPerformed

    private void jFileChooserIconHealthyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserIconHealthyActionPerformed
        jTextFieldIconHealthy.setText(jFileChooserIconHealthy.getSelectedFile().getAbsolutePath());
        javax.swing.ImageIcon currImageIcon;
        if (jFileChooserIconHealthy.getSelectedFile().getAbsolutePath() == null) {
            currImageIcon = null;
        } else {
            currImageIcon = new javax.swing.ImageIcon(jFileChooserIconHealthy.getSelectedFile().getAbsolutePath());
        }
        jLabelPratinjauIconHealthy.setIcon(currImageIcon);
    }//GEN-LAST:event_jFileChooserIconHealthyActionPerformed

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        switch (kategoriDialog) {
            case TAMBAH:
                try {
                    KategoriAlat newKategoriAlat = new KategoriAlat(jTextFieldNamaAlat.getText(), jTextFieldIconHealthy.getText(), jTextFieldIconInRepair.getText(), jTextFieldIconDamaged.getText());
                    if(new KategoriAlatDAO().insert(mainJFrame, newKategoriAlat))
                    {
                        JOptionPane.showMessageDialog(TambahUbahKategoriAlatJDialog.this, "Sukses menyimpan kategori alat", "Sukses Simpan", JOptionPane.INFORMATION_MESSAGE);
                        mainJFrame.refreshKategoriAlat();
                        dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(TambahUbahKategoriAlatJDialog.this, "Gagal menyimpan kategori alat", "Sukses Simpan", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(TambahUbahKategoriAlatJDialog.this, "Gagal menyimpan kategori alat: "+e.getLocalizedMessage(), "Gagal Simpan", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case UBAH:
                try {
                    KategoriAlat newKategoriAlat = new KategoriAlat(jTextFieldNamaAlat.getText(), jTextFieldIconHealthy.getText(), jTextFieldIconInRepair.getText(), jTextFieldIconDamaged.getText());
                    if(new KategoriAlatDAO().update(mainJFrame, idKategoriAlatUpdate, newKategoriAlat))
                    {
                        JOptionPane.showMessageDialog(TambahUbahKategoriAlatJDialog.this, "Sukses menyimpan kategori alat", "Sukses Simpan", JOptionPane.INFORMATION_MESSAGE);
                        mainJFrame.refreshKategoriAlat();
                        dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(TambahUbahKategoriAlatJDialog.this, "Gagal menyimpan kategori alat", "Sukses Simpan", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(TambahUbahKategoriAlatJDialog.this, "Gagal menyimpan kategori alat: "+e.getLocalizedMessage(), "Gagal Simpan", JOptionPane.ERROR_MESSAGE);
                }
                break;
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonPilihBerkasIconInRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPilihBerkasIconInRepairActionPerformed
        jFileChooserIconInRepair.showDialog(TambahUbahKategoriAlatJDialog.this, "Pilih");
    }//GEN-LAST:event_jButtonPilihBerkasIconInRepairActionPerformed

    private void jButtonPilihBerkasIconDamagedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPilihBerkasIconDamagedActionPerformed
        jFileChooserIconDamaged.showDialog(TambahUbahKategoriAlatJDialog.this, "Pilih");
    }//GEN-LAST:event_jButtonPilihBerkasIconDamagedActionPerformed

    private void jFileChooserIconInRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserIconInRepairActionPerformed
        jTextFieldIconInRepair.setText(jFileChooserIconInRepair.getSelectedFile().getAbsolutePath());
        javax.swing.ImageIcon currImageIcon;
        if (jFileChooserIconInRepair.getSelectedFile().getAbsolutePath() == null) {
            currImageIcon = null;
        } else {
            currImageIcon = new javax.swing.ImageIcon(jFileChooserIconInRepair.getSelectedFile().getAbsolutePath());
        }
        jLabelPratinjauIconInRepair.setIcon(currImageIcon);
    }//GEN-LAST:event_jFileChooserIconInRepairActionPerformed

    private void jFileChooserIconDamagedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserIconDamagedActionPerformed
        jTextFieldIconDamaged.setText(jFileChooserIconDamaged.getSelectedFile().getAbsolutePath());
        javax.swing.ImageIcon currImageIcon;
        if (jFileChooserIconDamaged.getSelectedFile().getAbsolutePath() == null) {
            currImageIcon = null;
        } else {
            currImageIcon = new javax.swing.ImageIcon(jFileChooserIconDamaged.getSelectedFile().getAbsolutePath());
        }
        jLabelPratinjauIconDamaged.setIcon(currImageIcon);
    }//GEN-LAST:event_jFileChooserIconDamagedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonPilihBerkasIconDamaged;
    private javax.swing.JButton jButtonPilihBerkasIconHealthy;
    private javax.swing.JButton jButtonPilihBerkasIconInRepair;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JFileChooser jFileChooserIconDamaged;
    private javax.swing.JFileChooser jFileChooserIconHealthy;
    private javax.swing.JFileChooser jFileChooserIconInRepair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelPratinjauIconDamaged;
    private javax.swing.JLabel jLabelPratinjauIconHealthy;
    private javax.swing.JLabel jLabelPratinjauIconInRepair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextFieldIconDamaged;
    private javax.swing.JTextField jTextFieldIconHealthy;
    private javax.swing.JTextField jTextFieldIconInRepair;
    private javax.swing.JTextField jTextFieldNamaAlat;
    // End of variables declaration//GEN-END:variables
}
